project_id = "inqqnsvlimtpjxjxuzaf"

[functions.api-sync-vehicles]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://inqqnsvlimtpjxjxuzaf.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[functions.admin-users]
verify_jwt = true

[functions.performance-collector]
verify_jwt = false

[functions.admin-user-operations]
verify_jwt = true

[functions.registration-emails]
verify_jwt = false

[functions.secure-file-upload]
verify_jwt = true

[functions.translate-message]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.generate-dashboard-images]
verify_jwt = false

[functions.send-mass-notification-emails]
verify_jwt = true

[functions.send-vehicle-contact-details]
verify_jwt = true

[functions.run-security-audit]
verify_jwt = true

[functions.generate-static-image]
verify_jwt = true

[functions.replace-static-image]
verify_jwt = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15
