
export default {
  // Calculator
  'calculator.title': 'Import Cost Calculator',
  'calculator.subtitle': 'For professionals (B2B) - Vehicle import to Spain',
  
  // Form
  'calculator.form.title': 'Vehicle and Import Details',
  'calculator.form.description': 'Enter the details to calculate import costs',
  
  // Tabs
  'calculator.tabs.vehicle': 'Vehicle',
  'calculator.tabs.fiscal': 'Fiscal',
  'calculator.tabs.emissions': 'Emissions',
  'calculator.tabs.services': 'Services',
  
  // Vehicle tab
  'calculator.vehicle.type': 'Vehicle type',
  'calculator.vehicle.selectType': 'Select type',
  'calculator.vehicle.car': 'Car',
  'calculator.vehicle.commercial': 'Commercial',
  'calculator.vehicle.motorcycle': 'Motorcycle',
  'calculator.vehicle.originCountry': 'Country of origin',
  'calculator.vehicle.selectCountry': 'Select country',
  'calculator.vehicle.isNew': 'New vehicle',
  'calculator.vehicle.newTooltip': 'A vehicle is considered new if it is less than 6 months old or has less than 6,000 km',
  
  // Fiscal tab
  'calculator.fiscal.price': 'Vehicle price (€)',
  'calculator.fiscal.includesVAT': 'Price includes VAT',
  'calculator.fiscal.vatTooltip': 'For intra-community B2B operations, VAT is self-assessed in Spain',
  'calculator.fiscal.ivtmTax': 'Circulation tax (IVTM) (€)',
  'calculator.fiscal.ivtmTooltip': 'Annual municipal tax varies by vehicle power and municipality. Typically ranges from 30€ to 200€.',
  
  // Emissions tab
  'calculator.emissions.co2': 'CO2 emissions (g/km)',
  'calculator.emissions.taxRate': 'Applicable registration tax',
  
  // Services tab
  'calculator.services.agency': 'Hire agency services',
  'calculator.services.agencyTooltip': 'Includes management of administrative procedures',
  'calculator.services.transport': 'Include transport',
  
  // Buttons
  'calculator.buttons.next': 'Next step',
  'calculator.buttons.calculate': 'Calculate costs',
  'calculator.buttons.printCalculation': 'Print calculation',
  
  // Results
  'calculator.results.title': 'Cost Summary',
  'calculator.results.netPrice': 'Net price',
  'calculator.results.vat': 'VAT (21%)',
  'calculator.results.vatInfo': 'Self-assessed VAT in Spain for B2B operations',
  'calculator.results.matriculation': 'Registration tax',
  'calculator.results.matriculationInfo': 'Based on CO2 emissions',
  'calculator.results.adminCostsTitle': 'Administrative costs',
  'calculator.results.dgtFee': 'DGT Registration fee',
  'calculator.results.technicalSheet': 'Technical data sheet',
  'calculator.results.itv': 'Import vehicle inspection',
  'calculator.results.trafficFee': 'Traffic fee (circulation permit)',
  'calculator.results.ivtm': 'Circulation tax (IVTM)',
  'calculator.results.ivtmInfo': 'Annual municipal tax (varies by power and location)',
  'calculator.results.agency': 'Agency services',
  'calculator.results.transport': 'Transport',
  'calculator.results.total': 'Total cost',
  
  // Info
  'calculator.info.title': 'Important Information',
  'calculator.info.disclaimer': 'Calculations are estimates and may vary. Consult with a professional for specific information.',
  'calculator.info.b2bOnly': 'This calculator is designed exclusively for B2B imports (between professionals).',
  'calculator.info.vatInfo': 'For intra-community B2B operations, the Spanish buyer self-assesses VAT, declaring and deducting it simultaneously.',
  
  // Printable document
  'calculator.printable.title': 'Vehicle Import Cost Calculation',
  'calculator.printable.date': 'Date',
  'calculator.printable.vehicleDetails': 'Vehicle Details',
  'calculator.printable.footer': 'Generated by KONECT VO Automotive Marketplace - Import Calculator',
  
  // Common
  'common.yes': 'Yes',
  'common.no': 'No'
};
