
export default {
  // Terms and conditions
  'terms.introduction.title': 'Introduction',
  'terms.introduction.subtitle1': 'Right of withdrawal and legal scope',
  'terms.introduction.p1': '1.1.1 KONTACT VO, S.L., with CIF B00000000 and address for notifications at BBBBBBBBBBBBBBBBBB, registered in the Commercial Registry of Madrid (Volume: 00000 Sheet: 000Section: 0Page: M-00000) is responsible for the contents and operations of KONTACTVO.es The domain belongs to third parties. KONTACT VO S.L. acts exclusively as an intermediary, providing professionals and individuals with a commercial portal and platform for vehicles www.Kontactvo.es. Kontact VO, S.L. does not appear in any case as a buying or selling party in the sales made through said website.',
  'terms.introduction.p2': '1.1.2 Legal scope KONTACTVO S.L. offers a commercial platform on the Internet. The conditions described below affect the use of the applications on the KONTACTVO S.L. website. These conditions are in Spanish. The contracting parties must be exclusively natural persons over 18 years of age or legal entities, with legal capacity to enter into binding contracts. These conditions will be expressly submitted and with waiver of any other jurisdiction to the competence of the Courts and Tribunals of the city of Sabadell. These conditions will be governed by the provisions of Spanish regulations. In the event that any of these conditions is or is declared ineffective, null or unrealizable, this will not affect the effectiveness of the rest, which will remain fully valid and effective. Such condition in question will be understood, without requiring any further actions by the parties regarding form, content, time and measure, replaced by a provision that is valid, effective and realizable and that comes as close as possible from any perspective, and especially the economic one, to the purpose and spirit of the provision being remedied.',
  
  'terms.introduction.subtitle2': 'User categories and usage rights',
  'terms.introduction.p3': '1.2.1 It is a requirement to buy or sell through www.KONTACTVO.es to be properly registered. Users must not register with several names at the same time or take actions with a false identity. There is no right to register and use the website. KONTACT VO S.L. will not be responsible for any failures that may occur in communications, including deletion, incomplete transmission or delays in sending, nor does it commit to the transmission network being operational at all times. It will also not be responsible if a third party, breaking the security measures established by KONTACT VO S.L., accesses messages, introduces computer viruses or causes any other type of damage to the computer system that may affect its users. KONTACT VO S.L. does not control or guarantee the absence of computer viruses in services provided by third parties through the website that may cause alterations in your computer system (software and hardware) or in electronic documents and files stored in your computer system. KONTACT VO S.L. reserves the right to modify the applications of its website, block or delete users and/or offers at any time without the need to indicate the reasons.',
  'terms.introduction.p4': '1.2.2 Only registering as a Business user will imply a different registration where these General Auction Terms and Conditions will be taken into account as general conditions, with other special conditions being applicable to these Business users, which will be sent to them by email in the shortest possible time from when the user is registered in this category.',
  'terms.introduction.p5': '1.2.3 User registrations in any category will imply total acceptance of these General Auction Conditions. KONTACT VO S.L. is committed to sending precise instructions about the auction participation process at the time a user registers on the website. This sending will be done by email so this information must be true and correct at the time of registration. Likewise, KONTACT VO S.L. will provide the user with a control panel that will be accessible through a username and password, previously provided by the user, where they can access complete data of their profile and where they can update their data and preferences. Subsequently, KONTACT VO S.L. and at the time when the auction has ended, will send users the data of the counterparty so that they can communicate with them. KONTACT VO S.L. communications will end with the sending of the invoice for services rendered.',
  
  'terms.introduction.subtitle3': 'Vehicle registration',
  'terms.introduction.p6': '1.3.1 Vehicle age: All registered users can register vehicles that have been first registered after 1983.',
  'terms.introduction.p7': '1.3.2 Description: The seller must describe their item and all the conditions of sale on the item insertion page of the website. Announcements may include descriptive texts, graphics, photographs, and other content relevant to the sale. All inserted items must be included in the appropriate category. All relevant basic characteristics and qualities for the purchase decision must be indicated, as well as defects, which may reduce the value of the offered merchandise. In addition, the user must be informed in detail about the ownership of the offered vehicle and the payment and delivery conditions. Professionals who advertise vehicles to consumers are obliged to inform about legal guarantees. The description and images used must not infringe third-party copyrights and must refer exclusively to the offer (original images). Descriptions, drawings, and images must not contain advertising for items other than those being advertised, especially they must not refer to links to their own website or include data about phone numbers, etc.',
  
  'terms.introduction.subtitle4': 'Responsibility',
  'terms.introduction.p8': '1.4.1 KONTACT VO S.L. declares that it only provides a marketing portal for buyers and sellers. Possible sales contracts are carried out exclusively between the seller and the buyer. KONTACT VO S.L. is not responsible for the truthfulness or accuracy of the data, characteristics and conditions contained in the offers, promotions and advertising contained in the information provided. Similarly, the owners or marketers of the vehicles are solely responsible for the commercial operations that they conclude in relation to them. KONTACT VO S.L. is not responsible for possible loss of profit. KONTACT VO S.L. is also not responsible for technical problems or program errors. On the KONTACT VO S.L. Web pages, links to other Internet pages may be found. KONTACT VO S.L. does not offer or market the products and services available on the linked sites, so it assumes no responsibility of any kind in relation to the contents and information, or with the operations, which can be accessed or performed, as the case may be, through this portal and in general for the consequences that may arise from users\' access to them, regarding which it disclaims all responsibility. Such services are provided by third parties who act in all cases in their own name and on their own behalf, both in relation to the offer and the contracting of the services in question, and fully assume their management and operation, regardless of how users may have accessed them.',
  
  'terms.introduction.subtitle5': 'Contract closure, auction rules, binding term',
  'terms.introduction.p9': '1.5.1 With the registration of a vehicle on the KONTACT VO S.L. website, the seller makes a binding offer for the sale of the vehicle either at the offered fixed price or to the bidder who, during the offer period, makes the highest bid. The seller fully agrees to sell their offered vehicle, in the absence of higher offers, to the bidder who has bid for an amount corresponding to the minimum price. If two bidders make the same offer, the first offer made will be considered the highest offer. The bidder is subject to their bid until a higher offer exceeds it. If the bid is not raised, it prevails, unless special rules have been agreed, until 6:00 p.m. on the day on which the offer expires. Offers already made cannot be reduced or canceled. KONTACT VO S.L. records and stores all offers made. If doubts arise about the offers, KONTACT VO S.L. will clarify them in a binding manner for the contracting parties. An offer is not binding if the bidder when making the offer has made an obvious spelling mistake that could lead to errors or if a third party has made the offer by making improper use of the bidder\'s username or password, or if the bidder is not able to determine the identity of the seller within 10 working days after the end of the offer period. At the end of the offer period set by KONTACT VO S.L., in the event that nothing else has been agreed, the binding period will end at the expiration of the auction day and the sales contract will be carried out between the seller and the best bidder in accordance with Spanish law. Both contracting parties are obliged to close the deal. The seller undertakes to deliver the vehicle in the described condition to the best bidder. The best bidder has the duty to collect the vehicle and pay for it. The same will apply when a contract has been made through the customer service center or mediated in some other way by KONTACT VO S.L. In the event that a vehicle has been sold through www.KONTACTVO.es, both the buyer and the seller undertake to print and use the contract directly from www.autorola.es. The purchase note will also be sent by email or fax. It must be checked that the purchase note or contract sent by KONTACT VO S.L. is correct.',
  'terms.introduction.p10': '1.5.2 Exclusivity in KONTACT VO S.L. mediation Once the sale or auction has ended and the contact details of the counterparty are known, the user undertakes to respect KONTACT VO S.L. as an auction intermediary and to pay the stipulated amounts as commission for its intermediation work. In the event that KONTACT VO S.L. becomes aware that two users have contacted each other and finalized the sale of the vehicle excluding the company from the business, it may initiate the necessary legal actions to claim payment for the services rendered, and may request a claim for damages.',
  'terms.introduction.p11': '1.5.3 Basic principles for online auctions As long as a vehicle is sold in an online auction, the user may only offer bidders who have bid on that item similar types of vehicles and merchandise only in the form of an offer registered on the KONTACT VO S.L. website, not through other means, such as e.g. by email (withdrawal of bidders). This is also valid after the offer period has elapsed. Users are not authorized to manipulate the development of the online auction by making bids through another user account or through the intervention of a third party. In particular, the seller is prohibited from making bids during the offer period for the offers that they themselves have registered. The same vehicle cannot be offered simultaneously in online auctions taking place at the same time. This will not apply in the case that the user has several vehicles and merchandise of the same type. It is prohibited to make offers using automatic data processing methods (e.g. programs known as "Sniffers").',
  'terms.introduction.p12': '1.5.4 Auction development KONTACT VO S.L. controls the start, end and development of the auction. KONTACT VO S.L. reserves the right to suspend or modify planned auctions. KONTACT VO S.L. is authorized to cancel auctions without having to give reasons for it. The cancellation may occur both before and during the auction. Auctions already held cannot be canceled.',
  'terms.introduction.p13': '1.6 Extended auction',

  'terms.delivery.title': 'Delivery and buyer inspection right',
  'terms.delivery.subtitle1': 'Location',
  'terms.delivery.p1': '2.1.1 The delivery of the vehicle takes place, in the case that another end has not been agreed, at the moment in which the buyer picks it up. The collection must be carried out at the address indicated by the seller within the postal code area, and which is indicated in the description. If no address is indicated within the mentioned postal code area, the vehicle will be collected at the seller\'s address. When registering the vehicle, the seller has the possibility of offering the buyer the delivery of the vehicle elsewhere, instead of the buyer collecting it at the seller\'s address. This place can be the buyer\'s address or another place. Optionally, this clause will replace the collection. Despite the seller selecting this possibility, the buyer can always agree to collect the vehicle at the seller\'s address, if preferred.',
  
  'terms.delivery.subtitle2': 'Deadline',
  'terms.delivery.p2': '2.2.1 The delivery must be made within a maximum period of 5 working days after the contract becomes effective. The seller undertakes that the buyer picks up the vehicle within the indicated period in the interval between 9 and 17 hours, Central European time. If it happens that the contracting parties do not agree on the time, the buyer will set it within the indicated interval, always leaving a period of at least 24 hours for the seller.',
  
  'terms.delivery.subtitle3': 'Inspection',
  'terms.delivery.p3': '2.3.1 Check for damages and if there are differences with what was published, reflect them in the exit slip. The vehicle provider is not responsible for the difference in exterior damage (sheet metal and paint) that may be in the vehicle once removed from the facilities.',
  
  'terms.delivery.subtitle4': 'Vehicle data',
  'terms.delivery.p4': '2.4.1 Before making the payment, the buyer is authorized to verify that the vehicle\'s chassis number and license plate, if applicable, match the ownership of the vehicle. The original vehicle ownership/registration certificate II, the vehicle circulation permit/registration certificate I, the general inspection document and the combustion gas control document must be delivered to the buyer, all together with the vehicle.',

  'terms.payment.title': 'Vehicle payment',
  'terms.payment.subtitle1': 'Payment',
  'terms.payment.p1': '3.1.1 The entire purchase price, unless there are special contracting conditions, must be made effective by the buyer at the time of delivery of the vehicle, the original registration certification and all documentation linked to the vehicle. If one of the contracting parties requests a receipt, the other contracting party is obliged to provide a credit note.',
  
  'terms.payment.subtitle2': 'Payments in open auction',
  'terms.payment.p2': '3.2.1 We remind you that Autorola Spain is a mere intermediary and we recommend that you verify the condition of the vehicle on-site before making the payment. When the sale is closed, KONTACT VO will put the seller and the buyer in contact to finalize the transaction.',

  'terms.obligations.title': 'Obligations',
  'terms.obligations.subtitle1': 'Seller obligations',
  'terms.obligations.p1': '4.1.1 The seller is responsible for ensuring that the vehicle is available, that all data indicated about the vehicle is correct, true and sufficient and that the vehicle has no defects. The seller guarantees that they are the legal owner of the vehicle and that there are no third-party rights (reservation of ownership, judicial execution, right of preference, prohibition of alienation or other rights) that limit or prevent the sale of the vehicle without charges. This will not apply when the seller has informed about these rights in the description of the vehicle and when they have agreed with the buyer that the buyer will fulfill or assume these rights when closing the sales contract. Before registering the vehicle, the seller must ensure that all possible obligations and other rights regarding the vehicle related to the transfer of ownership can be fulfilled at the latest at the time of delivery. If the vehicle is delivered with a provisional registration, civil liability insurance valid at the time of delivery will be required. If the vehicle is not delivered registered, it will not be insured at the time of transfer.',
  
  'terms.obligations.subtitle2': 'Buyer obligations',
  'terms.obligations.p2': '4.2.1 If the buyer obtains the vehicle with a valid registration, they commit to indicate the change of owner within a maximum period of three days after delivery. If the buyer has been the best bidder with their offer on www.KONTACTVO.es according to the bidding rules or has accepted the purchase in another way, a contract will be carried out between the buyer and the seller. The buyer has the obligation to collect the vehicle and make the agreed sum effective. Reference is made to the other provisions on responsibilities and obligations stipulated in the auction conditions.',
  
  'terms.obligations.subtitle3': 'Disputes between buyer and seller',
  'terms.obligations.p3': '4.3.1 If a claim has been filed in due time and there is a breach/defect for which the other contracting party is responsible, retroactive settlements or claims for compensation will be carried out in accordance with Spanish law. If the buyer or seller files a claim against the other contracting party, the transport costs will be set at a fixed amount. In the event that, according to an agreement of the contracting parties, more transports of the vehicle have been produced, the amount of transport costs will be increased. In the event of disputes between the buyer and seller that cannot be resolved immediately by mutual agreement, the parties will be asked to take legal action. In the event of a dispute between the buyer and the seller, a copy of the contract together with a description of the reason must be sent immediately to KONTACT VO S.L. This will be used for statistical and registration purposes and will not imply, in any case, that KONTACT VO S.L. assumes the role of an involved party. In any case, KONTACT VO S.L.\'s right to a commission will not be affected and the parties undertake to satisfy it, as set out in clause 1.5.2.',

  'terms.registration.title': 'Registration, blocking, suspension and termination',
  'terms.registration.p1': '5.1.1 To be able to use all the services of KONTACT VO S.L., a "user" must be registered. There is no right to register on KONTACT VO S.L. Registration is free. It is carried out by opening a user account and presenting the declaration of conformity to the corresponding general business conditions. With the registration, a contract is carried out between KONTACT VO S.L. and the "user" on the use of the vehicle auction platform www.autorola.es. The data that KONTACT VO S.L. requests during registration must be complete and correct. If there is a modification in the "user" data after registration, the "user" has the duty to communicate said modification to KONTACT VO S.L. During registration, the "user" will select a username and a password. The username must not be an email address or an Internet address nor must it violate third party rights, in particular name or brand rights. The password must be kept secret. The user is responsible for cases of misuse of the username and password. The user account is not transferable. KONTACT VO S.L. can block the user account at any time. At the moment a user account is blocked, this user will not be able to continue using the KONTACT VO S.L. websites and will not be able to register again without an express authorization from KONTACT VO S.L. The user can terminate the user contract at any time. For the declaration of termination, a written note or an email to servicioalcliente@autorola.es is sufficient. KONTACT VO S.L. can terminate the user contract with immediate effect at any time without the need to comply with deadlines.',

  'terms.fees.title': 'Fees',
  'terms.fees.p1': '6.1.1 Registration as a user on www.KONTACTVO.es is free. The amount of the vehicles is shown on the file of each one, with express mention of the inclusion or not of the corresponding taxes (VAT, Registration Tax, etc.) The amount of the commission is based on the current price list. This can be consulted on the Price List. Commissions must be made effective upon receipt of the invoice. They may be made effective through a transfer or a direct debit. If the payment cannot be made, the user must pay the additional expenses caused, in the case that they are responsible for the situation. KONTACT VO S.L. will send the user invoices by postal mail or to their email address. The user will incur in default without receiving another payment reminder two weeks after sending the invoice. The invoice amount includes the VAT in effect on the day of invoicing. The corresponding commission will be paid to the seller in the event that the other contracting party does not duly comply with the contract closed through the KONTACT VO S.L. website. The credit must be requested according to the planned procedure. Compensation with credits from accounts not yet granted is only authorized for payable and/or future credits as long as these credits are legally valid or indisputable.',

  'terms.prohibitedItems.title': 'Prohibited items',
  'terms.prohibitedItems.p1': '7.1.1 It is prohibited to offer vehicles whose offer, sale or acquisition violate legal provisions. In particular, the following vehicles should not be described or offered: vehicles whose request, offer or sale violates copyrights.',

  'terms.principles.title': 'General basic principles',
  'terms.principles.p1': '8.1.1 The user is obliged to comply with current law when using the KONTACT VO S.L. website and the service provisions of KONTACT VO S.L. If a contract is reached between users on the commercial platform, KONTACT VO S.L. will provide the necessary contact details. If the users are entrepreneurs, the laws in force in Spain will apply to the contracts concluded between these users in the market offered by KONTACT VO S.L., as long as nothing else has been agreed, expressly excluding the application of the United Nations Convention on Contracts for the International Sale of Goods. If one of the users who closes the contract is a consumer, the law of the country in which they have their habitual residence will apply. All users are prohibited from using the addresses obtained, contact details and email addresses for commercial advertising.',

  'terms.exemption.title': 'Exemption',
  'terms.exemption.p1': '9.1.1 The user exempts KONTACT VO S.L. from any liability regarding any claim from other users or third parties against KONTACT VO S.L. for the violation of their rights in the offers or contents that the user has registered on the website or for improper use of the KONTACT VO S.L. website by the user. The user will bear the costs of defending KONTACT VO S.L.\'s rights, including all lawyer and solicitor fees as well as court fees. This will not apply in the event that the violation of the right is not the responsibility of the user.',

  'terms.integrity.title': 'System integrity',
  'terms.integrity.p1': '10.1.1 The user is not authorized to use mechanisms, software or other routes in relation to the use of the KONTACT VO S.L. website that could hinder the operation of said website. The user is not authorized to take any measure that may entail a disproportionate or excessive load on the infrastructure. It is prohibited to copy, disclose, reproduce or use for another purpose the contents of the KONTACT VO S.L. website without the prior consent of the rights holder. This also affects copies made using "Robot/Crawler" search engine techniques (crawlers) or other automatic mechanisms. The reproduction and use on other websites of the design of the KONTACT VO S.L. website and the general terms of use is only authorized with the prior written consent of KONTACT VO S.L.',
};

