
export default {
  // Termini e condizioni
  'terms.introduction.title': 'Introduzione',
  'terms.introduction.subtitle1': 'Diritto di recesso e ambito legale',
  'terms.introduction.p1': '1.1.1 KONTACT VO, S.L., con CIF B00000000 e domicilio per le notifiche presso BBBBBBBBBBBBBBBBBB, iscritta nel Registro Mercantile di Madrid (Volume: 00000 Foglio: 000Sezione: 0Pagina: M-00000) è responsabile dei contenuti e delle operazioni di KONTACTVO.es. Il dominio appartiene a terzi. KONTACT VO S.L. agisce esclusivamente come intermediario, mettendo a disposizione di professionisti e privati un portale e una piattaforma commerciale di veicoli www.Kontactvo.es. Kontact VO, S.L. non figura in nessun caso come parte acquirente o venditrice nelle vendite effettuate tramite detto sito web.',
  'terms.introduction.p2': '1.1.2 Ambito legale KONTACTVO S.L. offre una piattaforma commerciale su Internet. Le condizioni descritte di seguito riguardano l\'uso delle applicazioni del sito web di KONTACTVO S.L. Queste condizioni sono in lingua spagnola. Le parti contraenti devono essere esclusivamente persone fisiche maggiorenni o persone giuridiche, con capacità giuridica di sottoscrivere contratti vincolanti. Le presenti condizioni saranno espressamente sottoposte e con rinuncia a qualsiasi altra giurisdizione alla competenza dei Tribunali della città di Sabadell. Le presenti condizioni saranno regolate dalle disposizioni della normativa spagnola. Nel caso in cui una delle presenti condizioni sia o fosse dichiarata inefficace, nulla o irrealizzabile, ciò non influirà sull\'efficacia delle restanti, le quali sussisteranno pienamente valide ed efficaci. Tale condizione in questione si intenderà, senza che per questo siano necessarie ulteriori azioni delle parti per quanto riguarda forma, contenuto, tempo e misura, sostituita da una disposizione che sia valida, efficace e realizzabile e che si avvicini il più possibile da qualunque prospettiva, e in particolare quella economica, alla finalità e spirito della disposizione oggetto di correzione.',
  
  'terms.introduction.subtitle2': 'Categorie di utenti e diritti d\'uso',
  'terms.introduction.p3': '1.2.1 È un requisito per comprare o vendere tramite www.KONTACTVO.es registrarsi debitamente. Gli utenti non devono registrarsi con diversi nomi contemporaneamente né compiere azioni con un\'identità falsa. Non esiste un diritto alla registrazione e all\'uso del sito web. KONTACT VO S.L. non sarà responsabile dei guasti che potrebbero verificarsi nelle comunicazioni, inclusa la cancellazione, trasmissione incompleta o ritardi nella trasmissione, non impegnandosi neanche a che la rete di trasmissione sia operativa in ogni momento. Non sarà nemmeno responsabile nel caso in cui un terzo, violando le misure di sicurezza stabilite da KONTACT VO S.L., acceda ai messaggi, introduca virus informatici o produca qualsiasi altro tipo di danno nel sistema informatico che possa ripercuotersi sui suoi utenti. KONTACT VO S.L. non controlla né garantisce l\'assenza di virus informatici nei servizi prestati da terzi attraverso il sito web che potrebbero produrre alterazioni nel suo sistema informatico (software e hardware) o nei documenti e file elettronici immagazzinati nel suo sistema informatico. KONTACT VO S.L. si riserva il diritto di modificare le applicazioni del suo sito web, bloccare o cancellare gli utenti e/o le offerte in qualsiasi momento e senza necessità di indicare i motivi.',
  'terms.introduction.p4': '1.2.2 Solo la registrazione di un utente Azienda comporterà una registrazione diversa dove queste Condizioni Generali di Asta saranno prese in considerazione come condizioni generali, essendo applicabili a questi utenti Azienda altre condizioni speciali, che saranno loro inviate per posta elettronica nel minor tempo possibile da quando si effettua la registrazione dell\'utente in questa categoria.',
  'terms.introduction.p5': '1.2.3 Le registrazioni di utente in qualsiasi categoria comporteranno l\'accettazione totale delle presenti Condizioni Generali di Asta. KONTACT VO S.L. si impegna all\'invio di istruzioni precise sul processo di partecipazione all\'asta nel momento in cui un utente si registra sul sito web. Questo invio si effettuerà per posta elettronica in modo che questo dato dovrà essere vero e corretto al momento della registrazione. Inoltre, KONTACT VO S.L. fornirà all\'utente un pannello di controllo che sarà accessibile mediante utente e password, precedentemente forniti dall\'utente, dove questi potrà avere accesso ai dati completi del suo profilo e dove potrà aggiornare i suoi dati e preferenze. Successivamente, KONTACT VO S.L. e nel momento in cui l\'asta sia terminata, invierà agli utenti i dati della controparte affinché possa comunicare con essa. Le comunicazioni di KONTACT VO S.L. termineranno con l\'invio della fattura per i servizi prestati.',
  
  'terms.introduction.subtitle3': 'Registrazione dei veicoli',
  'terms.introduction.p6': '1.3.1 Anzianità dei veicoli: Tutti gli utenti registrati possono registrare veicoli che siano stati immatricolati per la prima volta dopo l\'anno 1983.',
  'terms.introduction.p7': '1.3.2 Descrizione: Il venditore deve descrivere il suo articolo e tutte le condizioni di vendita nella pagina di inserimento articoli del sito web. Gli annunci potranno includere testi descrittivi, grafici, fotografie e altri contenuti pertinenti per la vendita. Tutti gli articoli inseriti dovranno essere inclusi nella categoria appropriata. Si devono indicare tutte le caratteristiche e qualità di base rilevanti per la decisione di acquisto, così come difetti, che possono ridurre il valore della merce offerta. Inoltre, si deve informare con dettaglio l\'utente sulla proprietà del veicolo offerto e le condizioni di pagamento e consegna. I professionisti che annunciano veicoli a consumatori hanno l\'obbligo di informare sulle garanzie legali. La descrizione e le immagini utilizzate non devono vulnerare i diritti d\'autore di terzi e devono fare riferimento esclusivamente all\'offerta (immagini originali). Le descrizioni, i disegni e le immagini non devono contenere pubblicità per altri articoli che non siano quelli che si annunciano, in special modo non devono rimandare a collegamenti al proprio sito web o includere dati su numeri di telefono, ecc.',
  
  'terms.introduction.subtitle4': 'Responsabilità',
  'terms.introduction.p8': '1.4.1 KONTACT VO S.L. dichiara che mette a disposizione unicamente un portale di commercializzazione per compratori e venditori. I possibili contratti di compravendita si svolgono esclusivamente tra il venditore e il compratore. KONTACT VO S.L. non è responsabile della veridicità o esattezza dei dati, caratteristiche e condizioni contenute nelle offerte, promozioni e pubblicità contenuta nell\'informazione che si facilita. Allo stesso modo, sono i proprietari o commercializzatori dei veicoli gli unici responsabili delle operazioni commerciali che in relazione con gli stessi concludono. KONTACT VO S.L. non si responsabilizza di un possibile lucro cessante. KONTACT VO S.L. nemmeno si responsabilizza dei problemi tecnici né degli errori del programma. Nelle pagine Web di KONTACT VO S.L. possono trovarsi collegamenti ad altre pagine di Internet. KONTACT VO S.L. non offre né commercializza i prodotti e servizi disponibili nei siti collegati per cui non assume responsabilità di nessun tipo in relazione con i contenuti e informazioni, né con le operazioni, a cui si può accedere o che si possono realizzare, a seconda del caso, attraverso questo portale e in generale delle conseguenze che si derivino dall\'accesso da parte degli utenti agli stessi, rispetto ai quali declina ogni responsabilità. Detti servizi sono prestati da terzi che agiscono in ogni caso in proprio nome e per proprio conto, sia in relazione con l\'offerta sia con la contrattazione dei servizi di cui si tratta, e assumono pienamente la loro gestione e sfruttamento, indipendentemente dalla forma in cui gli utenti abbiano potuto accedervi.',
  
  'terms.introduction.subtitle5': 'Chiusura del contratto, regole d\'asta, termine del vincolo',
  'terms.introduction.p9': '1.5.1 Con la registrazione di un veicolo sul sito web di KONTACT VO S.L., il venditore realizza un\'offerta vincolante per la vendita del veicolo sia per il prezzo fisso offerto sia all\'offerente che nel corso del periodo di offerta realizzi l\'offerta più alta. Il venditore si dichiara completamente d\'accordo a vendere il suo veicolo offerto, in caso di assenza di offerte più elevate, all\'offerente che abbia offerto per un importo che corrisponda al prezzo minimo. Se due offerenti realizzano la stessa offerta, si considererà la prima offerta realizzata come offerta più alta. L\'offerente è soggetto alla sua offerta fino a che un\'offerta più alta la superi. Se non si alza l\'offerta, questa prevale, a meno che non si siano accordate delle regole speciali, fino alle 18.00 ore del giorno in cui l\'offerta scada. Le offerte già realizzate non possono ridursi né annullarsi. KONTACT VO S.L. registra e conserva tutte le offerte realizzate. Se sorgono dubbi sulle offerte, KONTACT VO S.L. le chiarirà in forma vincolante per le parti contraenti. Un\'offerta non è vincolante se l\'offerente al realizzare l\'offerta ha commesso un errore di ortografia evidente al realizzare l\'offerta che potrebbe condurre a errori o se un terzo ha realizzato l\'offerta effettuando un uso indebito del nome dell\'utente o della password dell\'offerente, o se l\'offerente non è capace di determinare l\'identità del venditore nel periodo di 10 giorni lavorativi dopo la finalizzazione del periodo di offerta. Al terminare il periodo di offerta fissato da KONTACT VO S.L., nel caso in cui non si sia accordato altro, finalizzerà il periodo della vincolazione alla scadenza del giorno dell\'asta e si realizzerà il contratto di compravendita tra il venditore e il miglior offerente conformemente al diritto spagnolo. Entrambe le parti contraenti hanno l\'obbligo di chiudere l\'affare. Il venditore si impegna a consegnare il veicolo nello stato descritto al miglior offerente. Il miglior offerente ha il dovere di ritirare il veicolo e pagarlo. Lo stesso si applicherà quando un contratto si sia realizzato attraverso il centro di attenzione al cliente o mediato in qualche altra forma da KONTACT VO S.L. Nel caso in cui un veicolo si sia venduto attraverso www.KONTACTVO.es, tanto il compratore quanto il venditore si impegnano a stampare e utilizzare il contratto direttamente da www.autorola.es. La nota di acquisto sarà anche inviata per posta elettronica o fax. Deve verificarsi che la nota di acquisto o contratto che invii KONTACT VO S.L. sia corretta.',
  'terms.introduction.p10': '1.5.2 Esclusività nella mediazione di KONTACT VO S.L. Una volta finalizzata la vendita o l\'asta e conosciuti i dati di contatto della controparte, l\'utente si impegna a rispettare la figura di KONTACT VO S.L. come intermediario dell\'asta e a pagare le quantità stipulate in concetto di commissione per il suo lavoro di intermediazione. Nel caso in cui KONTACT VO S.L. venga a conoscenza che due utenti si sono messi in contatto e finalizzato la compravendita del veicolo escludendo la compagnia dall\'affare, potrà avviare le azioni legali necessarie per la reclamazione del pagamento dei servizi realizzati, potendo sollecitare reclamo per danni e pregiudizi.',
  'terms.introduction.p11': '1.5.3 Principi base per le aste online Fintanto che un veicolo si vende in un\'asta online, l\'utente solo potrà offrire agli offerenti che hanno offerto per quell\'articolo veicoli di tipo simile e merci solo in forma di offerta registrata nel sito Web di KONTACT VO S.L., non attraverso altri mezzi, come p. es. per posta elettronica (ritiro di offerenti). Questo è anche vigente trascorso il periodo dell\'offerta. Gli utenti non sono autorizzati a manipolare lo sviluppo dell\'asta online realizzando offerte mediante un altro account utente o mediante l\'intervento di un terzo. In special modo, si proibisce al venditore che durante il periodo dell\'offerta realizzi offerte per le offerte che lui stesso ha registrato. Lo stesso veicolo non può offrirsi simultaneamente in aste online che abbiano luogo allo stesso tempo. Questo non si applicherà nel caso in cui l\'utente disponga di vari veicoli e merci dello stesso tipo. Rimane proibita la realizzazione di offerte mediante metodi di elaborazione automatica di dati (p. es. i programmi conosciuti come "Sniffer").',
  'terms.introduction.p12': '1.5.4 Sviluppo dell\'asta KONTACT VO S.L. controlla l\'inizio, la fine e lo sviluppo dell\'asta. KONTACT VO S.L. si riserva il diritto di sospendere o modificare aste pianificate. KONTACT VO S.L. è autorizzata ad annullare aste senza dover dare ragioni per ciò. L\'annullamento può prodursi sia previamente che durante l\'asta. Le aste già realizzate non possono annullarsi.',
  'terms.introduction.p13': '1.6 Asta ampliata',

  'terms.delivery.title': 'Consegna e diritto di ispezione del compratore',
  'terms.delivery.subtitle1': 'Località',
  'terms.delivery.p1': '2.1.1 La consegna del veicolo avviene, nel caso in cui non sia stato concordato altro, nel momento in cui il compratore lo ritira. Il ritiro dovrà essere effettuato all\'indirizzo indicato dal venditore all\'interno dell\'area del codice postale, e che è indicato nella descrizione. Se non si indica nessun indirizzo all\'interno dell\'area del codice postale menzionato, il veicolo si ritirerà all\'indirizzo del venditore. Nel registrare il veicolo, il venditore ha la possibilità di offrire al compratore la consegna del veicolo in un altro posto, invece che questo lo ritiri all\'indirizzo del venditore. Questo luogo può essere l\'indirizzo del compratore o un altro luogo. In forma opzionale, questa clausola sostituirà il ritiro. Nonostante il venditore selezioni questa possibilità, il compratore sempre può concordare il ritiro del veicolo all\'indirizzo del venditore, se così preferisce.',
  
  'terms.delivery.subtitle2': 'Termine',
  'terms.delivery.p2': '2.2.1 La consegna deve essere effettuata entro un termine massimo di 5 giorni lavorativi dopo l\'entrata in vigore del contratto. Il venditore si impegna a far sì che il compratore ritiri il veicolo entro il termine indicato nell\'intervallo compreso tra le 9 e le 17, ora dell\'Europa Centrale. Se si dà il caso che le parti contraenti non si mettono d\'accordo sull\'ora, il compratore la fisserà dentro l\'intervallo indicato, lasciando sempre un periodo di almeno 24 ore al venditore.',
  
  'terms.delivery.subtitle3': 'Ispezione',
  'terms.delivery.p3': '2.3.1 Verificare i danni e se esistono differenze con quanto pubblicato, riportarle nella bolla di uscita. Il fornitore del veicolo non si responsabilizza della differenza di danni esteriori (lamiera e vernice) che potrebbe esserci nel veicolo una volta ritirato dalle installazioni.',
  
  'terms.delivery.subtitle4': 'Dati del veicolo',
  'terms.delivery.p4': '2.4.1 Prima di effettuare il pagamento, il compratore è autorizzato a verificare che il numero di telaio del veicolo e la targa, se del caso, coincidano con la titolarità del veicolo. Dovrà consegnarsi al compratore la titolarità originale del veicolo/certificato di immatricolazione II, il permesso di circolazione del veicolo/certificato di immatricolazione I, il documento di ispezioni generali e il documento di controllo dei gas di combustione, tutto ciò insieme al veicolo.',

  'terms.payment.title': 'Pagamento del veicolo',
  'terms.payment.subtitle1': 'Pagamento',
  'terms.payment.p1': '3.1.1 La totalità del prezzo di acquisto, a meno che non esistano condizioni di contrattazione speciali, deve essere corrisposta da parte del compratore al momento della consegna del veicolo, della certificazione di immatricolazione originale e di tutta la documentazione vincolata al veicolo. Se una delle parti contraenti sollecita una ricevuta, l\'altra parte contraente è obbligata a consegnarle una nota di accredito.',
  
  'terms.payment.subtitle2': 'Pagamenti in asta aperta',
  'terms.payment.p2': '3.2.1 Ti ricordiamo che Autorola Spagna è un mero intermediario e ti raccomandiamo di verificare lo stato del veicolo in loco prima di effettuare il pagamento. Al chiudersi la vendita, KONTACT VO metterà in contatto il venditore e il compratore per finalizzare la transazione.',

  'terms.obligations.title': 'Obblighi',
  'terms.obligations.subtitle1': 'Obblighi del venditore',
  'terms.obligations.p1': '4.1.1 Il venditore si responsabilizza di garantire che il veicolo sia disponibile, che tutti i dati indicati sul veicolo siano corretti, veri e sufficienti e che il veicolo non presenti difetti. Il venditore garantisce che è proprietario legale del veicolo e che non esistono diritti a terzi (riserva della proprietà, esecuzione giudiziale, diritto di preferenza, proibizione di alienazione o altri diritti) che limitino o impediscano la vendita del veicolo senza carichi. Questo non si applicherà quando il venditore abbia informato su questi diritti nella descrizione del veicolo e quando abbia accordato con il compratore che questi adempirà o assumerà questi diritti nel chiudere il contratto di compravendita. Prima di registrare il veicolo, il venditore dovrà assicurare che tutte le possibili obbligazioni e altri diritti riferiti al veicolo relazionati con il trasferimento di proprietà si potranno adempiere al massimo al momento della consegna. Se il veicolo si consegna con una targa provvisoria, si richiederà un\'assicurazione di responsabilità civile vigente al momento della consegna. Se il veicolo non si consegna immatricolato, al momento del trasferimento non sarà assicurato.',
  
  'terms.obligations.subtitle2': 'Obblighi del compratore',
  'terms.obligations.p2': '4.2.1 Se il compratore ottiene il veicolo con un\'immatricolazione valida, si impegna a indicare il cambio di proprietario in un periodo massimo di tre giorni successivi alla consegna. Se il compratore è stato il miglior offerente con la sua offerta in www.KONTACTVO.es secondo le regole di offerta o ha accettato l\'acquisto in altra forma, si realizzerà un contratto tra il compratore e il venditore. Il compratore ha l\'obbligo di ritirare il veicolo e rendere effettiva la somma concordata. Si rimanda alle altre disposizioni su responsabilità e obblighi stipulate nelle condizioni d\'asta.',
  
  'terms.obligations.subtitle3': 'Controversie tra il compratore e il venditore',
  'terms.obligations.p3': '4.3.1 Se è stata presentata una reclamo con il dovuto anticipo ed esiste un inadempimento/difetto del quale è responsabile l\'altra parte contraente, si effettueranno le liquidazioni retroattive o le richieste di indennizzo conformemente al diritto spagnolo. Se il compratore o venditore presenta una domanda contro l\'altra parte contraente, si fisseranno le spese di trasporto in un importo fisso. Nel caso in cui, secondo accordo delle parti contraenti, si siano prodotti più trasporti del veicolo, si aumenterà l\'importo delle spese per trasporto. Nel caso di dispute tra il compratore e il venditore che non possano risolversi immediatamente di comune accordo, si chiederà alle parti che prendano misure giudiziali. Nel caso di una controversia tra il compratore e il venditore, dovrà inviarsi immediatamente una copia del contratto insieme a una descrizione del motivo a KONTACT VO S.L. Questa si utilizzerà per fini statistici e di registro e non implicherà, in nessun caso, che KONTACT VO S.L. assuma il ruolo di parte implicata. In qualsiasi caso, il diritto di KONTACT VO S.L. a una commissione non si vedrà affetto e le parti si impegnano a soddisfarla, come si espone nella clausola 1.5.2.',

  'terms.registration.title': 'Registrazione, blocco, sospensione e terminazione',
  'terms.registration.p1': '5.1.1 Per poter fare uso di tutti i servizi di KONTACT VO S.L., deve registrarsi un "utente". Non esiste un diritto alla registrazione su KONTACT VO S.L. La registrazione è gratuita. Si effettua aprendo un account utente e presentando la dichiarazione di conformità alle condizioni commerciali generali corrispondenti. Con la registrazione si effettua un contratto tra KONTACT VO S.L. e l\'"utente" sull\'uso della piattaforma d\'asta di veicoli www.autorola.es. I dati che KONTACT VO S.L. sollecita durante la registrazione devono essere completi e corretti. Se si produce una modifica nei dati dell\'"utente" dopo la registrazione, l\'"utente" ha il dovere di comunicare detta modifica a KONTACT VO S.L. Durante la registrazione, l\'"utente" selezionerà un nome utente e una password. Il nome utente non deve trattarsi di un indirizzo di posta elettronica né un indirizzo di Internet né deve violare diritti di terzi, in particolare diritti di nome o marca. La password deve mantenersi in segreto. L\'utente si responsabilizza dei casi di uso indebito del nome utente e della password. L\'account utente non è trasferibile. KONTACT VO S.L. può bloccare in qualsiasi momento l\'account utente. Nel momento in cui si blocchi un account utente, questo utente non potrà continuare a utilizzare i siti Web di KONTACT VO S.L. e non potrà registrarsi di nuovo senza un\'autorizzazione espressa di KONTACT VO S.L. L\'utente può rescindere il contratto d\'uso in qualsiasi momento. Per la dichiarazione di rescissione è sufficiente una nota scritta o una email a servicioalcliente@autorola.es. KONTACT VO S.L. può rescindere il contratto d\'uso con un effetto immediato in qualsiasi momento senza necessità di compiere i termini.',

  'terms.fees.title': 'Tariffe',
  'terms.fees.p1': '6.1.1 La registrazione come utente su www.KONTACTVO.es è gratuita. L\'importo dei veicoli si mostra nella scheda di ognuno, con espressa menzione all\'inclusione o meno delle imposte corrispondenti (IVA, Imposta di Immatricolazione, ecc.) L\'importo della commissione si basa sulla lista di prezzi attuale. Questa si può consultare in Lista di prezzi. Le commissioni dovranno rendersi effettive nel momento di ricevere la fattura. Potranno rendersi effettive mediante un trasferimento o una domiciliazione bancaria. Se il pagamento non si può effettuare, l\'utente dovrà pagare le spese addizionali causate, nel caso in cui sia responsabile della situazione. KONTACT VO S.L. invierà all\'utente le fatture per posta o al suo indirizzo di posta elettronica. L\'utente incorrerà in mora senza ricevere altro promemoria di pagamento trascorse due settimane dopo l\'invio della fattura. Nell\'importo della fattura figura l\'IVA vigente il giorno della fatturazione. Si pagherà la commissione corrispondente al venditore nel caso in cui l\'altra parte contraente non adempia come si deve il contratto chiuso attraverso il sito Web di KONTACT VO S.L. L\'accredito dovrà sollecitarsi conforme al procedimento previsto. Il compenso con crediti di accrediti in conto ancora non ottenuti si autorizza solo per crediti pagabili e/o futuri sempre e quando questi crediti siano giuridicamente validi o indiscutibili.',

  'terms.prohibitedItems.title': 'Articoli proibiti',
  'terms.prohibitedItems.p1': '7.1.1 È proibito offrire veicoli la cui offerta, vendita o acquisto infrangano le disposizioni legali. In special modo, non dovranno descriversi né offrirsi i seguenti veicoli: veicoli la cui sollecitazione, offerta o vendita violi i diritti d\'autore.',

  'terms.principles.title': 'Principi base generali',
  'terms.principles.p1': '8.1.1 L\'utente ha l\'obbligo di rispettare la legge vigente quando utilizza il sito Web di KONTACT VO S.L. e delle prestazioni di servizio di KONTACT VO S.L. Se nella piattaforma commerciale si arriva a chiudere un contratto tra gli utenti, KONTACT VO S.L. faciliterà i dati necessari per il contatto. Se gli utenti sono imprenditori si applicherà, nei contratti celebrati tra questi utenti nel mercato che offre KONTACT VO S.L., sempre e quando non si sia accordato altro, le leggi vigenti di Spagna escludendo espressamente l\'applicazione della Convenzione delle Nazioni Unite sui Contratti di Compravendita Internazionale di Mercanzie. Se uno degli utenti che chiude il contratto è un consumatore, si applicherà il diritto del paese in cui questi ha il suo domicilio abituale. Rimane proibito a tutti gli utenti utilizzare gli indirizzi ottenuti, i dati di contatto e gli indirizzi di posta elettronica per pubblicità commerciale.',

  'terms.exemption.title': 'Esenzione',
  'terms.exemption.p1': '9.1.1 L\'utente esenta KONTACT VO S.L. da qualsiasi responsabilità rispetto a qualsiasi reclamo di altri utenti o di terzi contro KONTACT VO S.L. per la violazione dei loro diritti nelle offerte o contenuti che l\'utente ha registrato nel sito Web o per un uso inadeguato del sito Web di KONTACT VO S.L. da parte dello stesso. L\'utente si farà carico dei costi della difesa dei diritti di KONTACT VO S.L., inclusi tutti gli onorari di avvocati e procuratori così come tasse giudiziali. Ciò non si applicherà nel caso in cui la violazione del diritto non sia responsabilità dell\'utente.',

  'terms.integrity.title': 'Integrità del sistema',
  'terms.integrity.p1': '10.1.1 L\'utente non è autorizzato a utilizzare meccanismi, software né altre vie in relazione con l\'uso della pagina web di KONTACT VO S.L. che potrebbero ostacolare il funzionamento di detta pagina web. L\'utente non è autorizzato a prendere nessuna misura che possa comportare un carico sproporzionato o eccessivo nell\'infrastruttura. Rimane proibito copiare, divulgare, riprodurre o utilizzare per altro fine i contenuti del sito Web di KONTACT VO S.L. senza il consenso previo del titolare dei diritti. Questo riguarda anche le copie realizzate mediante tecniche di motori di ricerca "Robot/Crawler" (crawler) o altri meccanismi automatici. Unicamente si autorizza la riproduzione e l\'utilizzo in altri siti Web del design del sito Web di KONTACT VO S.L. e delle condizioni d\'uso generali con il consenso previo e per iscritto di KONTACT VO S.L.',
};

