/**
 * FASE 3: Script de Generación Automática de Traducciones
 * Usa IA para completar todas las traducciones faltantes
 */

import { translations } from '@/translations';
import { SUPPORTED_LANGUAGES } from '@/config/languages';
import { performTranslationAudit } from '@/utils/translation-audit';
import { supabase } from '@/integrations/supabase/client';
import type { Language } from '@/config/languages';

interface TranslationJob {
  key: string;
  sourceText: string;
  sourceLanguage: Language;
  targetLanguage: Language;
}

/**
 * Traduce un texto usando la Edge Function
 */
const translateText = async (
  text: string,
  sourceLang: Language,
  targetLang: Language
): Promise<string> => {
  try {
    const { data, error } = await supabase.functions.invoke('translate-text', {
      body: {
        text,
        sourceLang,
        targetLang
      }
    });
    
    if (error) {
      console.error(`Error traduciendo de ${sourceLang} a ${targetLang}:`, error);
      return text; // Retornar texto original en caso de error
    }
    
    return data.translatedText || text;
  } catch (error) {
    console.error(`Excepción traduciendo de ${sourceLang} a ${targetLang}:`, error);
    return text;
  }
};

/**
 * Genera trabajos de traducción basados en el audit
 */
const generateTranslationJobs = (): TranslationJob[] => {
  const audit = performTranslationAudit();
  const jobs: TranslationJob[] = [];
  const masterLang: Language = 'es';
  const masterTranslations = translations[masterLang];
  
  // Para cada idioma con traducciones faltantes
  Object.entries(audit.missingByLanguage).forEach(([lang, missingKeys]) => {
    if (lang === masterLang || missingKeys.length === 0) return;
    
    missingKeys.forEach(key => {
      const sourceText = masterTranslations[key];
      
      if (sourceText) {
        jobs.push({
          key,
          sourceText,
          sourceLanguage: masterLang,
          targetLanguage: lang as Language
        });
      }
    });
  });
  
  return jobs;
};

/**
 * Procesa un lote de trabajos de traducción
 */
const processBatch = async (
  jobs: TranslationJob[],
  batchSize: number = 10
): Promise<Map<string, Map<Language, string>>> => {
  const results = new Map<string, Map<Language, string>>();
  
  // Procesar en lotes para no saturar la API
  for (let i = 0; i < jobs.length; i += batchSize) {
    const batch = jobs.slice(i, i + batchSize);
    
    console.log(`Procesando lote ${i / batchSize + 1} de ${Math.ceil(jobs.length / batchSize)}`);
    
    // Procesar lote en paralelo
    const batchResults = await Promise.all(
      batch.map(async job => {
        const translated = await translateText(
          job.sourceText,
          job.sourceLanguage,
          job.targetLanguage
        );
        
        return { ...job, translated };
      })
    );
    
    // Guardar resultados
    batchResults.forEach(({ key, targetLanguage, translated }) => {
      if (!results.has(key)) {
        results.set(key, new Map());
      }
      results.get(key)!.set(targetLanguage, translated);
    });
    
    // Pequeña pausa entre lotes para no saturar
    if (i + batchSize < jobs.length) {
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }
  
  return results;
};

/**
 * Genera código TypeScript con las traducciones
 */
const generateTranslationCode = (
  language: Language,
  newTranslations: Map<string, string>
): string => {
  const existing = translations[language];
  const merged = { ...existing };
  
  // Agregar nuevas traducciones
  newTranslations.forEach((value, key) => {
    merged[key] = value;
  });
  
  // Ordenar por clave
  const sorted = Object.keys(merged)
    .sort()
    .reduce((acc, key) => {
      acc[key] = merged[key];
      return acc;
    }, {} as Record<string, string>);
  
  // Generar código
  let code = '// Auto-generated translations\n';
  code += '// Generated by auto-translate script\n\n';
  code += 'export default {\n';
  
  Object.entries(sorted).forEach(([key, value]) => {
    // Escapar comillas y caracteres especiales
    const escapedValue = value
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n');
    
    code += `  '${key}': '${escapedValue}',\n`;
  });
  
  code += '};\n';
  
  return code;
};

/**
 * Exporta las traducciones generadas a archivos
 */
const exportTranslations = (
  translationsByLanguage: Map<Language, Map<string, string>>
): void => {
  console.group('📝 Exportando traducciones generadas...');
  
  translationsByLanguage.forEach((translations, lang) => {
    const code = generateTranslationCode(lang, translations);
    const filename = `${lang}-generated.ts`;
    
    console.log(`Generado: src/translations/${filename}`);
    console.log(`  ${translations.size} nuevas traducciones`);
    
    // En un entorno Node.js, aquí escribiríamos los archivos
    // Por ahora, solo mostrar en consola
    if (import.meta.env.DEV) {
      console.log(`\n--- ${filename} ---`);
      console.log(code.substring(0, 500) + '...');
    }
  });
  
  console.groupEnd();
};

/**
 * Ejecuta el proceso completo de auto-traducción
 */
export const runAutoTranslation = async (): Promise<void> => {
  console.group('🤖 [Auto-Translate] Iniciando traducción automática...');
  
  try {
    // 1. Generar trabajos de traducción
    console.log('1️⃣ Analizando traducciones faltantes...');
    const jobs = generateTranslationJobs();
    console.log(`   ${jobs.length} traducciones pendientes`);
    
    if (jobs.length === 0) {
      console.log('✅ No hay traducciones pendientes. Sistema completo!');
      console.groupEnd();
      return;
    }
    
    // 2. Agrupar por idioma
    const byLanguage = new Map<Language, TranslationJob[]>();
    jobs.forEach(job => {
      if (!byLanguage.has(job.targetLanguage)) {
        byLanguage.set(job.targetLanguage, []);
      }
      byLanguage.get(job.targetLanguage)!.push(job);
    });
    
    console.log('\n2️⃣ Idiomas a procesar:');
    byLanguage.forEach((jobs, lang) => {
      console.log(`   ${lang}: ${jobs.length} traducciones`);
    });
    
    // 3. Procesar traducciones
    console.log('\n3️⃣ Procesando traducciones...');
    const results = await processBatch(jobs, 10);
    
    // 4. Organizar por idioma para exportación
    const translationsByLanguage = new Map<Language, Map<string, string>>();
    
    results.forEach((langMap, key) => {
      langMap.forEach((translation, lang) => {
        if (!translationsByLanguage.has(lang)) {
          translationsByLanguage.set(lang, new Map());
        }
        translationsByLanguage.get(lang)!.set(key, translation);
      });
    });
    
    // 5. Exportar resultados
    console.log('\n4️⃣ Exportando resultados...');
    exportTranslations(translationsByLanguage);
    
    // 6. Resumen final
    console.log('\n✅ Traducción automática completada!');
    console.log(`   Total traducido: ${jobs.length} claves`);
    console.log(`   Idiomas actualizados: ${translationsByLanguage.size}`);
    
  } catch (error) {
    console.error('❌ Error en traducción automática:', error);
    throw error;
  } finally {
    console.groupEnd();
  }
};

/**
 * Comando de consola para ejecutar traducción manual de una clave
 */
export const translateKey = async (
  key: string,
  targetLanguage: Language
): Promise<string> => {
  const masterLang: Language = 'es';
  const sourceText = translations[masterLang][key];
  
  if (!sourceText) {
    throw new Error(`Clave no encontrada en idioma maestro: ${key}`);
  }
  
  console.log(`Traduciendo "${key}" de ${masterLang} a ${targetLanguage}...`);
  const translated = await translateText(sourceText, masterLang, targetLanguage);
  console.log(`Traducción: ${translated}`);
  
  return translated;
};

// Hacer funciones disponibles en la consola del navegador
if (import.meta.env.DEV) {
  (window as any).runAutoTranslation = runAutoTranslation;
  (window as any).translateKey = translateKey;
  
  console.log('🤖 [Auto-Translate] Comandos disponibles:');
  console.log('  - runAutoTranslation(): Ejecuta traducción automática completa');
  console.log('  - translateKey(key, targetLang): Traduce una clave específica');
}
