import type { Language } from '@/config/languages';

export const preRegistrationCopy: Record<Language, {
  title: string;
  subtitle: string;
  infoBanner: string;
  submit: string;
  submitting: string;
  successTitle: string;
  successMessage: string;
  successDetail: string;
  consent: string;
  toastSuccess: string;
  toastError: string;
  minChars: string;
  backToHome: string;
  fullRegistrationTitle: string;
  fullRegistrationMessage: string;
}> = {
  es: {
    title: 'Pre-Registro',
    subtitle: 'Solicitud de acceso anticipado a KONTACT VO',
    infoBanner: 'Complete este formulario de pre-registro. En cuanto KONTACT VO inicie su actividad, nos pondremos en contacto con usted para solicitar la documentación necesaria, validarla y habilitar su cuenta.',
    submit: 'Enviar Pre-Registro',
    submitting: 'Enviando...',
    successTitle: 'Pre-registro enviado',
    successMessage: 'Hemos recibido su solicitud de pre-registro correctamente.',
    successDetail: 'En cuanto iniciemos la actividad, nos pondremos en contacto con usted para completar el proceso de registro y habilitar su cuenta.',
    consent: 'Al enviar este formulario acepta que contactemos con usted cuando el servicio esté disponible.',
    toastSuccess: 'Pre-registro enviado correctamente',
    toastError: 'Error al enviar el pre-registro. Inténtelo de nuevo.',
    minChars: 'mín. 3 caracteres',
    backToHome: 'Volver al inicio',
    fullRegistrationTitle: 'Registro Completo',
    fullRegistrationMessage: 'El formulario de registro completo estará disponible próximamente. Mientras tanto, complete el pre-registro a la izquierda para reservar su acceso.',
  },
  en: {
    title: 'Pre-Registration',
    subtitle: 'Early access request for KONTACT VO',
    infoBanner: 'Complete this pre-registration form. As soon as KONTACT VO begins operations, we will contact you to request the necessary documentation, validate it and activate your account.',
    submit: 'Submit Pre-Registration',
    submitting: 'Submitting...',
    successTitle: 'Pre-registration sent',
    successMessage: 'We have received your pre-registration request successfully.',
    successDetail: 'As soon as operations begin, we will contact you to complete the registration process and activate your account.',
    consent: 'By sending this form, you agree that we may contact you when the service becomes available.',
    toastSuccess: 'Pre-registration sent successfully',
    toastError: 'Error sending the pre-registration. Please try again.',
    minChars: 'min. 3 characters',
    backToHome: 'Back to home',
    fullRegistrationTitle: 'Full Registration',
    fullRegistrationMessage: 'The full registration form will be available soon. In the meantime, complete the pre-registration on the left to reserve your access.',
  },
  fr: {
    title: 'Pré-inscription',
    subtitle: 'Demande d’accès anticipé à KONTACT VO',
    infoBanner: 'Remplissez ce formulaire de pré-inscription. Dès que KONTACT VO démarrera son activité, nous vous contacterons pour demander la documentation nécessaire, la valider et activer votre compte.',
    submit: 'Envoyer la pré-inscription',
    submitting: 'Envoi en cours...',
    successTitle: 'Pré-inscription envoyée',
    successMessage: 'Nous avons bien reçu votre demande de pré-inscription.',
    successDetail: 'Dès le démarrage de l’activité, nous vous contacterons pour compléter le processus d’inscription et activer votre compte.',
    consent: 'En envoyant ce formulaire, vous acceptez que nous vous contactions lorsque le service sera disponible.',
    toastSuccess: 'Pré-inscription envoyée avec succès',
    toastError: 'Erreur lors de l’envoi de la pré-inscription. Veuillez réessayer.',
    minChars: 'min. 3 caractères',
    backToHome: 'Retour à l’accueil',
    fullRegistrationTitle: 'Inscription complète',
    fullRegistrationMessage: 'Le formulaire d’inscription complet sera bientôt disponible. En attendant, complétez la pré-inscription à gauche pour réserver votre accès.',
  },
  it: {
    title: 'Pre-registrazione',
    subtitle: 'Richiesta di accesso anticipato a KONTACT VO',
    infoBanner: 'Compila questo modulo di pre-registrazione. Non appena KONTACT VO inizierà la sua attività, ti contatteremo per richiedere la documentazione necessaria, validarla e attivare il tuo account.',
    submit: 'Invia pre-registrazione',
    submitting: 'Invio in corso...',
    successTitle: 'Pre-registrazione inviata',
    successMessage: 'Abbiamo ricevuto correttamente la tua richiesta di pre-registrazione.',
    successDetail: 'Non appena inizierà l’attività, ti contatteremo per completare il processo di registrazione e attivare il tuo account.',
    consent: 'Inviando questo modulo accetti che possiamo contattarti quando il servizio sarà disponibile.',
    toastSuccess: 'Pre-registrazione inviata correttamente',
    toastError: 'Errore durante l’invio della pre-registrazione. Riprova.',
    minChars: 'min. 3 caratteri',
    backToHome: 'Torna alla home',
    fullRegistrationTitle: 'Registrazione completa',
    fullRegistrationMessage: 'Il modulo di registrazione completo sarà disponibile a breve. Nel frattempo, completa la pre-registrazione a sinistra per riservare il tuo accesso.',
  },
  de: {
    title: 'Vorregistrierung',
    subtitle: 'Anfrage auf frühzeitigen Zugang zu KONTACT VO',
    infoBanner: 'Füllen Sie dieses Vorregistrierungsformular aus. Sobald KONTACT VO den Betrieb aufnimmt, werden wir Sie kontaktieren, um die erforderlichen Unterlagen anzufordern, zu prüfen und Ihr Konto zu aktivieren.',
    submit: 'Vorregistrierung senden',
    submitting: 'Wird gesendet...',
    successTitle: 'Vorregistrierung gesendet',
    successMessage: 'Wir haben Ihre Vorregistrierungsanfrage erfolgreich erhalten.',
    successDetail: 'Sobald der Betrieb startet, werden wir Sie kontaktieren, um den Registrierungsprozess abzuschließen und Ihr Konto zu aktivieren.',
    consent: 'Mit dem Absenden dieses Formulars stimmen Sie zu, dass wir Sie kontaktieren dürfen, sobald der Dienst verfügbar ist.',
    toastSuccess: 'Vorregistrierung erfolgreich gesendet',
    toastError: 'Fehler beim Senden der Vorregistrierung. Bitte versuchen Sie es erneut.',
    minChars: 'mind. 3 Zeichen',
    backToHome: 'Zurück zur Startseite',
    fullRegistrationTitle: 'Vollständige Registrierung',
    fullRegistrationMessage: 'Das vollständige Registrierungsformular wird in Kürze verfügbar sein. Füllen Sie in der Zwischenzeit die Vorregistrierung links aus, um Ihren Zugang zu reservieren.',
  },
  nl: {
    title: 'Voorregistratie',
    subtitle: 'Aanvraag voor vroege toegang tot KONTACT VO',
    infoBanner: 'Vul dit voorregistratieformulier in. Zodra KONTACT VO van start gaat, nemen wij contact met u op om de benodigde documentatie op te vragen, te valideren en uw account te activeren.',
    submit: 'Voorregistratie verzenden',
    submitting: 'Bezig met verzenden...',
    successTitle: 'Voorregistratie verzonden',
    successMessage: 'Wij hebben uw voorregistratieverzoek succesvol ontvangen.',
    successDetail: 'Zodra de activiteit start, nemen wij contact met u op om het registratieproces af te ronden en uw account te activeren.',
    consent: 'Door dit formulier te verzenden, gaat u ermee akkoord dat wij contact met u opnemen wanneer de dienst beschikbaar is.',
    toastSuccess: 'Voorregistratie succesvol verzonden',
    toastError: 'Fout bij het verzenden van de voorregistratie. Probeer het opnieuw.',
    minChars: 'min. 3 tekens',
    backToHome: 'Terug naar home',
    fullRegistrationTitle: 'Volledige registratie',
    fullRegistrationMessage: 'Het volledige registratieformulier zal binnenkort beschikbaar zijn. Vul intussen links de voorregistratie in om uw toegang te reserveren.',
  },
  pt: {
    title: 'Pré-registo',
    subtitle: 'Pedido de acesso antecipado ao KONTACT VO',
    infoBanner: 'Preencha este formulário de pré-registo. Assim que o KONTACT VO iniciar a sua atividade, entraremos em contacto consigo para solicitar a documentação necessária, validá-la e ativar a sua conta.',
    submit: 'Enviar pré-registo',
    submitting: 'A enviar...',
    successTitle: 'Pré-registo enviado',
    successMessage: 'Recebemos o seu pedido de pré-registo com sucesso.',
    successDetail: 'Assim que a atividade começar, entraremos em contacto consigo para completar o processo de registo e ativar a sua conta.',
    consent: 'Ao enviar este formulário, aceita que o contactemos quando o serviço estiver disponível.',
    toastSuccess: 'Pré-registo enviado com sucesso',
    toastError: 'Erro ao enviar o pré-registo. Tente novamente.',
    minChars: 'mín. 3 caracteres',
    backToHome: 'Voltar ao início',
    fullRegistrationTitle: 'Registo completo',
    fullRegistrationMessage: 'O formulário de registo completo estará disponível em breve. Entretanto, complete o pré-registo à esquerda para reservar o seu acesso.',
  },
  pl: {
    title: 'Wstępna rejestracja',
    subtitle: 'Wniosek o wcześniejszy dostęp do KONTACT VO',
    infoBanner: 'Wypełnij ten formularz wstępnej rejestracji. Gdy KONTACT VO rozpocznie działalność, skontaktujemy się z Tobą, aby poprosić o niezbędne dokumenty, zweryfikować je i aktywować Twoje konto.',
    submit: 'Wyślij wstępną rejestrację',
    submitting: 'Wysyłanie...',
    successTitle: 'Wstępna rejestracja wysłana',
    successMessage: 'Pomyślnie otrzymaliśmy Twoje zgłoszenie wstępnej rejestracji.',
    successDetail: 'Gdy działalność się rozpocznie, skontaktujemy się z Tobą, aby dokończyć proces rejestracji i aktywować Twoje konto.',
    consent: 'Wysyłając ten formularz, zgadzasz się, abyśmy skontaktowali się z Tobą, gdy usługa będzie dostępna.',
    toastSuccess: 'Wstępna rejestracja została wysłana pomyślnie',
    toastError: 'Błąd podczas wysyłania wstępnej rejestracji. Spróbuj ponownie.',
    minChars: 'min. 3 znaki',
    backToHome: 'Powrót do strony głównej',
    fullRegistrationTitle: 'Pełna rejestracja',
    fullRegistrationMessage: 'Pełny formularz rejestracyjny będzie wkrótce dostępny. W międzyczasie wypełnij wstępną rejestrację po lewej stronie, aby zarezerwować dostęp.',
  },
  dk: {
    title: 'Forhåndsregistrering',
    subtitle: 'Anmodning om tidlig adgang til KONTACT VO',
    infoBanner: 'Udfyld denne forhåndsregistreringsformular. Så snart KONTACT VO starter sin aktivitet, kontakter vi dig for at anmode om den nødvendige dokumentation, validere den og aktivere din konto.',
    submit: 'Send forhåndsregistrering',
    submitting: 'Sender...',
    successTitle: 'Forhåndsregistrering sendt',
    successMessage: 'Vi har modtaget din forhåndsregistrering.',
    successDetail: 'Så snart aktiviteten starter, kontakter vi dig for at fuldføre registreringsprocessen og aktivere din konto.',
    consent: 'Ved at sende denne formular accepterer du, at vi kontakter dig, når tjenesten bliver tilgængelig.',
    toastSuccess: 'Forhåndsregistrering sendt',
    toastError: 'Fejl ved afsendelse af forhåndsregistreringen. Prøv igen.',
    minChars: 'min. 3 tegn',
    backToHome: 'Tilbage til forsiden',
    fullRegistrationTitle: 'Fuld registrering',
    fullRegistrationMessage: 'Den fulde registreringsformular vil snart være tilgængelig. Udfyld i mellemtiden forhåndsregistreringen til venstre for at reservere din adgang.',
  },
};
