
export default {
  // Términos y condiciones
  'terms.introduction.title': 'Introducción',
  'terms.introduction.subtitle1': 'Derecho de revocación y ámbito de legal',
  'terms.introduction.p1': '1.1.1 KONTACT VO, S.L., con CIF B00000000 y domicilio a efecto de notificaciones en BBBBBBBBBBBBBBBBBB, inscrita en el Registro Mercantil de Madrid (Tomo: 00000 Folio: 000Sección: 0Hoja: M-00000) es responsable de los contenidos y operaciones de KONTACTVO.es El dominio pertenece a terceras personas. KONTACT VO S.L. actúa exclusivamente como intermediario, poniendo a disposición de los profesionales y particulares un portal y una plataforma comercial de vehículos www.Kontactvo.es. Kontact VO, S.L. no figura en ningún caso como parte compradora o vendedora en las compraventas realizadas a través de dicha página web.',
  'terms.introduction.p2': '1.1.2 Ámbito legal KONTACTVO S.L. ofrece una plataforma comercial en Internet. Las condiciones que se describen a continuación afectan al uso de las aplicaciones de la página web de KONTACTVO S.L. Estas condiciones se encuentran en lengua española. Las partes contratantes han de ser exclusivamente personas físicas mayores de 18 años o bien personas jurídicas, con capacidad legal para suscribir contratos vinculantes. Las presentes condiciones, se someterán expresamente y con renuncia a cualquier otra jurisdicción a la competencia de los Juzgados y Tribunales de la cuidad de Sabadell. Las presentes condiciones se regirán por lo previsto en la normativa española. En el caso de que alguna de las presentes condiciones sea o fuese declarada ineficaz, nula o irrealizable, ello no afectará a la eficacia de las restantes, las cuales subsistirán plenamente válidas y eficaces. Tal condición en cuestión se entenderá, sin que para ello sea preciso cualesquiera ulteriores actuaciones de las partes en cuanto a forma, contenido, tiempo y medida, sustituida por una disposición que sea válida, eficaz y realizable y que se acerque al máximo desde cualquier perspectiva, y en especial la económica, a la finalidad y espíritu de la disposición objeto de subsanación.',
  
  'terms.introduction.subtitle2': 'Categorías de usuarios y derechos de uso',
  'terms.introduction.p3': '1.2.1 Es requisito para comprar o vender a través de www.KONTACTVO.es registrarse debidamente. Los usuarios no deben registrarse con varios nombres a la vez ni realizar acciones con una identidad falsa. No existe un derecho al registro y uso de la página web. KONTACT VO S.L. no será responsable de los fallos que pudieran producirse en las comunicaciones, incluido el borrado, transmisión incompleta o retrasos en la remisión, no comprometiéndose tampoco a que la red de transmisión esté operativa en todo momento. Tampoco será responsable en caso de que un tercero, quebrantando las medidas de seguridad establecidas por KONTACT VO S.L. acceda a los mensajes, introduzca virus informáticos o produzca cualquier otro tipo de daño en el sistema informático que pueda repercutir en sus usuarios. KONTACT VO S.L. no controla ni garantiza la ausencia de virus informáticos en los servicios prestados por terceros a través de la página web que puedan producir alteraciones en su sistema informático (software y hardware) o en los documentos y ficheros electrónicos almacenados en su sistema informático. KONTACT VO S.L. se reserva el derecho de modificar las aplicaciones de su página web, bloquear o borrar los usuarios y/o las ofertas en cualquier momento y sin necesidad de indicar los motivos.',
  'terms.introduction.p4': '1.2.2 Sólo el alta de un usuario Empresa supondrá un alta diferente donde estas Condiciones Generales de Subasta serán tenidas en cuenta como condiciones generales, siendo de aplicación a estos usuarios Empresa otras condiciones especiales, que les serán remitida por correo electrónico en el menor plazo de tiempo posible desde que se efectúe el alta de usuario en esta categoría.',
  'terms.introduction.p5': '1.2.3 Las altas de usuario en cualquier categoría supondrán la aceptación total de las presentes Condiciones Generales de Subasta. KONTACT VO S.L. se compromete al envío de instrucciones precisas sobre el proceso de participación en la subasta en el momento en que un usuario se de alta en la página web. Este envío se efectuará por correo electrónico de manera que este dato deberá ser cierto y correcto en el momento del alta. Asimismo, KONTACT VO S.L. facilitará al usuario un panel del control que será accesible mediante usuario y contraseña, previamente aportados por el usuario, donde éste podrá tener acceso a los datos completos de su perfil y donde podrá actualizar sus datos y preferencias. Posteriormente, KONTACT VO S.L. y en el momento en que la subasta haya finalizado, enviará a los usuarios los datos de la contraparte para que pueda comunicarse con ella. Las comunicaciones de KONTACT VO S.L. finalizarán con el envío de la factura por los servicios prestados.',
  
  'terms.introduction.subtitle3': 'Registro de vehículos',
  'terms.introduction.p6': '1.3.1 Antigüedad de los vehículos: Todos los usuarios registrados pueden dar de alta vehículos que hayan sido matriculados por primera con posterioridad al año 1983.',
  'terms.introduction.p7': '1.3.2 Descripción: El vendedor debe describir su artículo y todas las condiciones de venta en la página de inserción de artículos de la página web. Los anuncios podrán incluir textos descriptivos, gráficos, fotografías y otros contenidos pertinentes para la venta. Todos los artículos insertados deberán ser incluidos en la categoría apropiada. Se deben indicar todas las características y cualidades básicas relevantes para la decisión de compra, así como defectos, que pueden reducir el valor de la mercancía ofrecida. Además, se debe informar con detalle al usuario sobre la propiedad del vehículo ofrecido y las condiciones de pago y entrega. Los profesionales que anuncian vehículos a consumidores tienen la obligación de informar sobre las garantías legales. La descripción y las imágenes utilizadas no deben vulnerar los derechos de autor de terceros y deben hacer referencia exclusivamente a la oferta (imágenes originales). Las descripciones, los dibujos y las imágenes no deben contener publicidad para otros artículos que no sean los que se anuncian, en especial no deben remitir a enlaces a la propia página web o incluir datos sobre números de teléfono, etc.',
  
  'terms.introduction.subtitle4': 'Responsabilidad',
  'terms.introduction.p8': '1.4.1 KONTACT VO S.L. declara que únicamente pone a disposición un portal de comercialización para compradores y vendedores. Los posibles contratos de compraventa se llevan a cabo exclusivamente entre el vendedor y el comprador. KONTACT VO S.L. no es responsable de la veracidad o exactitud de los datos, características y condiciones contenidas en las ofertas, promociones y publicidad contenida en la información que se facilita. Del mismo modo, son los propietarios o comercializadores de los vehículos los únicos responsables de las operaciones comerciales que en relación con los mismos concluyan. KONTACT VO S.L. no se responsabiliza de un posible lucro cesante. KONTACT VO S.L. tampoco se responsabiliza de los problemas técnicos ni de los errores del programa. En las páginas Web de KONTACT VO S.L. pueden encontrarse enlaces a otras páginas de Internet. KONTACT VO S.L. no ofrece ni comercializa los productos y servicios disponibles en los sitios enlazados por lo que no asume responsabilidad de ningún tipo en relación con los contenidos e informaciones, ni con las operaciones, a los que se pueda acceder o que se puedan realizar, según sea el caso, a través de este portal y en general de las consecuencias que se deriven del acceso por los usuarios a los mismo, respecto de los cuales declina toda responsabilidad. Dichos servicios son prestados por terceros que actúan en todo caso en su propio nombre y por su cuenta propia, tanto en relación con la oferta como con la contratación de los servicios de que se trate, y asumen plenamente su gestión y explotación, con independencia de la forma en que los usuarios hayan podido acceder a ellos.',
  
  'terms.introduction.subtitle5': 'Cierre del contrato, reglas de subasta, plazo de la vinculación',
  'terms.introduction.p9': '1.5.1 Con el registro de un vehículo en el sitio web de KONTACT VO S.L., el vendedor realiza una oferta vinculante para la venta del vehículo bien por el precio fijo ofertado o al postor que en el transcurso del período de oferta realice la puja más alta. El vendedor se declara completamente de acuerdo a vender su vehículo ofertado, en caso de ausencia de ofertas más elevadas, al postor que haya pujado por un importe que corresponda al precio mínimo. Si dos postores realizan la misma oferta, se considerará la primera oferta realizada como oferta más alta. El postor está sujeto a su puja hasta que una oferta más alta la supere. Si no se sube la puja, ésta prevalece, a no ser que se hayan acordado unas reglas especiales, hasta las 18.00 horas del día en el que la oferta caduque. Las ofertas ya realizadas no pueden reducirse ni anularse. KONTACT VO S.L. registra y guarda todas las ofertas realizadas. Si surgen dudas sobre las ofertas, KONTACT VO S.L. las aclarará de forma vinculante para las partes contratantes. Una oferta no es vinculante si el postor al realizar la oferta ha cometido una falta de ortografía evidente al realizar la oferta que podría conducir a errores o si un tercero ha realizado la oferta efectuando un uso indebido del nombre del usuario o de la contraseña del postor, o si el postor no es capaz de determinar la identidad del vendedor en el plazo de 10 días laborables tras finalizar el período de oferta. Al finalizar el período de oferta fijado por KONTACT VO S.L., en el caso de que no se haya acordado otra cosa, finalizará el plazo de la vinculación al vencer el día de la subasta y se llevará a cabo el contrato de compraventa entre el vendedor y el mejor postor conforme al derecho español. Ambas partes contratantes tienen la obligación de cerrar el negocio. El vendedor se compromete a entregar el vehículo en el estado descrito al mejor postor. El mejor postor tiene el deber de recoger el vehículo y pagarlo. Lo mismo se aplicará cuando un contrato se haya realizado a través del centro de atención al cliente o mediado de alguna otra forma por KONTACT VO S.L. En el caso de que un vehículo se haya vendido a través de www.KONTACTVO.es, tanto el comprador como el vendedor se comprometen a imprimir y utilizar el contrato directamente de www.autorola.es. La nota de compra también se enviará por correo electrónico o fax. Debe comprobarse que la nota de compra o contrato que envíe KONTACT VO S.L. sea correcta.',
  'terms.introduction.p10': '1.5.2 Exclusividad en la mediación de KONTACT VO S.L. Una vez finalizada la venta o la subasta y conocidos los datos de contacto de la contraparte, el usuario se compromete a respetar la figura de KONTACT VO S.L. como intermediario de la subasta y a pagar las cantidades estipuladas en concepto de comisión por su labor de intermediación. En caso de que KONTACT VO S.L. tenga conocimiento de que dos usuarios se han puesto en contacto y finalizado la compraventa del vehículo excluyendo a la compañía del negocio, podrá incoar las acciones legales necesarias para la reclamación del pago de los servicios realizados, pudiendo solicitar reclamación por daños y perjuicios.',
  'terms.introduction.p11': '1.5.3 Principios básicos para las subastas online En tanto que un vehículo se venda en una subasta online, el usuario sólo podrá ofrecer a los postores que han pujado por ese artículo vehículos de tipo similar y mercancías sólo en forma de oferta registrada en el sitio Web de KONTACT VO S.L., no a través de otros medios, como p. ej. por correo electrónico (retirada de postores). Esto también es vigente transcurrido el período de la oferta. Los usuarios no están autorizados a manipular el desarrollo de la subasta online realizando pujas mediante otra cuenta de usuario o mediante la intervención de un tercero. En especial, se le prohíbe al vendedor que durante el período de la oferta realice pujas por las ofertas que él mismo ha registrado. El mismo vehículo no puede ofrecerse simultáneamente en subastas online que tengan lugar al mismo tiempo. Esto no se aplicará en el caso de que el usuario disponga de varios vehículos y mercancías del mismo tipo. Queda prohibida la realización de ofertas mediante métodos de procesamiento automático de datos (p. ej. los programas conocidos como "Sniffer").',
  'terms.introduction.p12': '1.5.4 Desarrollo de la subasta KONTACT VO S.L. controla el inicio, el final y el desarrollo de la subasta. KONTACT VO S.L. se reserva el derecho de suspender o modificar subastas planificadas. KONTACT VO S.L. está autorizada a anular subastas sin tener que dar razones por ello. La anulación puede producirse tanto previamente como durante la subasta. Las subastas ya realizadas no pueden anularse.',
  'terms.introduction.p13': '1.6 Subasta ampliada',

  'terms.delivery.title': 'Entrega y derecho de inspección del comprador',
  'terms.delivery.subtitle1': 'Localidad',
  'terms.delivery.p1': '2.1.1 La entrega del vehículo tiene lugar, en el caso de que no se haya acordado otro extremo, en el momento en el que el comprador lo recoge. La recogida deberá realizarse en la dirección que indique el vendedor dentro del área del código postal, y que se indica en la descripción. Si no se indica ninguna dirección dentro del área del código postal mencionado, el vehículo se recogerá en la dirección del vendedor. Al dar de alta el vehículo, el vendedor tiene la posibilidad de ofrecer al comprador la entrega del vehículo en otro sitio, en vez de que éste lo recoja en la dirección del vendedor. Este lugar puede ser la dirección del comprador u otro lugar. De forma opcional, esta cláusula sustituirá la recogida. A pesar de que el vendedor seleccione esta posibilidad, el comprador siempre puede acordar la recogida del vehículo en la dirección del vendedor, si así lo prefiere.',
  
  'terms.delivery.subtitle2': 'Plazo',
  'terms.delivery.p2': '2.2.1 La entrega deberá realizarse como máximo en un plazo de 5 días laborables tras hacerse efectivo el contrato. El vendedor se compromete a que el comprador recoja el vehículo dentro del plazo indicado en el intervalo comprendido entre las 9 y 17 horas, hora de Europa Central. Si se da el caso de que las partes contratantes no se ponen de acuerdo sobre la hora, el comprador la fijará dentro del intervalo indicado, dejando siempre un plazo como mínimo de 24 horas al vendedor.',
  
  'terms.delivery.subtitle3': 'Inspección',
  'terms.delivery.p3': '2.3.1 Verifique los daños y si existen diferencias con lo publicado, refléjelos en el albarán de salida. el proveedor del vehículo no se responsabilizan de la diferencia de daños exteriores (chapa y pintura) que pudiera haber en el vehículo una vez retirado de las instalaciones.',
  
  'terms.delivery.subtitle4': 'Datos del vehículo',
  'terms.delivery.p4': '2.4.1 Antes de efectuar el pago, el comprador está autorizado a comprobar que el número de bastidor del vehículo y la matrícula, en su caso, coincidan con la titularidad del vehículo. Deberá entregarse al comprador la titularidad original del vehículo/certificado de matriculación II, el permiso de circulación del vehículo/certificado de matriculación I, el documento de inspecciones generales y el documento de control de los gases de combustión, todo ello junto con el vehículo.',

  'terms.payment.title': 'Pago del vehículo',
  'terms.payment.subtitle1': 'Pago',
  'terms.payment.p1': '3.1.1 La totalidad del precio de compra, a no ser que existan condiciones de contratación especiales, debe hacerse efectiva por parte del comprador en el momento de la entrega del vehículo, de la certificación de matriculación original y toda la documentación vinculada al vehículo. Si una de las partes contratantes solicita un recibo, la otra parte contratante está obligada a entregarle una nota de abono.',
  
  'terms.payment.subtitle2': 'Pagos en subasta abierta',
  'terms.payment.p2': '3.2.1 Le recordamos que Autorola España es un mero intermediario y le recomendamos que verifique el estado del vehículo in situ antes de realizar el pago. Al cerrarse la venta, KONTACT VO pondrá en contacto al vendedor y al comprador para finalizar la transacción.',

  'terms.obligations.title': 'Obligaciones',
  'terms.obligations.subtitle1': 'Obligaciones del vendedor',
  'terms.obligations.p1': '4.1.1 El vendedor se responsabiliza de que el vehículo esté disponible, que todos los datos indicados sobre el vehículo sean correctos, verdaderos y suficientes y que el vehículo no presente defectos. El vendedor garantiza que es propietario legal del vehículo y que no existen derechos a terceros (reserva de la propiedad, ejecución judicial, derecho de preferencia, prohibición de enajenación u otros derechos) que limiten o impidan la venta del vehículo sin cargas. Esto no se aplicará cuando el vendedor haya informado sobre estos derechos en la descripción del vehículo y cuando haya acordado con el comprador que éste cumplirá o asumirá estos derechos al cerrar el contrato de compraventa. Antes de dar de alta el vehículo, el vendedor deberá asegurar que todas las posibles obligaciones y demás derechos referentes al vehículo relacionados con el traspaso de propiedad se podrán cumplir como máximo en el momento de la entrega. Si el vehículo se entrega con una matrícula provisional, se requerirá un seguro de responsabilidad civil vigente en el momento de la entrega. Si el vehículo no se entrega matriculado, en el momento del traspaso no estará asegurado.',
  
  'terms.obligations.subtitle2': 'Obligaciones del comprador',
  'terms.obligations.p2': '4.2.1 Si el comprador obtiene el vehículo con una matriculación válida, se compromete a indicar el cambio de propietario en un plazo máximo de tres días posteriores a la entrega. Si el comprador ha sido el mejor postor con su oferta en www.KONTACTVO.es según las reglas de puja o ha aceptado la compra de otra forma, se llevará a cabo un contrato entre el comprador y el vendedor. El comprador tiene la obligación de recoger el vehículo y hacer efectiva la suma acordada. Se remite a las demás disposiciones sobre responsabilidades y obligaciones estipuladas en las condiciones de subasta.',
  
  'terms.obligations.subtitle3': 'Litigios entre el comprador y el vendedor',
  'terms.obligations.p3': '4.3.1 Si se ha presentado una reclamación con la debida antelación y existe un incumplimiento/defecto del cual es responsable la otra parte contratante, se llevarán a cabo las liquidaciones retroactivas o demandas de indemnización conforme al derecho español. Si el comprador o vendedor presenta una demanda contra la otra parte contratante, se fijarán los gastos de transporte en un importe fijo. En el caso de que, según acuerdo de las partes contratantes, se hayan producido más transportes del vehículo, se aumentará el importe de los gastos por transporte. En el caso de disputas entre el comprador y el vendedor que no puedan resolverse inmediatamente de común acuerdo, se pedirá a las partes que tomen medidas judiciales. En el caso de un litigio entre el comprador y el vendedor, deberá enviarse de inmediato una copia del contrato junto con una descripción del motivo a KONTACT VO S.L. Ésta se utilizará para fines estadísticos y de registro y no implicará, en ningún caso, que KONTACT VO S.L. asuma el papel de parte implicada. En cualquier caso, el derecho de KONTACT VO S.L. a una comisión no se verá afectado y las partes se comprometen a satisfacerla, tal y como se expone en la cláusula 1.5.2.',

  'terms.registration.title': 'Registro, bloqueo, suspensión y terminación',
  'terms.registration.p1': '5.1.1 Para poder hacer uso de todos los servicios de KONTACT VO S.L., debe registrarse un "usuario". No existe un derecho al registro en KONTACT VO S.L. El registro es gratuito. Se lleva a cabo abriendo una cuenta de usuario y presentando la declaración de conformidad a las condiciones comerciales generales correspondientes. Con el registro se lleva a cabo un contrato entre KONTACT VO S.L. y el "usuario" sobre el uso de la plataforma de subasta de vehículos www.autorola.es. Los datos que KONTACT VO S.L. solicita durante el registro deben ser completos y correctos. Si se produce una modificación en los datos del "usuario" después del registro, el „usuario" tiene el deber de comunicar dicha modificación a KONTACT VO S.L. Durante el registro, el "usuario" seleccionará un nombre de usuario y una contraseña. El nombre de usuario no debe tratarse de una dirección de correo electrónico ni una dirección de Internet ni debe violar derechos de terceros, en particular derechos de nombre o marca. La contraseña debe mantenerse en secreto. El usuario se responsabiliza de los casos de uso indebido del nombre de usuario y de la contraseña. La cuenta de usuario no es transferible. KONTACT VO S.L. puede bloquear en cualquier momento la cuenta de usuario. En el momento en que se bloquee una cuenta de usuario, este usuario no podrá seguir utilizando los sitios Web de KONTACT VO S.L. y no podrá registrarse de nuevo sin una autorización expresa de KONTACT VO S.L. El usuario puede rescindir el contrato de uso en cualquier momento. Para la declaración de rescisión es suficiente una nota escrita o un correo electrónico a servicioalcliente@autorola.es. KONTACT VO S.L. puede rescindir el contrato de uso con un efecto inmediato en cualquier momento sin necesidad de cumplir los plazos.',

  'terms.fees.title': 'Tarifas',
  'terms.fees.p1': '6.1.1 El registro como usuario en www.KONTACTVO.es gratuito. El importe de los vehículos se muestra en la ficha de cada uno, con expresa mención a la inclusión o no de los impuestos correspondientes (IVA, Impuesto de Matriculación, etc.) El importe de la comisión se basa en la lista de precios actual. Ésta se puede consultar en Lista de precios. Las comisiones deberán hacerse efectivas en el momento de recibir la factura. Podrán hacerse efectivas mediante una transferencia o una domiciliación bancaria. Si el pago no se puede efectuar, el usuario deberá abonar los gastos adicionales ocasionados, en el caso de que sea responsable de la situación. KONTACT VO S.L. enviará al usuario las facturas por correo postal o a su dirección de correo electrónico. El usuario incurrirá en demora sin recibir otro recordatorio de pago transcurridas dos semanas tras el envío de la factura. En el importe de la factura figura el IVA vigente el día de la facturación. Se abonará la comisión correspondiente al vendedor en el caso de que la otra parte contratante no cumpla como es debido el contrato cerrado a través del sitio Web de KONTACT VO S.L. El abono deberá solicitarse conforme al procedimiento previsto. La compensación con créditos de abonos en cuenta todavía no otorgados sólo se autoriza para créditos pagaderos y/o futuros siempre y cuando estos créditos sean jurídicamente válidos o indiscutibles.',

  'terms.prohibitedItems.title': 'Artículos prohibidos',
  'terms.prohibitedItems.p1': '7.1.1 Está prohibido ofrecer vehículos cuya oferta, venta o adquisición infrinjan las disposiciones legales. En especial, no deberán describirse ni ofrecerse los siguientes vehículos: vehículos cuya solicitud, oferta o venta viole los derechos de autor.',

  'terms.principles.title': 'Principios básicos generales',
  'terms.principles.p1': '8.1.1 El usuario tiene la obligación de cumplir la ley vigente al hacer uso del sitio Web de KONTACT VO S.L. y de las prestaciones de servicio de KONTACT VO S.L. Si en la plataforma comercial se llega a cerrar un contrato entre los usuarios, KONTACT VO S.L. facilitará los datos necesarios para el contacto. Si los usuarios son empresarios se aplicará, en los contratos celebrados entre estos usuarios en el mercado que ofrece KONTACT VO S.L., siempre y cuando no se haya acordado otra cosa, las leyes vigentes de España excluyendo expresamente la aplicación de la Convención de las Naciones Unidas sobre los Contratos de Compraventa Internacional de Mercaderías. Si uno de los usuarios que cierra el contrato es un consumidor, se aplicará el derecho del país en el que éste tiene su domicilio habitual. Queda prohibido a todos los usuarios utilizar las direcciones obtenidas, los datos de contacto y las direcciones de correo electrónico para publicidad comercial.',

  'terms.exemption.title': 'Exención',
  'terms.exemption.p1': '9.1.1 El usuario exime a KONTACT VO S.L. de cualquier responsabilidad con respecto a cualquier reclamación de otros usuarios o terceros contra KONTACT VO S.L. por la violación de sus derechos en las ofertas o contenidos que el usuario ha registrado en el sitio Web o por un uso inadecuado del sitio Web de KONTACT VO S.L. por parte del mismo. El usuario se hará cargo de los costes de la defensa de los derechos de KONTACT VO S.L., incluidos todos los honorarios de abogados y procuradores así como tasas judiciales. Ello no se aplicará en el caso de que la violación del derecho no sea responsabilidad del usuario.',

  'terms.integrity.title': 'Integridad del sistema',
  'terms.integrity.p1': '10.1.1 El usuario no está autorizado a utilizar mecanismos, software ni otras rutas en relación con el uso de la página web de KONTACT VO S.L. que pudieran entorpecer el funcionamiento de dicha página web. El usuario no está autorizado a tomar ninguna medida que pueda entrañar una carga desproporcionada o excesiva en la infraestructura. Queda prohibido copiar, divulgar, reproducir o utilizar para otro fin los contenidos del sitio Web de KONTACT VO S.L. sin el consentimiento previo del titular de los derechos. Esto también afecta a las copias realizadas mediante técnicas de motores de búsqueda "Robot/Crawler" (rastreadores) u otros mecanismos automáticos. Únicamente se autoriza la reproducción y la utilización en otros sitios Web del diseño del sitio Web de KONTACT VO S.L. y de las condiciones de uso generales con el consentimiento previo y por escrito de KONTACT VO S.L.',
};

