
export default {
  // Termes et conditions
  'terms.introduction.title': 'Introduction',
  'terms.introduction.subtitle1': 'Droit de rétractation et cadre juridique',
  'terms.introduction.p1': '1.1.1 KONTACT VO, S.L., avec CIF B00000000 et adresse pour notifications à BBBBBBBBBBBBBBBBBB, inscrite au Registre du Commerce de Madrid (Tome : 00000 Feuille : 000Section : 0Page : M-00000) est responsable des contenus et opérations de KONTACTVO.es Le domaine appartient à des tiers. KONTACT VO S.L. agit exclusivement comme intermédiaire, en mettant à la disposition des professionnels et des particuliers un portail et une plateforme commerciale de véhicules www.Kontactvo.es. Kontact VO, S.L. n\'apparaît en aucun cas comme partie acheteuse ou vendeuse dans les ventes réalisées à travers ledit site web.',
  'terms.introduction.p2': '1.1.2 Cadre juridique KONTACTVO S.L. offre une plateforme commerciale sur Internet. Les conditions décrites ci-dessous affectent l\'utilisation des applications du site web de KONTACTVO S.L. Ces conditions sont en langue espagnole. Les parties contractantes doivent être exclusivement des personnes physiques majeures ou des personnes juridiques, avec capacité légale pour souscrire des contrats contraignants. Les présentes conditions seront expressément soumises et avec renonciation à toute autre juridiction à la compétence des Tribunaux de la ville de Sabadell. Les présentes conditions seront régies par les dispositions de la réglementation espagnole. Dans le cas où l\'une des présentes conditions serait ou serait déclarée inefficace, nulle ou irréalisable, cela n\'affectera pas l\'efficacité des autres, qui subsisteront pleinement valides et efficaces. Une telle condition en question sera comprise, sans qu\'il soit nécessaire pour cela d\'ultérieures actions des parties en termes de forme, contenu, temps et mesure, remplacée par une disposition qui soit valide, efficace et réalisable et qui se rapproche au maximum de toute perspective, et en particulier l\'économique, à la finalité et à l\'esprit de la disposition objet de correction.',
  
  'terms.introduction.subtitle2': 'Catégories d\'utilisateurs et droits d\'utilisation',
  'terms.introduction.p3': '1.2.1 C\'est une exigence pour acheter ou vendre via www.KONTACTVO.es de s\'enregistrer dûment. Les utilisateurs ne doivent pas s\'inscrire sous plusieurs noms à la fois ni effectuer des actions sous une fausse identité. Il n\'existe pas de droit à l\'inscription et à l\'utilisation du site web. KONTACT VO S.L. ne sera pas responsable des défaillances qui pourraient se produire dans les communications, y compris la suppression, la transmission incomplète ou les retards dans l\'envoi, ne s\'engageant pas non plus à ce que le réseau de transmission soit opérationnel à tout moment. Il ne sera pas non plus responsable au cas où un tiers, en enfreignant les mesures de sécurité établies par KONTACT VO S.L., accéderait aux messages, introduirait des virus informatiques ou produirait tout autre type de dommage au système informatique qui pourrait avoir des répercussions sur ses utilisateurs. KONTACT VO S.L. ne contrôle ni ne garantit l\'absence de virus informatiques dans les services fournis par des tiers à travers le site web qui peuvent produire des altérations dans votre système informatique (logiciels et matériels) ou dans les documents et fichiers électroniques stockés dans votre système informatique. KONTACT VO S.L. se réserve le droit de modifier les applications de son site web, bloquer ou supprimer les utilisateurs et/ou les offres à tout moment et sans nécessité d\'indiquer les motifs.',
  'terms.introduction.p4': '1.2.2 Seule l\'inscription d\'un utilisateur Entreprise supposera une inscription différente où ces Conditions Générales d\'Enchères seront prises en compte comme conditions générales, d\'autres conditions spéciales étant applicables à ces utilisateurs Entreprise, qui leur seront envoyées par courrier électronique dans les plus brefs délais à partir du moment où l\'utilisateur s\'inscrit dans cette catégorie.',
  'terms.introduction.p5': '1.2.3 Les inscriptions d\'utilisateur dans n\'importe quelle catégorie supposeront l\'acceptation totale des présentes Conditions Générales d\'Enchères. KONTACT VO S.L. s\'engage à l\'envoi d\'instructions précises sur le processus de participation à l\'enchère au moment où un utilisateur s\'inscrit sur le site web. Cet envoi se fera par courrier électronique de manière à ce que cette donnée devra être vraie et correcte au moment de l\'inscription. De même, KONTACT VO S.L. fournira à l\'utilisateur un panneau de contrôle qui sera accessible au moyen d\'un nom d\'utilisateur et d\'un mot de passe, préalablement fournis par l\'utilisateur, où celui-ci pourra avoir accès aux données complètes de son profil et où il pourra mettre à jour ses données et préférences. Par la suite, KONTACT VO S.L. et au moment où l\'enchère aura pris fin, enverra aux utilisateurs les données de la contrepartie pour qu\'il puisse communiquer avec elle. Les communications de KONTACT VO S.L. se termineront par l\'envoi de la facture pour les services rendus.',
  
  'terms.introduction.subtitle3': 'Enregistrement des véhicules',
  'terms.introduction.p6': '1.3.1 Ancienneté des véhicules : Tous les utilisateurs inscrits peuvent enregistrer des véhicules qui ont été immatriculés pour la première fois après l\'année 1983.',
  'terms.introduction.p7': '1.3.2 Description : Le vendeur doit décrire son article et toutes les conditions de vente sur la page d\'insertion d\'articles du site web. Les annonces pourront inclure des textes descriptifs, des graphiques, des photographies et d\'autres contenus pertinents pour la vente. Tous les articles insérés devront être inclus dans la catégorie appropriée. Toutes les caractéristiques et qualités de base pertinentes pour la décision d\'achat doivent être indiquées, ainsi que les défauts, qui peuvent réduire la valeur de la marchandise offerte. En outre, l\'utilisateur doit être informé en détail sur la propriété du véhicule offert et les conditions de paiement et de livraison. Les professionnels qui annoncent des véhicules aux consommateurs ont l\'obligation d\'informer sur les garanties légales. La description et les images utilisées ne doivent pas porter atteinte aux droits d\'auteur de tiers et doivent faire référence exclusivement à l\'offre (images originales). Les descriptions, les dessins et les images ne doivent pas contenir de publicité pour d\'autres articles que ceux qui sont annoncés, en particulier ils ne doivent pas renvoyer à des liens vers leur propre site web ou inclure des données sur des numéros de téléphone, etc.',
  
  'terms.introduction.subtitle4': 'Responsabilité',
  'terms.introduction.p8': '1.4.1 KONTACT VO S.L. déclare qu\'elle met uniquement à disposition un portail de commercialisation pour acheteurs et vendeurs. Les éventuels contrats de vente sont effectués exclusivement entre le vendeur et l\'acheteur. KONTACT VO S.L. n\'est pas responsable de la véracité ou de l\'exactitude des données, caractéristiques et conditions contenues dans les offres, promotions et publicité contenues dans l\'information qui est fournie. De même, ce sont les propriétaires ou commercialisateurs des véhicules qui sont les seuls responsables des opérations commerciales qu\'ils concluent en relation avec ceux-ci. KONTACT VO S.L. ne se responsabilise pas d\'un éventuel manque à gagner. KONTACT VO S.L. ne se responsabilise pas non plus des problèmes techniques ni des erreurs du programme. Sur les pages Web de KONTACT VO S.L. peuvent se trouver des liens vers d\'autres pages d\'Internet. KONTACT VO S.L. n\'offre ni ne commercialise les produits et services disponibles sur les sites liés, par conséquent elle n\'assume aucune responsabilité d\'aucune sorte en relation avec les contenus et informations, ni avec les opérations, auxquels on peut accéder ou que l\'on peut réaliser, selon le cas, à travers ce portail et en général des conséquences qui découlent de l\'accès par les utilisateurs à ceux-ci, à l\'égard desquels elle décline toute responsabilité. Ces services sont fournis par des tiers qui agissent dans tous les cas en leur propre nom et pour leur propre compte, tant en relation avec l\'offre qu\'avec la contractualisation des services dont il s\'agit, et assument pleinement leur gestion et exploitation, indépendamment de la manière dont les utilisateurs ont pu y accéder.',
  
  'terms.introduction.subtitle5': 'Clôture du contrat, règles d\'enchères, délai de la liaison',
  'terms.introduction.p9': '1.5.1 Avec l\'enregistrement d\'un véhicule sur le site web de KONTACT VO S.L., le vendeur réalise une offre contraignante pour la vente du véhicule soit au prix fixe offert soit à l\'enchérisseur qui au cours de la période d\'offre réalise l\'enchère la plus élevée. Le vendeur se déclare complètement d\'accord pour vendre son véhicule offert, en cas d\'absence d\'offres plus élevées, à l\'enchérisseur qui a enchéri pour un montant qui correspond au prix minimum. Si deux enchérisseurs réalisent la même offre, on considérera la première offre réalisée comme l\'offre la plus élevée. L\'enchérisseur est soumis à son enchère jusqu\'à ce qu\'une offre plus élevée la dépasse. Si l\'enchère n\'est pas augmentée, celle-ci prévaut, à moins que des règles spéciales n\'aient été convenues, jusqu\'à 18h00 le jour où l\'offre expire. Les offres déjà réalisées ne peuvent être réduites ni annulées. KONTACT VO S.L. enregistre et conserve toutes les offres réalisées. Si des doutes surgissent sur les offres, KONTACT VO S.L. les clarifiera de manière contraignante pour les parties contractantes. Une offre n\'est pas contraignante si l\'enchérisseur en réalisant l\'offre a commis une faute d\'orthographe évidente en réalisant l\'offre qui pourrait conduire à des erreurs ou si un tiers a réalisé l\'offre en effectuant un usage indu du nom d\'utilisateur ou du mot de passe de l\'enchérisseur, ou si l\'enchérisseur n\'est pas capable de déterminer l\'identité du vendeur dans le délai de 10 jours ouvrables après la finalisation de la période d\'offre. À la fin de la période d\'offre fixée par KONTACT VO S.L., au cas où rien d\'autre n\'ait été convenu, le délai de la liaison prendra fin à l\'expiration du jour de l\'enchère et le contrat de vente sera effectué entre le vendeur et le meilleur enchérisseur conformément au droit espagnol. Les deux parties contractantes ont l\'obligation de conclure l\'affaire. Le vendeur s\'engage à livrer le véhicule dans l\'état décrit au meilleur enchérisseur. Le meilleur enchérisseur a le devoir de récupérer le véhicule et de le payer. La même chose s\'appliquera lorsqu\'un contrat aura été réalisé à travers le centre d\'attention au client ou médiatisé d\'une autre manière par KONTACT VO S.L. Dans le cas où un véhicule aura été vendu à travers www.KONTACTVO.es, tant l\'acheteur que le vendeur s\'engagent à imprimer et utiliser le contrat directement de www.autorola.es. La note d\'achat sera également envoyée par courrier électronique ou fax. Il faut vérifier que la note d\'achat ou le contrat qu\'envoie KONTACT VO S.L. soit correct.',
  'terms.introduction.p10': '1.5.2 Exclusivité dans la médiation de KONTACT VO S.L. Une fois la vente ou l\'enchère finalisée et les données de contact de la contrepartie connues, l\'utilisateur s\'engage à respecter la figure de KONTACT VO S.L. en tant qu\'intermédiaire de l\'enchère et à payer les montants stipulés au titre de commission pour son travail d\'intermédiation. Au cas où KONTACT VO S.L. aurait connaissance que deux utilisateurs se sont mis en contact et ont finalisé la vente du véhicule en excluant la compagnie de l\'affaire, elle pourra engager les actions légales nécessaires pour la réclamation du paiement des services réalisés, pouvant solliciter une réclamation pour dommages et préjudices.',
  'terms.introduction.p11': '1.5.3 Principes de base pour les enchères en ligne Tant qu\'un véhicule se vend dans une enchère en ligne, l\'utilisateur ne pourra offrir aux enchérisseurs qui ont enchéri pour cet article des véhicules de type similaire et des marchandises que sous forme d\'offre enregistrée sur le site Web de KONTACT VO S.L., pas à travers d\'autres moyens, comme p. ex. par courrier électronique (retrait d\'enchérisseurs). Ceci est également en vigueur après l\'écoulement de la période de l\'offre. Les utilisateurs ne sont pas autorisés à manipuler le développement de l\'enchère en ligne en réalisant des enchères au moyen d\'un autre compte d\'utilisateur ou au moyen de l\'intervention d\'un tiers. En particulier, il est interdit au vendeur de réaliser des enchères pendant la période de l\'offre pour les offres qu\'il a lui-même enregistrées. Le même véhicule ne peut pas être offert simultanément dans des enchères en ligne qui ont lieu en même temps. Ceci ne s\'appliquera pas dans le cas où l\'utilisateur dispose de plusieurs véhicules et marchandises du même type. Il est interdit de réaliser des offres au moyen de méthodes de traitement automatique de données (p. ex. les programmes connus sous le nom de "Sniffer").',
  'terms.introduction.p12': '1.5.4 Déroulement de l\'enchère KONTACT VO S.L. contrôle le début, la fin et le déroulement de l\'enchère. KONTACT VO S.L. se réserve le droit de suspendre ou de modifier des enchères planifiées. KONTACT VO S.L. est autorisée à annuler des enchères sans avoir à donner de raisons pour cela. L\'annulation peut se produire aussi bien préalablement que pendant l\'enchère. Les enchères déjà réalisées ne peuvent pas être annulées.',
  'terms.introduction.p13': '1.6 Enchère élargie',

  'terms.delivery.title': 'Livraison et droit d\'inspection de l\'acheteur',
  'terms.delivery.subtitle1': 'Localité',
  'terms.delivery.p1': '2.1.1 La livraison du véhicule a lieu, au cas où un autre point n\'ait pas été convenu, au moment où l\'acheteur le récupère. La récupération devra être effectuée à l\'adresse indiquée par le vendeur dans la zone du code postal, et qui est indiquée dans la description. Si aucune adresse n\'est indiquée dans la zone du code postal mentionné, le véhicule sera récupéré à l\'adresse du vendeur. Lors de l\'enregistrement du véhicule, le vendeur a la possibilité d\'offrir à l\'acheteur la livraison du véhicule à un autre endroit, au lieu que celui-ci le récupère à l\'adresse du vendeur. Cet endroit peut être l\'adresse de l\'acheteur ou un autre lieu. De façon optionnelle, cette clause remplacera la récupération. Bien que le vendeur sélectionne cette possibilité, l\'acheteur peut toujours convenir de la récupération du véhicule à l\'adresse du vendeur, si cela est préféré ainsi.',
  
  'terms.delivery.subtitle2': 'Délai',
  'terms.delivery.p2': '2.2.1 La livraison devra être effectuée au maximum dans un délai de 5 jours ouvrables après l\'entrée en vigueur du contrat. Le vendeur s\'engage à ce que l\'acheteur récupère le véhicule dans le délai indiqué dans l\'intervalle compris entre 9 et 17 heures, heure d\'Europe centrale. S\'il arrive que les parties contractantes ne se mettent pas d\'accord sur l\'heure, l\'acheteur la fixera dans l\'intervalle indiqué, en laissant toujours un délai d\'au moins 24 heures au vendeur.',
  
  'terms.delivery.subtitle3': 'Inspection',
  'terms.delivery.p3': '2.3.1 Vérifiez les dommages et s\'il existe des différences avec ce qui a été publié, reflétez-les dans le bordereau de sortie. Le fournisseur du véhicule ne se responsabilise pas de la différence de dommages extérieurs (tôle et peinture) qui pourrait exister dans le véhicule une fois retiré des installations.',
  
  'terms.delivery.subtitle4': 'Données du véhicule',
  'terms.delivery.p4': '2.4.1 Avant d\'effectuer le paiement, l\'acheteur est autorisé à vérifier que le numéro de châssis du véhicule et la plaque d\'immatriculation, le cas échéant, coïncident avec la titularité du véhicule. Il devra être remis à l\'acheteur la titularité originale du véhicule/certificat d\'immatriculation II, le permis de circulation du véhicule/certificat d\'immatriculation I, le document d\'inspections générales et le document de contrôle des gaz de combustion, tout cela avec le véhicule.',

  'terms.payment.title': 'Paiement du véhicule',
  'terms.payment.subtitle1': 'Paiement',
  'terms.payment.p1': '3.1.1 La totalité du prix d\'achat, à moins qu\'il n\'existe des conditions de contractualisation spéciales, doit être effectuée par l\'acheteur au moment de la livraison du véhicule, de la certification d\'immatriculation originale et toute la documentation liée au véhicule. Si l\'une des parties contractantes sollicite un reçu, l\'autre partie contractante est obligée de lui remettre une note d\'avoir.',
  
  'terms.payment.subtitle2': 'Paiements en enchère ouverte',
  'terms.payment.p2': '3.2.1 Nous vous rappelons qu\'Autorola Espagne est un simple intermédiaire et nous vous recommandons de vérifier l\'état du véhicule sur place avant d\'effectuer le paiement. À la clôture de la vente, KONTACT VO mettra en contact le vendeur et l\'acheteur pour finaliser la transaction.',

  'terms.obligations.title': 'Obligations',
  'terms.obligations.subtitle1': 'Obligations du vendeur',
  'terms.obligations.p1': '4.1.1 Le vendeur se responsabilise que le véhicule soit disponible, que toutes les données indiquées sur le véhicule soient correctes, vraies et suffisantes et que le véhicule ne présente pas de défauts. Le vendeur garantit qu\'il est propriétaire légal du véhicule et qu\'il n\'existe pas de droits à des tiers (réserve de la propriété, exécution judiciaire, droit de préférence, interdiction d\'aliénation ou autres droits) qui limitent ou empêchent la vente du véhicule sans charges. Ceci ne s\'appliquera pas lorsque le vendeur aura informé sur ces droits dans la description du véhicule et lorsqu\'il aura convenu avec l\'acheteur que celui-ci remplira ou assumera ces droits en concluant le contrat de vente. Avant d\'enregistrer le véhicule, le vendeur devra assurer que toutes les obligations possibles et autres droits concernant le véhicule liés au transfert de propriété pourront être remplis au plus tard au moment de la livraison. Si le véhicule est livré avec une immatriculation provisoire, une assurance responsabilité civile valide au moment de la livraison sera requise. Si le véhicule n\'est pas livré immatriculé, au moment du transfert il ne sera pas assuré.',
  
  'terms.obligations.subtitle2': 'Obligations de l\'acheteur',
  'terms.obligations.p2': '4.2.1 Si l\'acheteur obtient le véhicule avec une immatriculation valide, il s\'engage à indiquer le changement de propriétaire dans un délai maximum de trois jours après la livraison. Si l\'acheteur a été le meilleur enchérisseur avec son offre sur www.KONTACTVO.es selon les règles d\'enchère ou a accepté l\'achat d\'une autre manière, un contrat sera effectué entre l\'acheteur et le vendeur. L\'acheteur a l\'obligation de récupérer le véhicule et de rendre effective la somme convenue. Il est fait référence aux autres dispositions sur les responsabilités et obligations stipulées dans les conditions d\'enchère.',
  
  'terms.obligations.subtitle3': 'Litiges entre l\'acheteur et le vendeur',
  'terms.obligations.p3': '4.3.1 Si une réclamation a été présentée en temps voulu et qu\'il existe un manquement/défaut dont l\'autre partie contractante est responsable, les liquidations rétroactives ou demandes d\'indemnisation seront effectuées conformément au droit espagnol. Si l\'acheteur ou le vendeur présente une demande contre l\'autre partie contractante, les frais de transport seront fixés à un montant fixe. Dans le cas où, selon accord des parties contractantes, plusieurs transports du véhicule se seraient produits, le montant des frais pour transport sera augmenté. Dans le cas de différends entre l\'acheteur et le vendeur qui ne peuvent être résolus immédiatement d\'un commun accord, il sera demandé aux parties de prendre des mesures judiciaires. Dans le cas d\'un litige entre l\'acheteur et le vendeur, une copie du contrat devra être envoyée immédiatement avec une description du motif à KONTACT VO S.L. Celle-ci sera utilisée à des fins statistiques et d\'enregistrement et n\'impliquera, en aucun cas, que KONTACT VO S.L. assume le rôle de partie impliquée. Dans tous les cas, le droit de KONTACT VO S.L. à une commission ne sera pas affecté et les parties s\'engagent à la satisfaire, tel qu\'exposé dans la clause 1.5.2.',

  'terms.registration.title': 'Enregistrement, blocage, suspension et résiliation',
  'terms.registration.p1': '5.1.1 Pour pouvoir faire usage de tous les services de KONTACT VO S.L., un "utilisateur" doit être enregistré. Il n\'existe pas de droit à l\'enregistrement sur KONTACT VO S.L. L\'enregistrement est gratuit. Il est effectué en ouvrant un compte utilisateur et en présentant la déclaration de conformité aux conditions commerciales générales correspondantes. Avec l\'enregistrement, un contrat est effectué entre KONTACT VO S.L. et l\'"utilisateur" sur l\'utilisation de la plateforme d\'enchères de véhicules www.autorola.es. Les données que KONTACT VO S.L. demande pendant l\'enregistrement doivent être complètes et correctes. S\'il se produit une modification dans les données de l\'"utilisateur" après l\'enregistrement, l\'"utilisateur" a le devoir de communiquer ladite modification à KONTACT VO S.L. Pendant l\'enregistrement, l\'"utilisateur" sélectionnera un nom d\'utilisateur et un mot de passe. Le nom d\'utilisateur ne doit pas s\'agir d\'une adresse électronique ni d\'une adresse Internet ni ne doit violer les droits de tiers, en particulier les droits de nom ou de marque. Le mot de passe doit être gardé secret. L\'utilisateur se responsabilise des cas d\'usage indu du nom d\'utilisateur et du mot de passe. Le compte utilisateur n\'est pas transférable. KONTACT VO S.L. peut bloquer le compte utilisateur à tout moment. Au moment où un compte utilisateur est bloqué, cet utilisateur ne pourra plus continuer à utiliser les sites Web de KONTACT VO S.L. et ne pourra pas se réenregistrer sans une autorisation expresse de KONTACT VO S.L. L\'utilisateur peut résilier le contrat d\'utilisation à tout moment. Pour la déclaration de résiliation, une note écrite ou un courrier électronique à servicioalcliente@autorola.es est suffisant. KONTACT VO S.L. peut résilier le contrat d\'utilisation avec un effet immédiat à tout moment sans nécessité de respecter les délais.',

  'terms.fees.title': 'Tarifs',
  'terms.fees.p1': '6.1.1 L\'enregistrement comme utilisateur sur www.KONTACTVO.es est gratuit. Le montant des véhicules est montré sur la fiche de chacun, avec mention expresse de l\'inclusion ou non des impôts correspondants (TVA, Taxe d\'Immatriculation, etc.) Le montant de la commission est basé sur la liste de prix actuelle. Celle-ci peut être consultée dans Liste de prix. Les commissions devront être rendues effectives au moment de recevoir la facture. Elles pourront être rendues effectives au moyen d\'un transfert ou d\'un prélèvement bancaire. Si le paiement ne peut pas être effectué, l\'utilisateur devra payer les frais additionnels occasionnés, dans le cas où il serait responsable de la situation. KONTACT VO S.L. enverra à l\'utilisateur les factures par courrier postal ou à son adresse électronique. L\'utilisateur tombera en demeure sans recevoir un autre rappel de paiement après deux semaines après l\'envoi de la facture. Dans le montant de la facture figure la TVA en vigueur le jour de la facturation. La commission correspondante sera payée au vendeur dans le cas où l\'autre partie contractante ne remplirait pas comme il se doit le contrat conclu à travers le site Web de KONTACT VO S.L. L\'avoir devra être demandé conformément à la procédure prévue. La compensation avec des crédits d\'avoirs en compte non encore accordés n\'est autorisée que pour des crédits payables et/ou futurs tant que ces crédits sont juridiquement valides ou indiscutables.',

  'terms.prohibitedItems.title': 'Articles interdits',
  'terms.prohibitedItems.p1': '7.1.1 Il est interdit d\'offrir des véhicules dont l\'offre, la vente ou l\'acquisition enfreignent les dispositions légales. En particulier, ne devront pas être décrits ni offerts les véhicules suivants : véhicules dont la demande, l\'offre ou la vente viole les droits d\'auteur.',

  'terms.principles.title': 'Principes de base généraux',
  'terms.principles.p1': '8.1.1 L\'utilisateur a l\'obligation de respecter la loi en vigueur lorsqu\'il utilise le site Web de KONTACT VO S.L. et les prestations de service de KONTACT VO S.L. Si sur la plateforme commerciale on arrive à conclure un contrat entre les utilisateurs, KONTACT VO S.L. facilitera les données nécessaires pour le contact. Si les utilisateurs sont des entrepreneurs s\'appliquera, dans les contrats célébrés entre ces utilisateurs sur le marché qu\'offre KONTACT VO S.L., tant qu\'autre chose n\'a pas été convenue, les lois en vigueur d\'Espagne en excluant expressément l\'application de la Convention des Nations Unies sur les Contrats de Vente Internationale de Marchandises. Si l\'un des utilisateurs qui conclut le contrat est un consommateur, s\'appliquera le droit du pays dans lequel celui-ci a son domicile habituel. Il est interdit à tous les utilisateurs d\'utiliser les adresses obtenues, les données de contact et les adresses électroniques pour la publicité commerciale.',

  'terms.exemption.title': 'Exemption',
  'terms.exemption.p1': '9.1.1 L\'utilisateur exempte KONTACT VO S.L. de toute responsabilité par rapport à toute réclamation d\'autres utilisateurs ou de tiers contre KONTACT VO S.L. pour la violation de leurs droits dans les offres ou contenus que l\'utilisateur a enregistrés sur le site Web ou pour un usage inadéquat du site Web de KONTACT VO S.L. de sa part. L\'utilisateur se chargera des coûts de la défense des droits de KONTACT VO S.L., y compris tous les honoraires d\'avocats et de procureurs ainsi que les taxes judiciaires. Cela ne s\'appliquera pas dans le cas où la violation du droit n\'est pas de la responsabilité de l\'utilisateur.',

  'terms.integrity.title': 'Intégrité du système',
  'terms.integrity.p1': '10.1.1 L\'utilisateur n\'est pas autorisé à utiliser des mécanismes, des logiciels ni d\'autres voies en relation avec l\'utilisation de la page web de KONTACT VO S.L. qui pourraient entraver le fonctionnement de ladite page web. L\'utilisateur n\'est pas autorisé à prendre aucune mesure qui puisse entraîner une charge disproportionnée ou excessive dans l\'infrastructure. Il est interdit de copier, divulguer, reproduire ou utiliser à d\'autres fins les contenus du site Web de KONTACT VO S.L. sans le consentement préalable du titulaire des droits. Ceci concerne également les copies réalisées au moyen de techniques de moteurs de recherche "Robot/Crawler" (robots d\'indexation) ou d\'autres mécanismes automatiques. La reproduction et l\'utilisation sur d\'autres sites Web du design du site Web de KONTACT VO S.L. et des conditions d\'utilisation générales n\'est autorisée qu\'avec le consentement préalable et par écrit de KONTACT VO S.L.',
};

