
export default {
  // Calculator
  'calculator.title': 'Import Cost Calculator',
  'calculator.subtitle': 'For professionals (B2B) - Vehicle import to Spain',
  
  // Form
  'calculator.form.title': 'Vehicle and import data',
  'calculator.form.description': 'Enter details to calculate import costs',
  
  // Tabs
  'calculator.tabs.vehicle': 'Vehicle',
  'calculator.tabs.fiscal': 'Fiscal',
  'calculator.tabs.emissions': 'Emissions',
  'calculator.tabs.services': 'Services',
  
  // Vehicle tab
  'calculator.vehicle.type': 'Vehicle type',
  'calculator.vehicle.selectType': 'Select type',
  'calculator.vehicle.car': 'Car',
  'calculator.vehicle.commercial': 'Commercial',
  'calculator.vehicle.motorcycle': 'Motorcycle',
  'calculator.vehicle.originCountry': 'Country of origin',
  'calculator.vehicle.selectCountry': 'Select country',
  'calculator.vehicle.isNew': 'New vehicle',
  'calculator.vehicle.newTooltip': 'A vehicle is considered new if it is less than 6 months old or has less than 6,000 km',
  
  // Fiscal tab
  'calculator.fiscal.price': 'Vehicle price (€)',
  'calculator.fiscal.includesVAT': 'Price includes VAT',
  'calculator.fiscal.vatTooltip': 'In intra-community B2B operations, VAT is self-invoiced in Spain',
  'calculator.fiscal.ivtmTax': 'Circulation tax (IVTM) (€)',
  'calculator.fiscal.ivtmTooltip': 'Annual municipal tax that varies according to vehicle power and municipality. Usually between €30 and €200.',
  
  // Emissions tab
  'calculator.emissions.co2': 'CO2 emissions (g/km)',
  'calculator.emissions.taxRate': 'Applicable registration tax',
  
  // Services tab
  'calculator.services.agency': 'Hire agency',
  'calculator.services.agencyTooltip': 'Includes management of administrative procedures',
  'calculator.services.transport': 'Include transport',
  
  // Buttons
  'calculator.buttons.next': 'Next step',
  'calculator.buttons.calculate': 'Calculate costs',
  'calculator.buttons.printCalculation': 'Print calculation',
  
  // Results
  'calculator.results.title': 'Cost summary',
  'calculator.results.netPrice': 'Net price',
  'calculator.results.vat': 'VAT (21%)',
  'calculator.results.vatInfo': 'VAT self-invoiced in Spain for B2B operations',
  'calculator.results.matriculation': 'Registration tax',
  'calculator.results.matriculationInfo': 'Based on CO2 emissions',
  'calculator.results.adminCostsTitle': 'Administrative costs',
  'calculator.results.dgtFee': 'Registration fee (DGT)',
  'calculator.results.technicalSheet': 'Reduced technical sheet',
  'calculator.results.itv': 'Import ITV',
  'calculator.results.trafficFee': 'Traffic fee (circulation permit)',
  'calculator.results.ivtm': 'Circulation tax (IVTM)',
  'calculator.results.ivtmInfo': 'Annual municipal tax (varies by power and municipality)',
  'calculator.results.agency': 'Agency',
  'calculator.results.transport': 'Transport',
  'calculator.results.total': 'Total cost',
  
  // Info
  'calculator.info.title': 'Important information',
  'calculator.info.disclaimer': 'Calculations are estimates and may vary. Consult a professional for specific information.',
  'calculator.info.b2bOnly': 'This calculator is designed exclusively for B2B imports (between professionals).',
  'calculator.info.vatInfo': 'In intra-community B2B operations, the Spanish buyer self-invoices VAT, declaring and deducting it simultaneously.',
  
  // Printable document
  'calculator.printable.title': 'Vehicle Import Cost Calculation',
  'calculator.printable.date': 'Date',
  'calculator.printable.vehicleDetails': 'Vehicle details',
  'calculator.printable.footer': 'Generated by KONECT VO Automotive Marketplace - Import Calculator',
  
  // Additional buttons and info
  'calculator.buttons.reset': 'Reset Calculations',
  'calculator.buttons.confirmReset': 'Yes, reset',
  'calculator.info.resetSuccess': 'Calculations reset successfully',
  'calculator.info.resetDescription': 'All values have been reset to their default values',
  'calculator.info.resetQuestion': 'Do you want to reset all calculations to start fresh with default values?',
  
  // Common
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.continue': 'Continue'
};
