/**
 * useStaticImage Hook
 * 
 * Retrieves product/UI images from the STATIC_IMAGE_REGISTRY.
 * PRIORITIZES images stored in Supabase Storage (generated by AI).
 * Falls back to registry path if no storage image exists.
 * 
 * ⚠️ PRODUCT IMAGES ONLY - Never use for user-generated content
 * 
 * @example
 * const { src, isValid, entry } = useStaticImage('home.hero');
 * <img src={src} alt={entry?.purpose} />
 */

import { useMemo, useState, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import {
  STATIC_IMAGE_REGISTRY,
  StaticImageEntry,
  StaticImageId,
  StaticImageKey,
  getImageById,
  isProductImagePath,
  validateRegistry,
  isValidImageId
} from '@/config/staticImageRegistry';

const FALLBACK_IMAGE = '/placeholder.svg';
const STORAGE_BUCKET = 'static-images';

export interface UseStaticImageResult {
  /** The resolved image path (storage URL, currentPath, or fallback) */
  src: string;
  /** Whether the image entry exists in the registry */
  isValid: boolean;
  /** Whether the path passed validation (is product image) */
  isProductPath: boolean;
  /** The full registry entry (null if not found) */
  entry: StaticImageEntry | null;
  /** Fallback path if main image fails */
  fallback: string;
  /** Whether this image is marked as critical */
  isCritical: boolean;
  /** Whether this image can be AI-edited */
  isAIEditable: boolean;
  /** Whether the image is from Supabase Storage (AI generated) */
  isFromStorage: boolean;
  /** Whether the hook is still checking storage */
  isLoading: boolean;
}

const isDev = import.meta.env.DEV;

// Cache for storage URLs to avoid repeated API calls
const storageUrlCache = new Map<string, { url: string | null; timestamp: number }>();
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

/**
 * Convert image ID to storage path prefix
 * e.g., 'home.hero' -> 'home/hero/'
 */
const getStoragePrefix = (imageId: string): string => {
  return imageId.replace(/\./g, '/') + '/';
};

/**
 * Check if a cached URL is still valid
 */
const isCacheValid = (imageId: string): boolean => {
  const cached = storageUrlCache.get(imageId);
  if (!cached) return false;
  return Date.now() - cached.timestamp < CACHE_TTL;
};

/**
 * Hook to retrieve a static image from the registry
 * Prioritizes images from Supabase Storage over registry paths
 * @param imageId The image ID (e.g., 'home.hero', 'services.showroom')
 * @returns Image data with src, validation status, and metadata
 */
export const useStaticImage = (imageId: string): UseStaticImageResult => {
  const [storageUrl, setStorageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isFromStorage, setIsFromStorage] = useState(false);
  const mountedRef = useRef(true);
  const checkedRef = useRef(false);

  // Get registry entry (memoized)
  const registryData = useMemo(() => {
    if (isDev && !isValidImageId(imageId)) {
      console.warn(`[useStaticImage] Image ID not in registry: ${imageId}`);
    }

    const entry = getImageById(imageId);
    
    if (!entry) {
      if (isDev) {
        console.warn(`[useStaticImage] Image not found in registry: ${imageId}`);
      }
      return {
        entry: null,
        isValid: false,
        isProductPath: false,
        resolvedSrc: FALLBACK_IMAGE,
        fallback: FALLBACK_IMAGE,
        isCritical: false,
        isAIEditable: false
      };
    }
    
    const isProductPath = isProductImagePath(entry.currentPath);
    
    if (!isProductPath && isDev) {
      console.error(`[useStaticImage] WARNING: Image "${imageId}" has user-content path: ${entry.currentPath}`);
    }
    
    let resolvedSrc = entry.currentPath;
    if (entry.currentPath.startsWith('src/assets/')) {
      resolvedSrc = `/${entry.currentPath}`;
    }
    
    const fallback = entry.fallback || FALLBACK_IMAGE;
    
    return {
      entry,
      isValid: true,
      isProductPath,
      resolvedSrc,
      fallback,
      isCritical: entry.critical,
      isAIEditable: entry.aiEditable
    };
  }, [imageId]);

  // Check Supabase Storage for AI-generated images
  useEffect(() => {
    mountedRef.current = true;
    
    // Only check storage for AI-editable images
    if (!registryData.isAIEditable || !registryData.entry) {
      setIsLoading(false);
      return;
    }

    // Check cache first
    if (isCacheValid(imageId)) {
      const cached = storageUrlCache.get(imageId);
      if (cached) {
        setStorageUrl(cached.url);
        setIsFromStorage(cached.url !== null);
        setIsLoading(false);
        return;
      }
    }

    // Don't re-check if already checked in this mount
    if (checkedRef.current) {
      return;
    }
    checkedRef.current = true;

    const checkStorage = async () => {
      try {
        const prefix = getStoragePrefix(imageId);
        
        // List files in the storage path
        const { data: files, error } = await supabase.storage
          .from(STORAGE_BUCKET)
          .list(prefix.slice(0, -1), {
            limit: 1,
            sortBy: { column: 'created_at', order: 'desc' }
          });

        if (!mountedRef.current) return;

        if (error) {
          console.warn(`[useStaticImage] Storage check error for ${imageId}:`, error.message);
          storageUrlCache.set(imageId, { url: null, timestamp: Date.now() });
          setIsLoading(false);
          return;
        }

        // Filter out folders (no metadata means it's a folder)
        const imageFiles = files?.filter(f => f.metadata && f.name) || [];

        if (imageFiles.length > 0) {
          const latestFile = imageFiles[0];
          const { data: urlData } = supabase.storage
            .from(STORAGE_BUCKET)
            .getPublicUrl(`${prefix}${latestFile.name}`);

          if (urlData?.publicUrl && mountedRef.current) {
            // Add cache buster for fresh images
            const urlWithCacheBuster = `${urlData.publicUrl}?t=${Date.now()}`;
            storageUrlCache.set(imageId, { url: urlWithCacheBuster, timestamp: Date.now() });
            setStorageUrl(urlWithCacheBuster);
            setIsFromStorage(true);
          }
        } else {
          storageUrlCache.set(imageId, { url: null, timestamp: Date.now() });
        }
      } catch (err) {
        console.warn(`[useStaticImage] Error checking storage for ${imageId}:`, err);
        storageUrlCache.set(imageId, { url: null, timestamp: Date.now() });
      } finally {
        if (mountedRef.current) {
          setIsLoading(false);
        }
      }
    };

    checkStorage();

    return () => {
      mountedRef.current = false;
    };
  }, [imageId, registryData.isAIEditable, registryData.entry]);

  // Return final result - prioritize storage URL if available
  return useMemo(() => ({
    src: storageUrl || registryData.resolvedSrc,
    isValid: registryData.isValid,
    isProductPath: registryData.isProductPath,
    entry: registryData.entry,
    fallback: registryData.fallback,
    isCritical: registryData.isCritical,
    isAIEditable: registryData.isAIEditable,
    isFromStorage,
    isLoading
  }), [storageUrl, registryData, isFromStorage, isLoading]);
};

/**
 * Get static image by registry key (not ID)
 * @param registryKey The key in STATIC_IMAGE_REGISTRY (e.g., 'HOME_HERO')
 */
export const useStaticImageByKey = (registryKey: StaticImageKey | string): UseStaticImageResult => {
  const entry = STATIC_IMAGE_REGISTRY[registryKey as StaticImageKey];
  const imageId = entry?.id || '';
  return useStaticImage(imageId);
};

/**
 * Get multiple static images at once
 * @param imageIds Array of image IDs
 */
export const useStaticImages = (imageIds: string[]): Record<string, UseStaticImageResult> => {
  // This is a simplified version - for batch operations
  // Each ID gets its own useStaticImage call internally
  const results: Record<string, UseStaticImageResult> = {};
  
  // Note: This won't work with hooks rules - need individual calls
  // For now, return basic registry data without storage check
  return useMemo(() => {
    for (const imageId of imageIds) {
      const entry = getImageById(imageId);
      
      if (!entry) {
        results[imageId] = {
          src: FALLBACK_IMAGE,
          isValid: false,
          isProductPath: false,
          entry: null,
          fallback: FALLBACK_IMAGE,
          isCritical: false,
          isAIEditable: false,
          isFromStorage: false,
          isLoading: false
        };
        continue;
      }
      
      const isProductPath = isProductImagePath(entry.currentPath);
      let resolvedSrc = entry.currentPath;
      if (entry.currentPath.startsWith('src/assets/')) {
        resolvedSrc = `/${entry.currentPath}`;
      }
      
      const fallback = entry.fallback || FALLBACK_IMAGE;
      
      results[imageId] = {
        src: resolvedSrc,
        isValid: true,
        isProductPath,
        entry,
        fallback,
        isCritical: entry.critical,
        isAIEditable: entry.aiEditable,
        isFromStorage: false,
        isLoading: false
      };
    }
    
    return results;
  }, [imageIds.join(',')]);
};

/**
 * Helper to get image path directly (non-hook version for data files)
 * Does NOT check storage - use useStaticImage hook for that
 * @param imageId The image ID
 * @returns The resolved image path from registry
 */
export const getStaticImagePath = (imageId: string): string => {
  const entry = getImageById(imageId);
  
  if (!entry) {
    if (isDev) {
      console.warn(`[getStaticImagePath] Image not found: ${imageId}`);
    }
    return FALLBACK_IMAGE;
  }
  
  if (!isProductImagePath(entry.currentPath) && isDev) {
    console.error(`[getStaticImagePath] User-content path detected: ${imageId}`);
  }
  
  return entry.currentPath;
};

/**
 * Get static image entry with full metadata (non-hook version)
 */
export const getStaticImageEntry = (imageId: string): StaticImageEntry | null => {
  return getImageById(imageId) || null;
};

/**
 * Invalidate cache for a specific image ID
 * Call this after generating/replacing an image
 */
export const invalidateStaticImageCache = (imageId: string): void => {
  storageUrlCache.delete(imageId);
};

/**
 * Clear all cached storage URLs
 */
export const clearStaticImageCache = (): void => {
  storageUrlCache.clear();
};

export default useStaticImage;
