
-- 1. Add key and active columns to equipment_items
ALTER TABLE public.equipment_items 
  ADD COLUMN IF NOT EXISTS key text UNIQUE,
  ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;

-- 2. Create translation table linked to equipment_items
CREATE TABLE IF NOT EXISTS public.vehicle_option_translations (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  option_id uuid NOT NULL REFERENCES public.equipment_items(id) ON DELETE CASCADE,
  language_code text NOT NULL,
  label text NOT NULL,
  UNIQUE(option_id, language_code)
);

ALTER TABLE public.vehicle_option_translations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view translations" ON public.vehicle_option_translations
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage translations" ON public.vehicle_option_translations
  FOR ALL USING (EXISTS (
    SELECT 1 FROM user_roles WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::app_role
  ));

-- 3. Create custom options table
CREATE TABLE IF NOT EXISTS public.vehicle_custom_options (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id uuid NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  label text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.vehicle_custom_options ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view custom options" ON public.vehicle_custom_options
  FOR SELECT USING (true);

CREATE POLICY "Vehicle owners can manage custom options" ON public.vehicle_custom_options
  FOR ALL USING (EXISTS (
    SELECT 1 FROM vehicles WHERE vehicles.id = vehicle_custom_options.vehicle_id AND vehicles.seller_id = auth.uid()
  ));

-- 4. Seed categories
INSERT INTO public.equipment_categories (name, display_order, icon, description) VALUES
  ('safety', 1, 'Shield', 'Safety features'),
  ('assistance', 2, 'HelpCircle', 'Driver assistance'),
  ('comfort', 3, 'Armchair', 'Comfort features'),
  ('infotainment', 4, 'Radio', 'Infotainment systems'),
  ('interior', 5, 'Layout', 'Interior features'),
  ('exterior', 6, 'Car', 'Exterior features'),
  ('lighting', 7, 'Lightbulb', 'Lighting systems'),
  ('climate', 8, 'Thermometer', 'Climate control'),
  ('seats', 9, 'Seat', 'Seat features'),
  ('security', 10, 'Lock', 'Security systems'),
  ('driving', 11, 'Gauge', 'Driving dynamics'),
  ('performance', 12, 'Zap', 'Performance features'),
  ('others', 13, 'MoreHorizontal', 'Other features');

-- 5. Seed equipment_items with keys
INSERT INTO public.equipment_items (name, key, category_id, active) VALUES
-- SAFETY
('ABS', 'abs', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('ESP', 'esp', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Traction Control', 'traction_control', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Emergency Brake Assist', 'emergency_brake_assist', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Brake Assist', 'brake_assist', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Lane Departure Warning', 'lane_departure_warning', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Lane Keep Assist', 'lane_keep_assist', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Blind Spot Monitor', 'blind_spot_monitor', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Rear Cross Traffic Alert', 'rear_cross_traffic_alert', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Driver Fatigue Detection', 'driver_fatigue_detection', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Traffic Sign Recognition', 'traffic_sign_recognition', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Pedestrian Detection', 'pedestrian_detection', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Cyclist Detection', 'cyclist_detection', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Collision Warning', 'collision_warning', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Hill Start Assist', 'hill_start_assist', (SELECT id FROM equipment_categories WHERE name='safety'), true),
('Hill Descent Control', 'hill_descent_control', (SELECT id FROM equipment_categories WHERE name='safety'), true),
-- ASSISTANCE
('Adaptive Cruise Control', 'adaptive_cruise_control', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Cruise Control', 'cruise_control', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Speed Limiter', 'speed_limiter', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Parking Assist', 'parking_assist', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Automatic Parking', 'automatic_parking', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Rear View Camera', 'rear_view_camera', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Surround View Camera', 'surround_view_camera', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Front Parking Sensors', 'front_parking_sensors', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Rear Parking Sensors', 'rear_parking_sensors', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Automatic Emergency Braking', 'automatic_emergency_braking', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
('Traffic Jam Assist', 'traffic_jam_assist', (SELECT id FROM equipment_categories WHERE name='assistance'), true),
-- COMFORT
('Keyless Entry', 'keyless_entry', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Keyless Start', 'keyless_start', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Electric Tailgate', 'electric_tailgate', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Hands Free Tailgate', 'hands_free_tailgate', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Remote Start', 'remote_start', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Heated Steering Wheel', 'heated_steering_wheel', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Power Steering', 'power_steering', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Adjustable Steering Wheel', 'adjustable_steering_wheel', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Ambient Lighting', 'ambient_lighting', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
('Soft Close Doors', 'soft_close_doors', (SELECT id FROM equipment_categories WHERE name='comfort'), true),
-- INFOTAINMENT
('Bluetooth', 'bluetooth', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('USB Ports', 'usb_ports', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Apple CarPlay', 'apple_carplay', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Android Auto', 'android_auto', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Navigation System', 'navigation_system', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Digital Radio', 'digital_radio', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('WiFi Hotspot', 'wifi_hotspot', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Voice Control', 'voice_control', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Touchscreen Display', 'touchscreen_display', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
('Rear Entertainment System', 'rear_entertainment_system', (SELECT id FROM equipment_categories WHERE name='infotainment'), true),
-- INTERIOR
('Leather Interior', 'leather_interior', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Fabric Interior', 'fabric_interior', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Alcantara Interior', 'alcantara_interior', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Carbon Fiber Trim', 'carbon_fiber_trim', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Wood Trim', 'wood_trim', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Adjustable Ambient Light', 'adjustable_ambient_light', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Multifunction Steering Wheel', 'multifunction_steering_wheel', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Digital Dashboard', 'digital_dashboard', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Head Up Display', 'head_up_display', (SELECT id FROM equipment_categories WHERE name='interior'), true),
('Configurable Instrument Cluster', 'configurable_instrument_cluster', (SELECT id FROM equipment_categories WHERE name='interior'), true),
-- EXTERIOR
('Alloy Wheels', 'alloy_wheels', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Steel Wheels', 'steel_wheels', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Roof Rails', 'roof_rails', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Panoramic Roof', 'panoramic_roof', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Sunroof', 'sunroof', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Tinted Windows', 'tinted_windows', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Metallic Paint', 'metallic_paint', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Pearlescent Paint', 'pearlescent_paint', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Tow Hook', 'tow_hook', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
('Electric Mirrors', 'electric_mirrors', (SELECT id FROM equipment_categories WHERE name='exterior'), true),
-- LIGHTING
('LED Headlights', 'led_headlights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Xenon Headlights', 'xenon_headlights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Matrix LED', 'matrix_led', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Adaptive Headlights', 'adaptive_headlights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Automatic Headlights', 'automatic_headlights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Daytime Running Lights', 'daytime_running_lights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Fog Lights', 'fog_lights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
('Cornering Lights', 'cornering_lights', (SELECT id FROM equipment_categories WHERE name='lighting'), true),
-- CLIMATE
('Manual Air Conditioning', 'manual_air_conditioning', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Automatic Climate Control', 'automatic_climate_control', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Dual Zone Climate', 'dual_zone_climate', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Tri Zone Climate', 'tri_zone_climate', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Air Quality Sensor', 'air_quality_sensor', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Pollen Filter', 'pollen_filter', (SELECT id FROM equipment_categories WHERE name='climate'), true),
('Ventilated Seats (Climate)', 'ventilated_seats_climate', (SELECT id FROM equipment_categories WHERE name='climate'), true),
-- SEATS
('Heated Seats', 'heated_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Ventilated Seats', 'ventilated_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Electric Seats', 'electric_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Memory Seats', 'memory_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Massage Seats', 'massage_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Sport Seats', 'sport_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Rear Adjustable Seats', 'rear_adjustable_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Folding Rear Seats', 'folding_rear_seats', (SELECT id FROM equipment_categories WHERE name='seats'), true),
('Child Seat ISOFIX', 'child_seat_isofix', (SELECT id FROM equipment_categories WHERE name='seats'), true),
-- SECURITY
('Alarm System', 'alarm_system', (SELECT id FROM equipment_categories WHERE name='security'), true),
('Immobilizer', 'immobilizer', (SELECT id FROM equipment_categories WHERE name='security'), true),
('Anti Theft System', 'anti_theft_system', (SELECT id FROM equipment_categories WHERE name='security'), true),
('Wheel Lock', 'wheel_lock', (SELECT id FROM equipment_categories WHERE name='security'), true),
('Interior Monitoring', 'interior_monitoring', (SELECT id FROM equipment_categories WHERE name='security'), true),
('GPS Tracker', 'gps_tracker', (SELECT id FROM equipment_categories WHERE name='security'), true),
-- DRIVING
('Drive Modes', 'drive_modes', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('Sport Mode', 'sport_mode', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('Eco Mode', 'eco_mode', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('All Wheel Drive', 'all_wheel_drive', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('Differential Lock', 'differential_lock', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('Air Suspension', 'air_suspension', (SELECT id FROM equipment_categories WHERE name='driving'), true),
('Adaptive Suspension', 'adaptive_suspension', (SELECT id FROM equipment_categories WHERE name='driving'), true),
-- PERFORMANCE
('Sport Exhaust', 'sport_exhaust', (SELECT id FROM equipment_categories WHERE name='performance'), true),
('Performance Brakes', 'performance_brakes', (SELECT id FROM equipment_categories WHERE name='performance'), true),
('Launch Control', 'launch_control', (SELECT id FROM equipment_categories WHERE name='performance'), true),
('Turbo', 'turbo', (SELECT id FROM equipment_categories WHERE name='performance'), true),
('Regenerative Braking', 'regenerative_braking', (SELECT id FROM equipment_categories WHERE name='performance'), true),
-- OTHERS
('Start Stop System', 'start_stop_system', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Spare Wheel', 'spare_wheel', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Tire Repair Kit', 'tire_repair_kit', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Onboard Computer', 'onboard_computer', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Service History', 'service_history', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Warranty', 'warranty', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Battery Certificate', 'battery_certificate', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Inspection Report', 'inspection_report', (SELECT id FROM equipment_categories WHERE name='others'), true),
('Homologation Documents', 'homologation_documents', (SELECT id FROM equipment_categories WHERE name='others'), true);

-- 6. Seed translations for ALL options in 9 languages
-- Using a DO block for efficiency
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT id, key FROM equipment_items LOOP
    -- SPANISH
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'es', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Control de tracción'
      WHEN 'emergency_brake_assist' THEN 'Asistente de frenado de emergencia'
      WHEN 'brake_assist' THEN 'Asistente de frenado'
      WHEN 'lane_departure_warning' THEN 'Alerta de cambio de carril'
      WHEN 'lane_keep_assist' THEN 'Asistente de mantenimiento de carril'
      WHEN 'blind_spot_monitor' THEN 'Monitor de ángulo muerto'
      WHEN 'rear_cross_traffic_alert' THEN 'Alerta de tráfico trasero cruzado'
      WHEN 'driver_fatigue_detection' THEN 'Detector de fatiga del conductor'
      WHEN 'traffic_sign_recognition' THEN 'Reconocimiento de señales de tráfico'
      WHEN 'pedestrian_detection' THEN 'Detección de peatones'
      WHEN 'cyclist_detection' THEN 'Detección de ciclistas'
      WHEN 'collision_warning' THEN 'Alerta de colisión'
      WHEN 'hill_start_assist' THEN 'Asistente de arranque en pendiente'
      WHEN 'hill_descent_control' THEN 'Control de descenso en pendiente'
      WHEN 'adaptive_cruise_control' THEN 'Control de crucero adaptativo'
      WHEN 'cruise_control' THEN 'Control de crucero'
      WHEN 'speed_limiter' THEN 'Limitador de velocidad'
      WHEN 'parking_assist' THEN 'Asistente de aparcamiento'
      WHEN 'automatic_parking' THEN 'Aparcamiento automático'
      WHEN 'rear_view_camera' THEN 'Cámara trasera'
      WHEN 'surround_view_camera' THEN 'Cámara 360°'
      WHEN 'front_parking_sensors' THEN 'Sensores de aparcamiento delanteros'
      WHEN 'rear_parking_sensors' THEN 'Sensores de aparcamiento traseros'
      WHEN 'automatic_emergency_braking' THEN 'Frenado de emergencia automático'
      WHEN 'traffic_jam_assist' THEN 'Asistente de tráfico'
      WHEN 'keyless_entry' THEN 'Entrada sin llave'
      WHEN 'keyless_start' THEN 'Arranque sin llave'
      WHEN 'electric_tailgate' THEN 'Portón eléctrico'
      WHEN 'hands_free_tailgate' THEN 'Portón manos libres'
      WHEN 'remote_start' THEN 'Arranque remoto'
      WHEN 'heated_steering_wheel' THEN 'Volante calefactado'
      WHEN 'power_steering' THEN 'Dirección asistida'
      WHEN 'adjustable_steering_wheel' THEN 'Volante ajustable'
      WHEN 'ambient_lighting' THEN 'Iluminación ambiental'
      WHEN 'soft_close_doors' THEN 'Puertas de cierre suave'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Puertos USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Sistema de navegación'
      WHEN 'digital_radio' THEN 'Radio digital'
      WHEN 'wifi_hotspot' THEN 'Punto WiFi'
      WHEN 'voice_control' THEN 'Control por voz'
      WHEN 'touchscreen_display' THEN 'Pantalla táctil'
      WHEN 'rear_entertainment_system' THEN 'Sistema de entretenimiento trasero'
      WHEN 'leather_interior' THEN 'Interior de cuero'
      WHEN 'fabric_interior' THEN 'Interior de tela'
      WHEN 'alcantara_interior' THEN 'Interior Alcántara'
      WHEN 'carbon_fiber_trim' THEN 'Acabados en fibra de carbono'
      WHEN 'wood_trim' THEN 'Acabados en madera'
      WHEN 'adjustable_ambient_light' THEN 'Luz ambiental ajustable'
      WHEN 'multifunction_steering_wheel' THEN 'Volante multifunción'
      WHEN 'digital_dashboard' THEN 'Cuadro de mandos digital'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Cuadro de instrumentos configurable'
      WHEN 'alloy_wheels' THEN 'Llantas de aleación'
      WHEN 'steel_wheels' THEN 'Llantas de acero'
      WHEN 'roof_rails' THEN 'Barras de techo'
      WHEN 'panoramic_roof' THEN 'Techo panorámico'
      WHEN 'sunroof' THEN 'Techo solar'
      WHEN 'tinted_windows' THEN 'Cristales tintados'
      WHEN 'metallic_paint' THEN 'Pintura metalizada'
      WHEN 'pearlescent_paint' THEN 'Pintura perlada'
      WHEN 'tow_hook' THEN 'Gancho de remolque'
      WHEN 'electric_mirrors' THEN 'Espejos eléctricos'
      WHEN 'led_headlights' THEN 'Faros LED'
      WHEN 'xenon_headlights' THEN 'Faros de xenón'
      WHEN 'matrix_led' THEN 'LED matricial'
      WHEN 'adaptive_headlights' THEN 'Faros adaptativos'
      WHEN 'automatic_headlights' THEN 'Faros automáticos'
      WHEN 'daytime_running_lights' THEN 'Luces diurnas'
      WHEN 'fog_lights' THEN 'Luces antiniebla'
      WHEN 'cornering_lights' THEN 'Luces de giro'
      WHEN 'manual_air_conditioning' THEN 'Aire acondicionado manual'
      WHEN 'automatic_climate_control' THEN 'Climatizador automático'
      WHEN 'dual_zone_climate' THEN 'Climatizador bi-zona'
      WHEN 'tri_zone_climate' THEN 'Climatizador tri-zona'
      WHEN 'air_quality_sensor' THEN 'Sensor de calidad del aire'
      WHEN 'pollen_filter' THEN 'Filtro de polen'
      WHEN 'ventilated_seats_climate' THEN 'Asientos ventilados'
      WHEN 'heated_seats' THEN 'Asientos calefactados'
      WHEN 'ventilated_seats' THEN 'Asientos ventilados'
      WHEN 'electric_seats' THEN 'Asientos eléctricos'
      WHEN 'memory_seats' THEN 'Asientos con memoria'
      WHEN 'massage_seats' THEN 'Asientos con masaje'
      WHEN 'sport_seats' THEN 'Asientos deportivos'
      WHEN 'rear_adjustable_seats' THEN 'Asientos traseros ajustables'
      WHEN 'folding_rear_seats' THEN 'Asientos traseros abatibles'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Sistema de alarma'
      WHEN 'immobilizer' THEN 'Inmovilizador'
      WHEN 'anti_theft_system' THEN 'Sistema antirrobo'
      WHEN 'wheel_lock' THEN 'Bloqueo de ruedas'
      WHEN 'interior_monitoring' THEN 'Monitorización interior'
      WHEN 'gps_tracker' THEN 'Localizador GPS'
      WHEN 'drive_modes' THEN 'Modos de conducción'
      WHEN 'sport_mode' THEN 'Modo deportivo'
      WHEN 'eco_mode' THEN 'Modo ECO'
      WHEN 'all_wheel_drive' THEN 'Tracción total'
      WHEN 'differential_lock' THEN 'Bloqueo de diferencial'
      WHEN 'air_suspension' THEN 'Suspensión neumática'
      WHEN 'adaptive_suspension' THEN 'Suspensión adaptativa'
      WHEN 'sport_exhaust' THEN 'Escape deportivo'
      WHEN 'performance_brakes' THEN 'Frenos de alto rendimiento'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Frenado regenerativo'
      WHEN 'start_stop_system' THEN 'Sistema Start/Stop'
      WHEN 'spare_wheel' THEN 'Rueda de repuesto'
      WHEN 'tire_repair_kit' THEN 'Kit de reparación de neumáticos'
      WHEN 'onboard_computer' THEN 'Ordenador de a bordo'
      WHEN 'service_history' THEN 'Historial de servicio'
      WHEN 'warranty' THEN 'Garantía'
      WHEN 'battery_certificate' THEN 'Certificado de batería'
      WHEN 'inspection_report' THEN 'Informe de inspección'
      WHEN 'homologation_documents' THEN 'Documentos de homologación'
      ELSE r.key
    END);

    -- ENGLISH
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'en', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Traction Control'
      WHEN 'emergency_brake_assist' THEN 'Emergency Brake Assist'
      WHEN 'brake_assist' THEN 'Brake Assist'
      WHEN 'lane_departure_warning' THEN 'Lane Departure Warning'
      WHEN 'lane_keep_assist' THEN 'Lane Keep Assist'
      WHEN 'blind_spot_monitor' THEN 'Blind Spot Monitor'
      WHEN 'rear_cross_traffic_alert' THEN 'Rear Cross Traffic Alert'
      WHEN 'driver_fatigue_detection' THEN 'Driver Fatigue Detection'
      WHEN 'traffic_sign_recognition' THEN 'Traffic Sign Recognition'
      WHEN 'pedestrian_detection' THEN 'Pedestrian Detection'
      WHEN 'cyclist_detection' THEN 'Cyclist Detection'
      WHEN 'collision_warning' THEN 'Collision Warning'
      WHEN 'hill_start_assist' THEN 'Hill Start Assist'
      WHEN 'hill_descent_control' THEN 'Hill Descent Control'
      WHEN 'adaptive_cruise_control' THEN 'Adaptive Cruise Control'
      WHEN 'cruise_control' THEN 'Cruise Control'
      WHEN 'speed_limiter' THEN 'Speed Limiter'
      WHEN 'parking_assist' THEN 'Parking Assist'
      WHEN 'automatic_parking' THEN 'Automatic Parking'
      WHEN 'rear_view_camera' THEN 'Rear View Camera'
      WHEN 'surround_view_camera' THEN 'Surround View Camera'
      WHEN 'front_parking_sensors' THEN 'Front Parking Sensors'
      WHEN 'rear_parking_sensors' THEN 'Rear Parking Sensors'
      WHEN 'automatic_emergency_braking' THEN 'Automatic Emergency Braking'
      WHEN 'traffic_jam_assist' THEN 'Traffic Jam Assist'
      WHEN 'keyless_entry' THEN 'Keyless Entry'
      WHEN 'keyless_start' THEN 'Keyless Start'
      WHEN 'electric_tailgate' THEN 'Electric Tailgate'
      WHEN 'hands_free_tailgate' THEN 'Hands-Free Tailgate'
      WHEN 'remote_start' THEN 'Remote Start'
      WHEN 'heated_steering_wheel' THEN 'Heated Steering Wheel'
      WHEN 'power_steering' THEN 'Power Steering'
      WHEN 'adjustable_steering_wheel' THEN 'Adjustable Steering Wheel'
      WHEN 'ambient_lighting' THEN 'Ambient Lighting'
      WHEN 'soft_close_doors' THEN 'Soft Close Doors'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'USB Ports'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Navigation System'
      WHEN 'digital_radio' THEN 'Digital Radio'
      WHEN 'wifi_hotspot' THEN 'WiFi Hotspot'
      WHEN 'voice_control' THEN 'Voice Control'
      WHEN 'touchscreen_display' THEN 'Touchscreen Display'
      WHEN 'rear_entertainment_system' THEN 'Rear Entertainment System'
      WHEN 'leather_interior' THEN 'Leather Interior'
      WHEN 'fabric_interior' THEN 'Fabric Interior'
      WHEN 'alcantara_interior' THEN 'Alcantara Interior'
      WHEN 'carbon_fiber_trim' THEN 'Carbon Fiber Trim'
      WHEN 'wood_trim' THEN 'Wood Trim'
      WHEN 'adjustable_ambient_light' THEN 'Adjustable Ambient Light'
      WHEN 'multifunction_steering_wheel' THEN 'Multifunction Steering Wheel'
      WHEN 'digital_dashboard' THEN 'Digital Dashboard'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Configurable Instrument Cluster'
      WHEN 'alloy_wheels' THEN 'Alloy Wheels'
      WHEN 'steel_wheels' THEN 'Steel Wheels'
      WHEN 'roof_rails' THEN 'Roof Rails'
      WHEN 'panoramic_roof' THEN 'Panoramic Roof'
      WHEN 'sunroof' THEN 'Sunroof'
      WHEN 'tinted_windows' THEN 'Tinted Windows'
      WHEN 'metallic_paint' THEN 'Metallic Paint'
      WHEN 'pearlescent_paint' THEN 'Pearlescent Paint'
      WHEN 'tow_hook' THEN 'Tow Hook'
      WHEN 'electric_mirrors' THEN 'Electric Mirrors'
      WHEN 'led_headlights' THEN 'LED Headlights'
      WHEN 'xenon_headlights' THEN 'Xenon Headlights'
      WHEN 'matrix_led' THEN 'Matrix LED'
      WHEN 'adaptive_headlights' THEN 'Adaptive Headlights'
      WHEN 'automatic_headlights' THEN 'Automatic Headlights'
      WHEN 'daytime_running_lights' THEN 'Daytime Running Lights'
      WHEN 'fog_lights' THEN 'Fog Lights'
      WHEN 'cornering_lights' THEN 'Cornering Lights'
      WHEN 'manual_air_conditioning' THEN 'Manual Air Conditioning'
      WHEN 'automatic_climate_control' THEN 'Automatic Climate Control'
      WHEN 'dual_zone_climate' THEN 'Dual Zone Climate'
      WHEN 'tri_zone_climate' THEN 'Tri-Zone Climate'
      WHEN 'air_quality_sensor' THEN 'Air Quality Sensor'
      WHEN 'pollen_filter' THEN 'Pollen Filter'
      WHEN 'ventilated_seats_climate' THEN 'Ventilated Seats'
      WHEN 'heated_seats' THEN 'Heated Seats'
      WHEN 'ventilated_seats' THEN 'Ventilated Seats'
      WHEN 'electric_seats' THEN 'Electric Seats'
      WHEN 'memory_seats' THEN 'Memory Seats'
      WHEN 'massage_seats' THEN 'Massage Seats'
      WHEN 'sport_seats' THEN 'Sport Seats'
      WHEN 'rear_adjustable_seats' THEN 'Rear Adjustable Seats'
      WHEN 'folding_rear_seats' THEN 'Folding Rear Seats'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Alarm System'
      WHEN 'immobilizer' THEN 'Immobilizer'
      WHEN 'anti_theft_system' THEN 'Anti-Theft System'
      WHEN 'wheel_lock' THEN 'Wheel Lock'
      WHEN 'interior_monitoring' THEN 'Interior Monitoring'
      WHEN 'gps_tracker' THEN 'GPS Tracker'
      WHEN 'drive_modes' THEN 'Drive Modes'
      WHEN 'sport_mode' THEN 'Sport Mode'
      WHEN 'eco_mode' THEN 'Eco Mode'
      WHEN 'all_wheel_drive' THEN 'All-Wheel Drive'
      WHEN 'differential_lock' THEN 'Differential Lock'
      WHEN 'air_suspension' THEN 'Air Suspension'
      WHEN 'adaptive_suspension' THEN 'Adaptive Suspension'
      WHEN 'sport_exhaust' THEN 'Sport Exhaust'
      WHEN 'performance_brakes' THEN 'Performance Brakes'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Regenerative Braking'
      WHEN 'start_stop_system' THEN 'Start/Stop System'
      WHEN 'spare_wheel' THEN 'Spare Wheel'
      WHEN 'tire_repair_kit' THEN 'Tire Repair Kit'
      WHEN 'onboard_computer' THEN 'Onboard Computer'
      WHEN 'service_history' THEN 'Service History'
      WHEN 'warranty' THEN 'Warranty'
      WHEN 'battery_certificate' THEN 'Battery Certificate'
      WHEN 'inspection_report' THEN 'Inspection Report'
      WHEN 'homologation_documents' THEN 'Homologation Documents'
      ELSE r.key
    END);

    -- FRENCH
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'fr', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Contrôle de traction'
      WHEN 'emergency_brake_assist' THEN 'Aide au freinage d''urgence'
      WHEN 'brake_assist' THEN 'Aide au freinage'
      WHEN 'lane_departure_warning' THEN 'Alerte de franchissement de ligne'
      WHEN 'lane_keep_assist' THEN 'Aide au maintien de voie'
      WHEN 'blind_spot_monitor' THEN 'Surveillance d''angle mort'
      WHEN 'rear_cross_traffic_alert' THEN 'Alerte de trafic transversal arrière'
      WHEN 'driver_fatigue_detection' THEN 'Détection de fatigue du conducteur'
      WHEN 'traffic_sign_recognition' THEN 'Reconnaissance des panneaux'
      WHEN 'pedestrian_detection' THEN 'Détection de piétons'
      WHEN 'cyclist_detection' THEN 'Détection de cyclistes'
      WHEN 'collision_warning' THEN 'Alerte de collision'
      WHEN 'hill_start_assist' THEN 'Aide au démarrage en côte'
      WHEN 'hill_descent_control' THEN 'Contrôle de descente'
      WHEN 'adaptive_cruise_control' THEN 'Régulateur adaptatif'
      WHEN 'cruise_control' THEN 'Régulateur de vitesse'
      WHEN 'speed_limiter' THEN 'Limiteur de vitesse'
      WHEN 'parking_assist' THEN 'Aide au stationnement'
      WHEN 'automatic_parking' THEN 'Stationnement automatique'
      WHEN 'rear_view_camera' THEN 'Caméra de recul'
      WHEN 'surround_view_camera' THEN 'Caméra 360°'
      WHEN 'front_parking_sensors' THEN 'Capteurs de stationnement avant'
      WHEN 'rear_parking_sensors' THEN 'Capteurs de stationnement arrière'
      WHEN 'automatic_emergency_braking' THEN 'Freinage d''urgence automatique'
      WHEN 'traffic_jam_assist' THEN 'Assistant embouteillage'
      WHEN 'keyless_entry' THEN 'Accès sans clé'
      WHEN 'keyless_start' THEN 'Démarrage sans clé'
      WHEN 'electric_tailgate' THEN 'Hayon électrique'
      WHEN 'hands_free_tailgate' THEN 'Hayon mains libres'
      WHEN 'remote_start' THEN 'Démarrage à distance'
      WHEN 'heated_steering_wheel' THEN 'Volant chauffant'
      WHEN 'power_steering' THEN 'Direction assistée'
      WHEN 'adjustable_steering_wheel' THEN 'Volant réglable'
      WHEN 'ambient_lighting' THEN 'Éclairage d''ambiance'
      WHEN 'soft_close_doors' THEN 'Portes à fermeture douce'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Ports USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Système de navigation'
      WHEN 'digital_radio' THEN 'Radio numérique'
      WHEN 'wifi_hotspot' THEN 'Point d''accès WiFi'
      WHEN 'voice_control' THEN 'Commande vocale'
      WHEN 'touchscreen_display' THEN 'Écran tactile'
      WHEN 'rear_entertainment_system' THEN 'Système de divertissement arrière'
      WHEN 'leather_interior' THEN 'Intérieur cuir'
      WHEN 'fabric_interior' THEN 'Intérieur tissu'
      WHEN 'alcantara_interior' THEN 'Intérieur Alcantara'
      WHEN 'carbon_fiber_trim' THEN 'Finitions fibre de carbone'
      WHEN 'wood_trim' THEN 'Finitions bois'
      WHEN 'adjustable_ambient_light' THEN 'Éclairage ambiant réglable'
      WHEN 'multifunction_steering_wheel' THEN 'Volant multifonction'
      WHEN 'digital_dashboard' THEN 'Tableau de bord numérique'
      WHEN 'head_up_display' THEN 'Affichage tête haute'
      WHEN 'configurable_instrument_cluster' THEN 'Combiné d''instruments configurable'
      WHEN 'alloy_wheels' THEN 'Jantes en alliage'
      WHEN 'steel_wheels' THEN 'Jantes en acier'
      WHEN 'roof_rails' THEN 'Barres de toit'
      WHEN 'panoramic_roof' THEN 'Toit panoramique'
      WHEN 'sunroof' THEN 'Toit ouvrant'
      WHEN 'tinted_windows' THEN 'Vitres teintées'
      WHEN 'metallic_paint' THEN 'Peinture métallisée'
      WHEN 'pearlescent_paint' THEN 'Peinture nacrée'
      WHEN 'tow_hook' THEN 'Crochet d''attelage'
      WHEN 'electric_mirrors' THEN 'Rétroviseurs électriques'
      WHEN 'led_headlights' THEN 'Phares LED'
      WHEN 'xenon_headlights' THEN 'Phares xénon'
      WHEN 'matrix_led' THEN 'LED matriciel'
      WHEN 'adaptive_headlights' THEN 'Phares adaptatifs'
      WHEN 'automatic_headlights' THEN 'Phares automatiques'
      WHEN 'daytime_running_lights' THEN 'Feux de jour'
      WHEN 'fog_lights' THEN 'Feux antibrouillard'
      WHEN 'cornering_lights' THEN 'Feux de virage'
      WHEN 'manual_air_conditioning' THEN 'Climatisation manuelle'
      WHEN 'automatic_climate_control' THEN 'Climatisation automatique'
      WHEN 'dual_zone_climate' THEN 'Climatisation bi-zone'
      WHEN 'tri_zone_climate' THEN 'Climatisation tri-zone'
      WHEN 'air_quality_sensor' THEN 'Capteur de qualité d''air'
      WHEN 'pollen_filter' THEN 'Filtre à pollen'
      WHEN 'ventilated_seats_climate' THEN 'Sièges ventilés'
      WHEN 'heated_seats' THEN 'Sièges chauffants'
      WHEN 'ventilated_seats' THEN 'Sièges ventilés'
      WHEN 'electric_seats' THEN 'Sièges électriques'
      WHEN 'memory_seats' THEN 'Sièges à mémoire'
      WHEN 'massage_seats' THEN 'Sièges massants'
      WHEN 'sport_seats' THEN 'Sièges sport'
      WHEN 'rear_adjustable_seats' THEN 'Sièges arrière réglables'
      WHEN 'folding_rear_seats' THEN 'Sièges arrière rabattables'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Système d''alarme'
      WHEN 'immobilizer' THEN 'Immobiliseur'
      WHEN 'anti_theft_system' THEN 'Système antivol'
      WHEN 'wheel_lock' THEN 'Antivol de roues'
      WHEN 'interior_monitoring' THEN 'Surveillance intérieure'
      WHEN 'gps_tracker' THEN 'Traceur GPS'
      WHEN 'drive_modes' THEN 'Modes de conduite'
      WHEN 'sport_mode' THEN 'Mode sport'
      WHEN 'eco_mode' THEN 'Mode ECO'
      WHEN 'all_wheel_drive' THEN 'Transmission intégrale'
      WHEN 'differential_lock' THEN 'Blocage de différentiel'
      WHEN 'air_suspension' THEN 'Suspension pneumatique'
      WHEN 'adaptive_suspension' THEN 'Suspension adaptative'
      WHEN 'sport_exhaust' THEN 'Échappement sport'
      WHEN 'performance_brakes' THEN 'Freins haute performance'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Freinage régénératif'
      WHEN 'start_stop_system' THEN 'Système Start/Stop'
      WHEN 'spare_wheel' THEN 'Roue de secours'
      WHEN 'tire_repair_kit' THEN 'Kit de réparation de pneus'
      WHEN 'onboard_computer' THEN 'Ordinateur de bord'
      WHEN 'service_history' THEN 'Historique d''entretien'
      WHEN 'warranty' THEN 'Garantie'
      WHEN 'battery_certificate' THEN 'Certificat de batterie'
      WHEN 'inspection_report' THEN 'Rapport d''inspection'
      WHEN 'homologation_documents' THEN 'Documents d''homologation'
      ELSE r.key
    END);

    -- GERMAN
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'de', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Traktionskontrolle'
      WHEN 'emergency_brake_assist' THEN 'Notbremsassistent'
      WHEN 'brake_assist' THEN 'Bremsassistent'
      WHEN 'lane_departure_warning' THEN 'Spurverlassenswarnung'
      WHEN 'lane_keep_assist' THEN 'Spurhalteassistent'
      WHEN 'blind_spot_monitor' THEN 'Totwinkelüberwachung'
      WHEN 'rear_cross_traffic_alert' THEN 'Querverkehrswarnung hinten'
      WHEN 'driver_fatigue_detection' THEN 'Müdigkeitserkennung'
      WHEN 'traffic_sign_recognition' THEN 'Verkehrszeichenerkennung'
      WHEN 'pedestrian_detection' THEN 'Fußgängererkennung'
      WHEN 'cyclist_detection' THEN 'Radfahrererkennung'
      WHEN 'collision_warning' THEN 'Kollisionswarnung'
      WHEN 'hill_start_assist' THEN 'Berganfahrhilfe'
      WHEN 'hill_descent_control' THEN 'Bergabfahrhilfe'
      WHEN 'adaptive_cruise_control' THEN 'Adaptiver Tempomat'
      WHEN 'cruise_control' THEN 'Tempomat'
      WHEN 'speed_limiter' THEN 'Geschwindigkeitsbegrenzer'
      WHEN 'parking_assist' THEN 'Parkassistent'
      WHEN 'automatic_parking' THEN 'Automatisches Einparken'
      WHEN 'rear_view_camera' THEN 'Rückfahrkamera'
      WHEN 'surround_view_camera' THEN '360°-Kamera'
      WHEN 'front_parking_sensors' THEN 'Parksensoren vorne'
      WHEN 'rear_parking_sensors' THEN 'Parksensoren hinten'
      WHEN 'automatic_emergency_braking' THEN 'Automatische Notbremsung'
      WHEN 'traffic_jam_assist' THEN 'Stauassistent'
      WHEN 'keyless_entry' THEN 'Schlüsselloser Zugang'
      WHEN 'keyless_start' THEN 'Schlüsselloser Start'
      WHEN 'electric_tailgate' THEN 'Elektrische Heckklappe'
      WHEN 'hands_free_tailgate' THEN 'Sensorgesteuerte Heckklappe'
      WHEN 'remote_start' THEN 'Fernstart'
      WHEN 'heated_steering_wheel' THEN 'Beheiztes Lenkrad'
      WHEN 'power_steering' THEN 'Servolenkung'
      WHEN 'adjustable_steering_wheel' THEN 'Verstellbares Lenkrad'
      WHEN 'ambient_lighting' THEN 'Ambientebeleuchtung'
      WHEN 'soft_close_doors' THEN 'Sanft schließende Türen'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'USB-Anschlüsse'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Navigationssystem'
      WHEN 'digital_radio' THEN 'Digitalradio'
      WHEN 'wifi_hotspot' THEN 'WLAN-Hotspot'
      WHEN 'voice_control' THEN 'Sprachsteuerung'
      WHEN 'touchscreen_display' THEN 'Touchscreen-Display'
      WHEN 'rear_entertainment_system' THEN 'Fond-Entertainment-System'
      WHEN 'leather_interior' THEN 'Lederausstattung'
      WHEN 'fabric_interior' THEN 'Stoffausstattung'
      WHEN 'alcantara_interior' THEN 'Alcantara-Ausstattung'
      WHEN 'carbon_fiber_trim' THEN 'Carbonzierteile'
      WHEN 'wood_trim' THEN 'Holzzierteile'
      WHEN 'adjustable_ambient_light' THEN 'Einstellbare Ambientebeleuchtung'
      WHEN 'multifunction_steering_wheel' THEN 'Multifunktionslenkrad'
      WHEN 'digital_dashboard' THEN 'Digitales Cockpit'
      WHEN 'head_up_display' THEN 'Head-Up-Display'
      WHEN 'configurable_instrument_cluster' THEN 'Konfigurierbares Kombiinstrument'
      WHEN 'alloy_wheels' THEN 'Leichtmetallräder'
      WHEN 'steel_wheels' THEN 'Stahlräder'
      WHEN 'roof_rails' THEN 'Dachreling'
      WHEN 'panoramic_roof' THEN 'Panoramadach'
      WHEN 'sunroof' THEN 'Schiebedach'
      WHEN 'tinted_windows' THEN 'Getönte Scheiben'
      WHEN 'metallic_paint' THEN 'Metallic-Lackierung'
      WHEN 'pearlescent_paint' THEN 'Perleffekt-Lackierung'
      WHEN 'tow_hook' THEN 'Anhängerkupplung'
      WHEN 'electric_mirrors' THEN 'Elektrische Außenspiegel'
      WHEN 'led_headlights' THEN 'LED-Scheinwerfer'
      WHEN 'xenon_headlights' THEN 'Xenon-Scheinwerfer'
      WHEN 'matrix_led' THEN 'Matrix-LED'
      WHEN 'adaptive_headlights' THEN 'Adaptive Scheinwerfer'
      WHEN 'automatic_headlights' THEN 'Automatisches Fahrlicht'
      WHEN 'daytime_running_lights' THEN 'Tagfahrlicht'
      WHEN 'fog_lights' THEN 'Nebelscheinwerfer'
      WHEN 'cornering_lights' THEN 'Abbiegelicht'
      WHEN 'manual_air_conditioning' THEN 'Manuelle Klimaanlage'
      WHEN 'automatic_climate_control' THEN 'Automatische Klimaanlage'
      WHEN 'dual_zone_climate' THEN 'Zweizonen-Klimaautomatik'
      WHEN 'tri_zone_climate' THEN 'Dreizonen-Klimaautomatik'
      WHEN 'air_quality_sensor' THEN 'Luftqualitätssensor'
      WHEN 'pollen_filter' THEN 'Pollenfilter'
      WHEN 'ventilated_seats_climate' THEN 'Belüftete Sitze'
      WHEN 'heated_seats' THEN 'Sitzheizung'
      WHEN 'ventilated_seats' THEN 'Belüftete Sitze'
      WHEN 'electric_seats' THEN 'Elektrische Sitze'
      WHEN 'memory_seats' THEN 'Sitze mit Memory'
      WHEN 'massage_seats' THEN 'Massagesitze'
      WHEN 'sport_seats' THEN 'Sportsitze'
      WHEN 'rear_adjustable_seats' THEN 'Verstellbare Rücksitze'
      WHEN 'folding_rear_seats' THEN 'Umklappbare Rücksitze'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Alarmanlage'
      WHEN 'immobilizer' THEN 'Wegfahrsperre'
      WHEN 'anti_theft_system' THEN 'Diebstahlschutzsystem'
      WHEN 'wheel_lock' THEN 'Felgenschlösser'
      WHEN 'interior_monitoring' THEN 'Innenraumüberwachung'
      WHEN 'gps_tracker' THEN 'GPS-Tracker'
      WHEN 'drive_modes' THEN 'Fahrmodi'
      WHEN 'sport_mode' THEN 'Sportmodus'
      WHEN 'eco_mode' THEN 'ECO-Modus'
      WHEN 'all_wheel_drive' THEN 'Allradantrieb'
      WHEN 'differential_lock' THEN 'Differentialsperre'
      WHEN 'air_suspension' THEN 'Luftfederung'
      WHEN 'adaptive_suspension' THEN 'Adaptives Fahrwerk'
      WHEN 'sport_exhaust' THEN 'Sportauspuff'
      WHEN 'performance_brakes' THEN 'Hochleistungsbremsen'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Rekuperationsbremse'
      WHEN 'start_stop_system' THEN 'Start/Stopp-System'
      WHEN 'spare_wheel' THEN 'Reserverad'
      WHEN 'tire_repair_kit' THEN 'Reifenreparaturset'
      WHEN 'onboard_computer' THEN 'Bordcomputer'
      WHEN 'service_history' THEN 'Servicehistorie'
      WHEN 'warranty' THEN 'Garantie'
      WHEN 'battery_certificate' THEN 'Batteriezertifikat'
      WHEN 'inspection_report' THEN 'Inspektionsbericht'
      WHEN 'homologation_documents' THEN 'Homologationsdokumente'
      ELSE r.key
    END);

    -- ITALIAN
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'it', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Controllo di trazione'
      WHEN 'emergency_brake_assist' THEN 'Assistenza frenata di emergenza'
      WHEN 'brake_assist' THEN 'Assistenza alla frenata'
      WHEN 'lane_departure_warning' THEN 'Avviso cambio corsia'
      WHEN 'lane_keep_assist' THEN 'Assistente mantenimento corsia'
      WHEN 'blind_spot_monitor' THEN 'Monitoraggio angolo cieco'
      WHEN 'rear_cross_traffic_alert' THEN 'Avviso traffico trasversale posteriore'
      WHEN 'driver_fatigue_detection' THEN 'Rilevamento stanchezza conducente'
      WHEN 'traffic_sign_recognition' THEN 'Riconoscimento segnali stradali'
      WHEN 'pedestrian_detection' THEN 'Rilevamento pedoni'
      WHEN 'cyclist_detection' THEN 'Rilevamento ciclisti'
      WHEN 'collision_warning' THEN 'Avviso collisione'
      WHEN 'hill_start_assist' THEN 'Assistente partenza in salita'
      WHEN 'hill_descent_control' THEN 'Controllo discesa'
      WHEN 'adaptive_cruise_control' THEN 'Cruise control adattivo'
      WHEN 'cruise_control' THEN 'Cruise control'
      WHEN 'speed_limiter' THEN 'Limitatore di velocità'
      WHEN 'parking_assist' THEN 'Assistente al parcheggio'
      WHEN 'automatic_parking' THEN 'Parcheggio automatico'
      WHEN 'rear_view_camera' THEN 'Telecamera posteriore'
      WHEN 'surround_view_camera' THEN 'Telecamera 360°'
      WHEN 'front_parking_sensors' THEN 'Sensori parcheggio anteriori'
      WHEN 'rear_parking_sensors' THEN 'Sensori parcheggio posteriori'
      WHEN 'automatic_emergency_braking' THEN 'Frenata di emergenza automatica'
      WHEN 'traffic_jam_assist' THEN 'Assistente traffico'
      WHEN 'keyless_entry' THEN 'Accesso senza chiave'
      WHEN 'keyless_start' THEN 'Avviamento senza chiave'
      WHEN 'electric_tailgate' THEN 'Portellone elettrico'
      WHEN 'hands_free_tailgate' THEN 'Portellone a mani libere'
      WHEN 'remote_start' THEN 'Avviamento remoto'
      WHEN 'heated_steering_wheel' THEN 'Volante riscaldato'
      WHEN 'power_steering' THEN 'Servosterzo'
      WHEN 'adjustable_steering_wheel' THEN 'Volante regolabile'
      WHEN 'ambient_lighting' THEN 'Illuminazione ambientale'
      WHEN 'soft_close_doors' THEN 'Porte a chiusura soft'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Porte USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Sistema di navigazione'
      WHEN 'digital_radio' THEN 'Radio digitale'
      WHEN 'wifi_hotspot' THEN 'Hotspot WiFi'
      WHEN 'voice_control' THEN 'Controllo vocale'
      WHEN 'touchscreen_display' THEN 'Display touchscreen'
      WHEN 'rear_entertainment_system' THEN 'Sistema intrattenimento posteriore'
      WHEN 'leather_interior' THEN 'Interni in pelle'
      WHEN 'fabric_interior' THEN 'Interni in tessuto'
      WHEN 'alcantara_interior' THEN 'Interni in Alcantara'
      WHEN 'carbon_fiber_trim' THEN 'Finiture in fibra di carbonio'
      WHEN 'wood_trim' THEN 'Finiture in legno'
      WHEN 'adjustable_ambient_light' THEN 'Luce ambientale regolabile'
      WHEN 'multifunction_steering_wheel' THEN 'Volante multifunzione'
      WHEN 'digital_dashboard' THEN 'Cruscotto digitale'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Quadro strumenti configurabile'
      WHEN 'alloy_wheels' THEN 'Cerchi in lega'
      WHEN 'steel_wheels' THEN 'Cerchi in acciaio'
      WHEN 'roof_rails' THEN 'Barre portapacchi'
      WHEN 'panoramic_roof' THEN 'Tetto panoramico'
      WHEN 'sunroof' THEN 'Tetto apribile'
      WHEN 'tinted_windows' THEN 'Vetri oscurati'
      WHEN 'metallic_paint' THEN 'Vernice metallizzata'
      WHEN 'pearlescent_paint' THEN 'Vernice perlata'
      WHEN 'tow_hook' THEN 'Gancio traino'
      WHEN 'electric_mirrors' THEN 'Specchietti elettrici'
      WHEN 'led_headlights' THEN 'Fari LED'
      WHEN 'xenon_headlights' THEN 'Fari allo xeno'
      WHEN 'matrix_led' THEN 'LED Matrix'
      WHEN 'adaptive_headlights' THEN 'Fari adattivi'
      WHEN 'automatic_headlights' THEN 'Fari automatici'
      WHEN 'daytime_running_lights' THEN 'Luci diurne'
      WHEN 'fog_lights' THEN 'Fendinebbia'
      WHEN 'cornering_lights' THEN 'Luci di svolta'
      WHEN 'manual_air_conditioning' THEN 'Climatizzazione manuale'
      WHEN 'automatic_climate_control' THEN 'Climatizzazione automatica'
      WHEN 'dual_zone_climate' THEN 'Climatizzazione bi-zona'
      WHEN 'tri_zone_climate' THEN 'Climatizzazione tri-zona'
      WHEN 'air_quality_sensor' THEN 'Sensore qualità dell''aria'
      WHEN 'pollen_filter' THEN 'Filtro antipolline'
      WHEN 'ventilated_seats_climate' THEN 'Sedili ventilati'
      WHEN 'heated_seats' THEN 'Sedili riscaldati'
      WHEN 'ventilated_seats' THEN 'Sedili ventilati'
      WHEN 'electric_seats' THEN 'Sedili elettrici'
      WHEN 'memory_seats' THEN 'Sedili con memoria'
      WHEN 'massage_seats' THEN 'Sedili con massaggio'
      WHEN 'sport_seats' THEN 'Sedili sportivi'
      WHEN 'rear_adjustable_seats' THEN 'Sedili posteriori regolabili'
      WHEN 'folding_rear_seats' THEN 'Sedili posteriori abbattibili'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Sistema di allarme'
      WHEN 'immobilizer' THEN 'Immobilizzatore'
      WHEN 'anti_theft_system' THEN 'Sistema antifurto'
      WHEN 'wheel_lock' THEN 'Bloccaruote'
      WHEN 'interior_monitoring' THEN 'Monitoraggio interno'
      WHEN 'gps_tracker' THEN 'Localizzatore GPS'
      WHEN 'drive_modes' THEN 'Modalità di guida'
      WHEN 'sport_mode' THEN 'Modalità sport'
      WHEN 'eco_mode' THEN 'Modalità ECO'
      WHEN 'all_wheel_drive' THEN 'Trazione integrale'
      WHEN 'differential_lock' THEN 'Blocco differenziale'
      WHEN 'air_suspension' THEN 'Sospensioni pneumatiche'
      WHEN 'adaptive_suspension' THEN 'Sospensioni adattive'
      WHEN 'sport_exhaust' THEN 'Scarico sportivo'
      WHEN 'performance_brakes' THEN 'Freni ad alte prestazioni'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Frenata rigenerativa'
      WHEN 'start_stop_system' THEN 'Sistema Start/Stop'
      WHEN 'spare_wheel' THEN 'Ruota di scorta'
      WHEN 'tire_repair_kit' THEN 'Kit riparazione pneumatici'
      WHEN 'onboard_computer' THEN 'Computer di bordo'
      WHEN 'service_history' THEN 'Storico tagliandi'
      WHEN 'warranty' THEN 'Garanzia'
      WHEN 'battery_certificate' THEN 'Certificato batteria'
      WHEN 'inspection_report' THEN 'Rapporto di ispezione'
      WHEN 'homologation_documents' THEN 'Documenti di omologazione'
      ELSE r.key
    END);

    -- PORTUGUESE
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'pt', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Controlo de tração'
      WHEN 'emergency_brake_assist' THEN 'Assistência de travagem de emergência'
      WHEN 'brake_assist' THEN 'Assistência à travagem'
      WHEN 'lane_departure_warning' THEN 'Aviso de mudança de faixa'
      WHEN 'lane_keep_assist' THEN 'Assistente de manutenção de faixa'
      WHEN 'blind_spot_monitor' THEN 'Monitor de ângulo morto'
      WHEN 'rear_cross_traffic_alert' THEN 'Alerta de tráfego traseiro cruzado'
      WHEN 'driver_fatigue_detection' THEN 'Deteção de fadiga do condutor'
      WHEN 'traffic_sign_recognition' THEN 'Reconhecimento de sinais de trânsito'
      WHEN 'pedestrian_detection' THEN 'Deteção de peões'
      WHEN 'cyclist_detection' THEN 'Deteção de ciclistas'
      WHEN 'collision_warning' THEN 'Aviso de colisão'
      WHEN 'hill_start_assist' THEN 'Assistente de arranque em subida'
      WHEN 'hill_descent_control' THEN 'Controlo de descida'
      WHEN 'adaptive_cruise_control' THEN 'Cruise control adaptativo'
      WHEN 'cruise_control' THEN 'Cruise control'
      WHEN 'speed_limiter' THEN 'Limitador de velocidade'
      WHEN 'parking_assist' THEN 'Assistente de estacionamento'
      WHEN 'automatic_parking' THEN 'Estacionamento automático'
      WHEN 'rear_view_camera' THEN 'Câmara traseira'
      WHEN 'surround_view_camera' THEN 'Câmara 360°'
      WHEN 'front_parking_sensors' THEN 'Sensores de estacionamento dianteiros'
      WHEN 'rear_parking_sensors' THEN 'Sensores de estacionamento traseiros'
      WHEN 'automatic_emergency_braking' THEN 'Travagem de emergência automática'
      WHEN 'traffic_jam_assist' THEN 'Assistente de trânsito'
      WHEN 'keyless_entry' THEN 'Entrada sem chave'
      WHEN 'keyless_start' THEN 'Arranque sem chave'
      WHEN 'electric_tailgate' THEN 'Porta-bagagens elétrica'
      WHEN 'hands_free_tailgate' THEN 'Porta-bagagens mãos livres'
      WHEN 'remote_start' THEN 'Arranque remoto'
      WHEN 'heated_steering_wheel' THEN 'Volante aquecido'
      WHEN 'power_steering' THEN 'Direção assistida'
      WHEN 'adjustable_steering_wheel' THEN 'Volante ajustável'
      WHEN 'ambient_lighting' THEN 'Iluminação ambiente'
      WHEN 'soft_close_doors' THEN 'Portas de fecho suave'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Portas USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Sistema de navegação'
      WHEN 'digital_radio' THEN 'Rádio digital'
      WHEN 'wifi_hotspot' THEN 'Hotspot WiFi'
      WHEN 'voice_control' THEN 'Controlo por voz'
      WHEN 'touchscreen_display' THEN 'Ecrã tátil'
      WHEN 'rear_entertainment_system' THEN 'Sistema de entretenimento traseiro'
      WHEN 'leather_interior' THEN 'Interior em couro'
      WHEN 'fabric_interior' THEN 'Interior em tecido'
      WHEN 'alcantara_interior' THEN 'Interior em Alcantara'
      WHEN 'carbon_fiber_trim' THEN 'Acabamentos em fibra de carbono'
      WHEN 'wood_trim' THEN 'Acabamentos em madeira'
      WHEN 'adjustable_ambient_light' THEN 'Luz ambiente ajustável'
      WHEN 'multifunction_steering_wheel' THEN 'Volante multifunções'
      WHEN 'digital_dashboard' THEN 'Painel digital'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Painel de instrumentos configurável'
      WHEN 'alloy_wheels' THEN 'Jantes de liga leve'
      WHEN 'steel_wheels' THEN 'Jantes de aço'
      WHEN 'roof_rails' THEN 'Barras de tejadilho'
      WHEN 'panoramic_roof' THEN 'Teto panorâmico'
      WHEN 'sunroof' THEN 'Teto de abrir'
      WHEN 'tinted_windows' THEN 'Vidros escurecidos'
      WHEN 'metallic_paint' THEN 'Pintura metalizada'
      WHEN 'pearlescent_paint' THEN 'Pintura perolizada'
      WHEN 'tow_hook' THEN 'Gancho de reboque'
      WHEN 'electric_mirrors' THEN 'Espelhos elétricos'
      WHEN 'led_headlights' THEN 'Faróis LED'
      WHEN 'xenon_headlights' THEN 'Faróis de xénon'
      WHEN 'matrix_led' THEN 'LED matricial'
      WHEN 'adaptive_headlights' THEN 'Faróis adaptativos'
      WHEN 'automatic_headlights' THEN 'Faróis automáticos'
      WHEN 'daytime_running_lights' THEN 'Luzes diurnas'
      WHEN 'fog_lights' THEN 'Faróis de nevoeiro'
      WHEN 'cornering_lights' THEN 'Luzes de curva'
      WHEN 'manual_air_conditioning' THEN 'Ar condicionado manual'
      WHEN 'automatic_climate_control' THEN 'Climatização automática'
      WHEN 'dual_zone_climate' THEN 'Climatização bi-zona'
      WHEN 'tri_zone_climate' THEN 'Climatização tri-zona'
      WHEN 'air_quality_sensor' THEN 'Sensor de qualidade do ar'
      WHEN 'pollen_filter' THEN 'Filtro de pólen'
      WHEN 'ventilated_seats_climate' THEN 'Bancos ventilados'
      WHEN 'heated_seats' THEN 'Bancos aquecidos'
      WHEN 'ventilated_seats' THEN 'Bancos ventilados'
      WHEN 'electric_seats' THEN 'Bancos elétricos'
      WHEN 'memory_seats' THEN 'Bancos com memória'
      WHEN 'massage_seats' THEN 'Bancos com massagem'
      WHEN 'sport_seats' THEN 'Bancos desportivos'
      WHEN 'rear_adjustable_seats' THEN 'Bancos traseiros ajustáveis'
      WHEN 'folding_rear_seats' THEN 'Bancos traseiros rebatíveis'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Sistema de alarme'
      WHEN 'immobilizer' THEN 'Imobilizador'
      WHEN 'anti_theft_system' THEN 'Sistema anti-roubo'
      WHEN 'wheel_lock' THEN 'Bloqueio de rodas'
      WHEN 'interior_monitoring' THEN 'Monitorização interior'
      WHEN 'gps_tracker' THEN 'Localizador GPS'
      WHEN 'drive_modes' THEN 'Modos de condução'
      WHEN 'sport_mode' THEN 'Modo desportivo'
      WHEN 'eco_mode' THEN 'Modo ECO'
      WHEN 'all_wheel_drive' THEN 'Tração integral'
      WHEN 'differential_lock' THEN 'Bloqueio de diferencial'
      WHEN 'air_suspension' THEN 'Suspensão pneumática'
      WHEN 'adaptive_suspension' THEN 'Suspensão adaptativa'
      WHEN 'sport_exhaust' THEN 'Escape desportivo'
      WHEN 'performance_brakes' THEN 'Travões de alto desempenho'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Travagem regenerativa'
      WHEN 'start_stop_system' THEN 'Sistema Start/Stop'
      WHEN 'spare_wheel' THEN 'Roda suplente'
      WHEN 'tire_repair_kit' THEN 'Kit de reparação de pneus'
      WHEN 'onboard_computer' THEN 'Computador de bordo'
      WHEN 'service_history' THEN 'Histórico de manutenção'
      WHEN 'warranty' THEN 'Garantia'
      WHEN 'battery_certificate' THEN 'Certificado de bateria'
      WHEN 'inspection_report' THEN 'Relatório de inspeção'
      WHEN 'homologation_documents' THEN 'Documentos de homologação'
      ELSE r.key
    END);

    -- DUTCH
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'nl', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Tractiecontrole'
      WHEN 'emergency_brake_assist' THEN 'Noodremassistent'
      WHEN 'brake_assist' THEN 'Remassistent'
      WHEN 'lane_departure_warning' THEN 'Rijstrookassistent'
      WHEN 'lane_keep_assist' THEN 'Rijstrookbehoud'
      WHEN 'blind_spot_monitor' THEN 'Dodehoekbewaking'
      WHEN 'rear_cross_traffic_alert' THEN 'Achter dwarsverkeer waarschuwing'
      WHEN 'driver_fatigue_detection' THEN 'Vermoeidheidsherkenning'
      WHEN 'traffic_sign_recognition' THEN 'Verkeersbordherkenning'
      WHEN 'pedestrian_detection' THEN 'Voetgangersdetectie'
      WHEN 'cyclist_detection' THEN 'Fietsersdetectie'
      WHEN 'collision_warning' THEN 'Botsingswaarschuwing'
      WHEN 'hill_start_assist' THEN 'Heuvelhulp'
      WHEN 'hill_descent_control' THEN 'Bergafdalingscontrole'
      WHEN 'adaptive_cruise_control' THEN 'Adaptieve cruisecontrol'
      WHEN 'cruise_control' THEN 'Cruisecontrol'
      WHEN 'speed_limiter' THEN 'Snelheidsbegrenzer'
      WHEN 'parking_assist' THEN 'Parkeerassistent'
      WHEN 'automatic_parking' THEN 'Automatisch parkeren'
      WHEN 'rear_view_camera' THEN 'Achteruitrijcamera'
      WHEN 'surround_view_camera' THEN '360°-camera'
      WHEN 'front_parking_sensors' THEN 'Parkeersensoren voor'
      WHEN 'rear_parking_sensors' THEN 'Parkeersensoren achter'
      WHEN 'automatic_emergency_braking' THEN 'Automatisch noodremmen'
      WHEN 'traffic_jam_assist' THEN 'Fileassistent'
      WHEN 'keyless_entry' THEN 'Sleutelloze toegang'
      WHEN 'keyless_start' THEN 'Sleutelloze start'
      WHEN 'electric_tailgate' THEN 'Elektrische achterklep'
      WHEN 'hands_free_tailgate' THEN 'Handsfree achterklep'
      WHEN 'remote_start' THEN 'Starten op afstand'
      WHEN 'heated_steering_wheel' THEN 'Verwarmd stuurwiel'
      WHEN 'power_steering' THEN 'Stuurbekrachtiging'
      WHEN 'adjustable_steering_wheel' THEN 'Verstelbaar stuurwiel'
      WHEN 'ambient_lighting' THEN 'Sfeerverlichting'
      WHEN 'soft_close_doors' THEN 'Soft-close deuren'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'USB-poorten'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Navigatiesysteem'
      WHEN 'digital_radio' THEN 'Digitale radio'
      WHEN 'wifi_hotspot' THEN 'WiFi-hotspot'
      WHEN 'voice_control' THEN 'Spraakbesturing'
      WHEN 'touchscreen_display' THEN 'Touchscreen'
      WHEN 'rear_entertainment_system' THEN 'Entertainment achter'
      WHEN 'leather_interior' THEN 'Leren interieur'
      WHEN 'fabric_interior' THEN 'Stoffen interieur'
      WHEN 'alcantara_interior' THEN 'Alcantara interieur'
      WHEN 'carbon_fiber_trim' THEN 'Koolstofvezel afwerking'
      WHEN 'wood_trim' THEN 'Houten afwerking'
      WHEN 'adjustable_ambient_light' THEN 'Instelbare sfeerverlichting'
      WHEN 'multifunction_steering_wheel' THEN 'Multifunctioneel stuurwiel'
      WHEN 'digital_dashboard' THEN 'Digitaal dashboard'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Configureerbaar instrumentenpaneel'
      WHEN 'alloy_wheels' THEN 'Lichtmetalen velgen'
      WHEN 'steel_wheels' THEN 'Stalen velgen'
      WHEN 'roof_rails' THEN 'Dakrails'
      WHEN 'panoramic_roof' THEN 'Panoramadak'
      WHEN 'sunroof' THEN 'Schuifdak'
      WHEN 'tinted_windows' THEN 'Getinte ruiten'
      WHEN 'metallic_paint' THEN 'Metallic lak'
      WHEN 'pearlescent_paint' THEN 'Parelmoerlak'
      WHEN 'tow_hook' THEN 'Trekhaak'
      WHEN 'electric_mirrors' THEN 'Elektrische spiegels'
      WHEN 'led_headlights' THEN 'LED-koplampen'
      WHEN 'xenon_headlights' THEN 'Xenon-koplampen'
      WHEN 'matrix_led' THEN 'Matrix LED'
      WHEN 'adaptive_headlights' THEN 'Adaptieve koplampen'
      WHEN 'automatic_headlights' THEN 'Automatische koplampen'
      WHEN 'daytime_running_lights' THEN 'Dagrijverlichting'
      WHEN 'fog_lights' THEN 'Mistlampen'
      WHEN 'cornering_lights' THEN 'Bochtverlichting'
      WHEN 'manual_air_conditioning' THEN 'Handmatige airco'
      WHEN 'automatic_climate_control' THEN 'Automatische klimaatregeling'
      WHEN 'dual_zone_climate' THEN 'Tweezone klimaat'
      WHEN 'tri_zone_climate' THEN 'Driezone klimaat'
      WHEN 'air_quality_sensor' THEN 'Luchtkwaliteitssensor'
      WHEN 'pollen_filter' THEN 'Pollenfilter'
      WHEN 'ventilated_seats_climate' THEN 'Geventileerde stoelen'
      WHEN 'heated_seats' THEN 'Stoelverwarming'
      WHEN 'ventilated_seats' THEN 'Geventileerde stoelen'
      WHEN 'electric_seats' THEN 'Elektrische stoelen'
      WHEN 'memory_seats' THEN 'Stoelen met geheugen'
      WHEN 'massage_seats' THEN 'Massagestoelen'
      WHEN 'sport_seats' THEN 'Sportstoelen'
      WHEN 'rear_adjustable_seats' THEN 'Verstelbare achterstoelen'
      WHEN 'folding_rear_seats' THEN 'Neerklapbare achterstoelen'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Alarmsysteem'
      WHEN 'immobilizer' THEN 'Startonderbreker'
      WHEN 'anti_theft_system' THEN 'Anti-diefstalsysteem'
      WHEN 'wheel_lock' THEN 'Wielsloten'
      WHEN 'interior_monitoring' THEN 'Interieurdetectie'
      WHEN 'gps_tracker' THEN 'GPS-tracker'
      WHEN 'drive_modes' THEN 'Rijmodi'
      WHEN 'sport_mode' THEN 'Sportmodus'
      WHEN 'eco_mode' THEN 'ECO-modus'
      WHEN 'all_wheel_drive' THEN 'Vierwielaandrijving'
      WHEN 'differential_lock' THEN 'Differentieel slot'
      WHEN 'air_suspension' THEN 'Luchtvering'
      WHEN 'adaptive_suspension' THEN 'Adaptief onderstel'
      WHEN 'sport_exhaust' THEN 'Sportuitlaat'
      WHEN 'performance_brakes' THEN 'Prestatie-remmen'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Regeneratief remmen'
      WHEN 'start_stop_system' THEN 'Start/Stop-systeem'
      WHEN 'spare_wheel' THEN 'Reservewiel'
      WHEN 'tire_repair_kit' THEN 'Bandenreparatieset'
      WHEN 'onboard_computer' THEN 'Boordcomputer'
      WHEN 'service_history' THEN 'Onderhoudshistorie'
      WHEN 'warranty' THEN 'Garantie'
      WHEN 'battery_certificate' THEN 'Batterijcertificaat'
      WHEN 'inspection_report' THEN 'Keuringsrapport'
      WHEN 'homologation_documents' THEN 'Homologatiedocumenten'
      ELSE r.key
    END);

    -- POLISH
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'pl', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Kontrola trakcji'
      WHEN 'emergency_brake_assist' THEN 'Asystent hamowania awaryjnego'
      WHEN 'brake_assist' THEN 'Asystent hamowania'
      WHEN 'lane_departure_warning' THEN 'Ostrzeżenie o zmianie pasa'
      WHEN 'lane_keep_assist' THEN 'Asystent pasa ruchu'
      WHEN 'blind_spot_monitor' THEN 'Monitor martwego pola'
      WHEN 'rear_cross_traffic_alert' THEN 'Alert ruchu poprzecznego z tyłu'
      WHEN 'driver_fatigue_detection' THEN 'Wykrywanie zmęczenia kierowcy'
      WHEN 'traffic_sign_recognition' THEN 'Rozpoznawanie znaków drogowych'
      WHEN 'pedestrian_detection' THEN 'Wykrywanie pieszych'
      WHEN 'cyclist_detection' THEN 'Wykrywanie rowerzystów'
      WHEN 'collision_warning' THEN 'Ostrzeżenie przed kolizją'
      WHEN 'hill_start_assist' THEN 'Asystent ruszania pod górę'
      WHEN 'hill_descent_control' THEN 'Kontrola zjazdu'
      WHEN 'adaptive_cruise_control' THEN 'Adaptacyjny tempomat'
      WHEN 'cruise_control' THEN 'Tempomat'
      WHEN 'speed_limiter' THEN 'Ogranicznik prędkości'
      WHEN 'parking_assist' THEN 'Asystent parkowania'
      WHEN 'automatic_parking' THEN 'Automatyczne parkowanie'
      WHEN 'rear_view_camera' THEN 'Kamera cofania'
      WHEN 'surround_view_camera' THEN 'Kamera 360°'
      WHEN 'front_parking_sensors' THEN 'Czujniki parkowania przód'
      WHEN 'rear_parking_sensors' THEN 'Czujniki parkowania tył'
      WHEN 'automatic_emergency_braking' THEN 'Automatyczne hamowanie awaryjne'
      WHEN 'traffic_jam_assist' THEN 'Asystent korków'
      WHEN 'keyless_entry' THEN 'Bezkluczykowy dostęp'
      WHEN 'keyless_start' THEN 'Bezkluczykowy rozruch'
      WHEN 'electric_tailgate' THEN 'Elektryczna klapa bagażnika'
      WHEN 'hands_free_tailgate' THEN 'Klapa bezdotykowa'
      WHEN 'remote_start' THEN 'Zdalny rozruch'
      WHEN 'heated_steering_wheel' THEN 'Podgrzewana kierownica'
      WHEN 'power_steering' THEN 'Wspomaganie kierownicy'
      WHEN 'adjustable_steering_wheel' THEN 'Regulowana kierownica'
      WHEN 'ambient_lighting' THEN 'Oświetlenie ambient'
      WHEN 'soft_close_doors' THEN 'Drzwi z cichym zamykaniem'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Porty USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'System nawigacji'
      WHEN 'digital_radio' THEN 'Radio cyfrowe'
      WHEN 'wifi_hotspot' THEN 'Hotspot WiFi'
      WHEN 'voice_control' THEN 'Sterowanie głosowe'
      WHEN 'touchscreen_display' THEN 'Ekran dotykowy'
      WHEN 'rear_entertainment_system' THEN 'System rozrywki z tyłu'
      WHEN 'leather_interior' THEN 'Wnętrze skórzane'
      WHEN 'fabric_interior' THEN 'Wnętrze materiałowe'
      WHEN 'alcantara_interior' THEN 'Wnętrze Alcantara'
      WHEN 'carbon_fiber_trim' THEN 'Wykończenie z włókna węglowego'
      WHEN 'wood_trim' THEN 'Wykończenie drewniane'
      WHEN 'adjustable_ambient_light' THEN 'Regulowane oświetlenie ambient'
      WHEN 'multifunction_steering_wheel' THEN 'Wielofunkcyjna kierownica'
      WHEN 'digital_dashboard' THEN 'Cyfrowy kokpit'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Konfigurowalny zestaw wskaźników'
      WHEN 'alloy_wheels' THEN 'Felgi aluminiowe'
      WHEN 'steel_wheels' THEN 'Felgi stalowe'
      WHEN 'roof_rails' THEN 'Relingi dachowe'
      WHEN 'panoramic_roof' THEN 'Dach panoramiczny'
      WHEN 'sunroof' THEN 'Szyberdach'
      WHEN 'tinted_windows' THEN 'Przyciemniane szyby'
      WHEN 'metallic_paint' THEN 'Lakier metalik'
      WHEN 'pearlescent_paint' THEN 'Lakier perłowy'
      WHEN 'tow_hook' THEN 'Hak holowniczy'
      WHEN 'electric_mirrors' THEN 'Lusterka elektryczne'
      WHEN 'led_headlights' THEN 'Reflektory LED'
      WHEN 'xenon_headlights' THEN 'Reflektory ksenonowe'
      WHEN 'matrix_led' THEN 'Matrix LED'
      WHEN 'adaptive_headlights' THEN 'Reflektory adaptacyjne'
      WHEN 'automatic_headlights' THEN 'Automatyczne światła'
      WHEN 'daytime_running_lights' THEN 'Światła do jazdy dziennej'
      WHEN 'fog_lights' THEN 'Światła przeciwmgielne'
      WHEN 'cornering_lights' THEN 'Światła doświetlające zakręty'
      WHEN 'manual_air_conditioning' THEN 'Klimatyzacja manualna'
      WHEN 'automatic_climate_control' THEN 'Klimatyzacja automatyczna'
      WHEN 'dual_zone_climate' THEN 'Klimatyzacja dwustrefowa'
      WHEN 'tri_zone_climate' THEN 'Klimatyzacja trzystrefowa'
      WHEN 'air_quality_sensor' THEN 'Czujnik jakości powietrza'
      WHEN 'pollen_filter' THEN 'Filtr pyłkowy'
      WHEN 'ventilated_seats_climate' THEN 'Fotele wentylowane'
      WHEN 'heated_seats' THEN 'Fotele podgrzewane'
      WHEN 'ventilated_seats' THEN 'Fotele wentylowane'
      WHEN 'electric_seats' THEN 'Fotele elektryczne'
      WHEN 'memory_seats' THEN 'Fotele z pamięcią'
      WHEN 'massage_seats' THEN 'Fotele z masażem'
      WHEN 'sport_seats' THEN 'Fotele sportowe'
      WHEN 'rear_adjustable_seats' THEN 'Regulowane tylne siedzenia'
      WHEN 'folding_rear_seats' THEN 'Składane tylne siedzenia'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'System alarmowy'
      WHEN 'immobilizer' THEN 'Immobilizer'
      WHEN 'anti_theft_system' THEN 'System antykradzieżowy'
      WHEN 'wheel_lock' THEN 'Blokada kół'
      WHEN 'interior_monitoring' THEN 'Monitoring wnętrza'
      WHEN 'gps_tracker' THEN 'Lokalizator GPS'
      WHEN 'drive_modes' THEN 'Tryby jazdy'
      WHEN 'sport_mode' THEN 'Tryb sportowy'
      WHEN 'eco_mode' THEN 'Tryb ECO'
      WHEN 'all_wheel_drive' THEN 'Napęd na cztery koła'
      WHEN 'differential_lock' THEN 'Blokada mechanizmu różnicowego'
      WHEN 'air_suspension' THEN 'Zawieszenie pneumatyczne'
      WHEN 'adaptive_suspension' THEN 'Zawieszenie adaptacyjne'
      WHEN 'sport_exhaust' THEN 'Sportowy układ wydechowy'
      WHEN 'performance_brakes' THEN 'Hamulce sportowe'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Hamowanie odzyskowe'
      WHEN 'start_stop_system' THEN 'System Start/Stop'
      WHEN 'spare_wheel' THEN 'Koło zapasowe'
      WHEN 'tire_repair_kit' THEN 'Zestaw naprawczy opon'
      WHEN 'onboard_computer' THEN 'Komputer pokładowy'
      WHEN 'service_history' THEN 'Historia serwisowa'
      WHEN 'warranty' THEN 'Gwarancja'
      WHEN 'battery_certificate' THEN 'Certyfikat baterii'
      WHEN 'inspection_report' THEN 'Raport z przeglądu'
      WHEN 'homologation_documents' THEN 'Dokumenty homologacyjne'
      ELSE r.key
    END);

    -- ROMANIAN
    INSERT INTO vehicle_option_translations (option_id, language_code, label) VALUES
    (r.id, 'ro', CASE r.key
      WHEN 'abs' THEN 'ABS'
      WHEN 'esp' THEN 'ESP'
      WHEN 'traction_control' THEN 'Control tracțiune'
      WHEN 'emergency_brake_assist' THEN 'Asistență frânare de urgență'
      WHEN 'brake_assist' THEN 'Asistență la frânare'
      WHEN 'lane_departure_warning' THEN 'Avertizare părăsire bandă'
      WHEN 'lane_keep_assist' THEN 'Asistent menținere bandă'
      WHEN 'blind_spot_monitor' THEN 'Monitor unghi mort'
      WHEN 'rear_cross_traffic_alert' THEN 'Alertă trafic transversal spate'
      WHEN 'driver_fatigue_detection' THEN 'Detectare oboseală șofer'
      WHEN 'traffic_sign_recognition' THEN 'Recunoaștere semne de circulație'
      WHEN 'pedestrian_detection' THEN 'Detectare pietoni'
      WHEN 'cyclist_detection' THEN 'Detectare bicicliști'
      WHEN 'collision_warning' THEN 'Avertizare coliziune'
      WHEN 'hill_start_assist' THEN 'Asistent pornire în rampă'
      WHEN 'hill_descent_control' THEN 'Control coborâre'
      WHEN 'adaptive_cruise_control' THEN 'Tempomat adaptiv'
      WHEN 'cruise_control' THEN 'Tempomat'
      WHEN 'speed_limiter' THEN 'Limitator de viteză'
      WHEN 'parking_assist' THEN 'Asistent parcare'
      WHEN 'automatic_parking' THEN 'Parcare automată'
      WHEN 'rear_view_camera' THEN 'Cameră marșarier'
      WHEN 'surround_view_camera' THEN 'Cameră 360°'
      WHEN 'front_parking_sensors' THEN 'Senzori parcare față'
      WHEN 'rear_parking_sensors' THEN 'Senzori parcare spate'
      WHEN 'automatic_emergency_braking' THEN 'Frânare de urgență automată'
      WHEN 'traffic_jam_assist' THEN 'Asistent trafic'
      WHEN 'keyless_entry' THEN 'Acces fără cheie'
      WHEN 'keyless_start' THEN 'Pornire fără cheie'
      WHEN 'electric_tailgate' THEN 'Hayon electric'
      WHEN 'hands_free_tailgate' THEN 'Hayon hands-free'
      WHEN 'remote_start' THEN 'Pornire la distanță'
      WHEN 'heated_steering_wheel' THEN 'Volan încălzit'
      WHEN 'power_steering' THEN 'Servodirecție'
      WHEN 'adjustable_steering_wheel' THEN 'Volan reglabil'
      WHEN 'ambient_lighting' THEN 'Iluminare ambientală'
      WHEN 'soft_close_doors' THEN 'Uși cu închidere lină'
      WHEN 'bluetooth' THEN 'Bluetooth'
      WHEN 'usb_ports' THEN 'Porturi USB'
      WHEN 'apple_carplay' THEN 'Apple CarPlay'
      WHEN 'android_auto' THEN 'Android Auto'
      WHEN 'navigation_system' THEN 'Sistem de navigație'
      WHEN 'digital_radio' THEN 'Radio digital'
      WHEN 'wifi_hotspot' THEN 'Hotspot WiFi'
      WHEN 'voice_control' THEN 'Control vocal'
      WHEN 'touchscreen_display' THEN 'Ecran tactil'
      WHEN 'rear_entertainment_system' THEN 'Sistem divertisment spate'
      WHEN 'leather_interior' THEN 'Interior din piele'
      WHEN 'fabric_interior' THEN 'Interior din material textil'
      WHEN 'alcantara_interior' THEN 'Interior Alcantara'
      WHEN 'carbon_fiber_trim' THEN 'Ornamente fibră de carbon'
      WHEN 'wood_trim' THEN 'Ornamente din lemn'
      WHEN 'adjustable_ambient_light' THEN 'Lumină ambientală reglabilă'
      WHEN 'multifunction_steering_wheel' THEN 'Volan multifuncțional'
      WHEN 'digital_dashboard' THEN 'Bord digital'
      WHEN 'head_up_display' THEN 'Head-Up Display'
      WHEN 'configurable_instrument_cluster' THEN 'Tablou de bord configurabil'
      WHEN 'alloy_wheels' THEN 'Jante din aliaj'
      WHEN 'steel_wheels' THEN 'Jante din oțel'
      WHEN 'roof_rails' THEN 'Bare longitudinale'
      WHEN 'panoramic_roof' THEN 'Trapa panoramică'
      WHEN 'sunroof' THEN 'Trapa'
      WHEN 'tinted_windows' THEN 'Geamuri fumurii'
      WHEN 'metallic_paint' THEN 'Vopsea metalizată'
      WHEN 'pearlescent_paint' THEN 'Vopsea perlată'
      WHEN 'tow_hook' THEN 'Cârlig remorcare'
      WHEN 'electric_mirrors' THEN 'Oglinzi electrice'
      WHEN 'led_headlights' THEN 'Faruri LED'
      WHEN 'xenon_headlights' THEN 'Faruri xenon'
      WHEN 'matrix_led' THEN 'LED Matrix'
      WHEN 'adaptive_headlights' THEN 'Faruri adaptive'
      WHEN 'automatic_headlights' THEN 'Faruri automate'
      WHEN 'daytime_running_lights' THEN 'Lumini de zi'
      WHEN 'fog_lights' THEN 'Proiectoare ceață'
      WHEN 'cornering_lights' THEN 'Lumini de virare'
      WHEN 'manual_air_conditioning' THEN 'Aer condiționat manual'
      WHEN 'automatic_climate_control' THEN 'Climatizare automată'
      WHEN 'dual_zone_climate' THEN 'Climatizare bi-zonă'
      WHEN 'tri_zone_climate' THEN 'Climatizare tri-zonă'
      WHEN 'air_quality_sensor' THEN 'Senzor calitate aer'
      WHEN 'pollen_filter' THEN 'Filtru de polen'
      WHEN 'ventilated_seats_climate' THEN 'Scaune ventilate'
      WHEN 'heated_seats' THEN 'Scaune încălzite'
      WHEN 'ventilated_seats' THEN 'Scaune ventilate'
      WHEN 'electric_seats' THEN 'Scaune electrice'
      WHEN 'memory_seats' THEN 'Scaune cu memorie'
      WHEN 'massage_seats' THEN 'Scaune cu masaj'
      WHEN 'sport_seats' THEN 'Scaune sport'
      WHEN 'rear_adjustable_seats' THEN 'Scaune spate reglabile'
      WHEN 'folding_rear_seats' THEN 'Scaune spate rabatabile'
      WHEN 'child_seat_isofix' THEN 'ISOFIX'
      WHEN 'alarm_system' THEN 'Sistem de alarmă'
      WHEN 'immobilizer' THEN 'Imobilizator'
      WHEN 'anti_theft_system' THEN 'Sistem antifurt'
      WHEN 'wheel_lock' THEN 'Blocaj roți'
      WHEN 'interior_monitoring' THEN 'Monitorizare interior'
      WHEN 'gps_tracker' THEN 'Localizator GPS'
      WHEN 'drive_modes' THEN 'Moduri de conducere'
      WHEN 'sport_mode' THEN 'Mod sport'
      WHEN 'eco_mode' THEN 'Mod ECO'
      WHEN 'all_wheel_drive' THEN 'Tracțiune integrală'
      WHEN 'differential_lock' THEN 'Blocare diferențial'
      WHEN 'air_suspension' THEN 'Suspensie pneumatică'
      WHEN 'adaptive_suspension' THEN 'Suspensie adaptivă'
      WHEN 'sport_exhaust' THEN 'Evacuare sport'
      WHEN 'performance_brakes' THEN 'Frâne de performanță'
      WHEN 'launch_control' THEN 'Launch Control'
      WHEN 'turbo' THEN 'Turbo'
      WHEN 'regenerative_braking' THEN 'Frânare regenerativă'
      WHEN 'start_stop_system' THEN 'Sistem Start/Stop'
      WHEN 'spare_wheel' THEN 'Roată de rezervă'
      WHEN 'tire_repair_kit' THEN 'Kit reparare anvelope'
      WHEN 'onboard_computer' THEN 'Computer de bord'
      WHEN 'service_history' THEN 'Istoric service'
      WHEN 'warranty' THEN 'Garanție'
      WHEN 'battery_certificate' THEN 'Certificat baterie'
      WHEN 'inspection_report' THEN 'Raport de inspecție'
      WHEN 'homologation_documents' THEN 'Documente de omologare'
      ELSE r.key
    END);

  END LOOP;
END $$;
