
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://inqqnsvlimtpjxjxuzaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucXFuc3ZsaW10cGp4anh1emFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDIyNzksImV4cCI6MjA2MDU3ODI3OX0.crFcbhfMi7w9BxpBHbzRMSfuvzmUZY1B_MS8r8gucfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
  }
});
